#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

#export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true

debconf-set-selections /preseed.txt
rm /preseed.txt

# install packages
pkg update
pkg install --reinstall locales
pkg install firefox-esr-l10n-ru

dpkg-reconfigure locales
dpkg-reconfigure keyboard-configuration
dpkg-reconfigure tzdata
dpkg-reconfigure console-setup

if [ ! -d /etc/systemd/system/console-setup.service.d ]; then
    mkdir -p /etc/systemd/system/console-setup.service.d
fi
cat >/etc/systemd/system/console-setup.service.d/override.conf <<EOF
[Unit]
After=systemd-tmpfiles-setup.service
EOF
