#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

timezone_to_array

DEBCONF_SETTINGS=(
    "keyboard-configuration  keyboard-configuration/layoutcode       string  us,ru"
    "keyboard-configuration  keyboard-configuration/variant  select  Russian"
    "keyboard-configuration  keyboard-configuration/toggle   select  Alt+Shift"
    "locales locales/locales_to_be_generated multiselect     ru_RU.UTF-8 UTF-8"
    "locales locales/default_environment_locale      select  ru_RU.UTF-8"
)

if [ $DISTRIBUTION != "buster" ]; then
    DEBCONF_SETTINGS+=(
        "keyboard-configuration  keyboard-configuration/layout   select  Russian"
    )
fi

for SETTING in "${DEBCONF_SETTINGS[@]}"; do
    echo "$SETTING" | debconf-set-selections -v
done

dpkg --remove --force-depends locales
rm -f /etc/locale.gen
pkg update
pkg install locales

#DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
DEBIAN_FRONTEND=noninteractive dpkg-reconfigure keyboard-configuration

pkg install firefox-esr-l10n-ru libreoffice-l10n-ru
