#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
#set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

if [ -z $DISTRIBUTION ]; then
    DISTRIBUTION="bullseye"
fi
if [ -z $APT_CMD ]; then
    APT_CMD="apt-get"
fi
if [ -z $APT_OPTIONS ]; then
    APT_OPTIONS="-y"
fi
if [ -z $OUTPUT ]; then
    OUTPUT="/dev/stdout"
fi

VBOX_VERSION=$(wget -O- https://download.virtualbox.org/virtualbox/LATEST.TXT)

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A2F683C52980AECF

echo "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian $DISTRIBUTION contrib" >/etc/apt/sources.list.d/virtualbox.list

# install packages
$APT_CMD update >>$OUTPUT 2>&1 &&
    $APT_CMD install $APT_OPTIONS linux-headers-amd64 gcc make >>$OUTPUT 2>&1

echo virtualbox-ext-pack virtualbox-ext-pack/license select true | sudo debconf-set-selections

# install packages
$APT_CMD install $APT_OPTIONS virtualbox-6.1 >>$OUTPUT 2>&1

wget -c https://download.virtualbox.org/virtualbox/$VBOX_VERSION/Oracle_VM_VirtualBox_Extension_Pack-$VBOX_VERSION.vbox-extpack

VBoxManage extpack install --replace $SCRIPT_DIR/Oracle_VM_VirtualBox_Extension_Pack-$VBOX_VERSION.vbox-extpack
