#!/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

VBOX_VERSION=$(wget -O- https://download.virtualbox.org/virtualbox/LATEST.TXT)

rm -Rf /usr/share/icons/hicolor/256x256 >>$OUTPUT 2>&1
rm -Rf /usr/share/icons/hicolor/512x512 >>$OUTPUT 2>&1
rm -Rf /usr/share/icons/gnome/256x256 >>$OUTPUT 2>&1
