#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

language_to_array

pkg update

# install packages
case $DISTRIBUTION in
stretch | buster)
    install_packages --package-list="$SCRIPT_DIR/package.list" --replace-packages="inkscape=inkscape/$DISTRIBUTION-backports" --delete-packages="telegram-desktop"
    ;;
bullseye)
    install_packages --package-list="$SCRIPT_DIR/package.list" --replace-packages="inkscape=inkscape/$DISTRIBUTION-backports telegram-desktop=telegram-desktop/$DISTRIBUTION-backports"
    ;;
bookworm)
    install_packages --package-list="$SCRIPT_DIR/package.list" --replace-packages="telegram-desktop=telegram-desktop/$DISTRIBUTION-backports"
    ;;
*)
    install_packages --package-list="$SCRIPT_DIR/package.list"
    ;;
esac

if grep -q 'imagemagick' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    rm -f /usr/share/applications/display-im6.q16.desktop
fi
if grep -q 'obs-studio' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    if [ -f /usr/share/icons/hicolor/256x256/apps/com.obsproject.Studio.png ]; then
        mv /usr/share/icons/hicolor/256x256/apps/com.obsproject.Studio.png /usr/share/pixmaps/
    elif [ -f /usr/share/icons/hicolor/256x256/apps/obs.png ]; then
        mv /usr/share/icons/hicolor/256x256/apps/obs.png /usr/share/pixmaps/
    fi
fi
if grep -q 'pdfmod' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    for FOLDER in $(ls /usr/share/icons/elementary-xfce/apps | grep -E '^[0-9]+$'); do
        cd /usr/share/icons/elementary-xfce/apps/$FOLDER
        ln -s pdfshuffler.png pdfmod.png
    done
fi
if grep -q 'guake' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    for FOLDER in $(ls /usr/share/icons/elementary-xfce/apps | grep -E '^[0-9]+$'); do
        cd /usr/share/icons/elementary-xfce/apps/$FOLDER
        ln -s utilities-terminal.png guake.png
    done
fi
if grep -q 'drawio' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    for FOLDER in $(ls /usr/share/icons/elementary-xfce/apps | grep -E '^[0-9]+$'); do
        cd /usr/share/icons/elementary-xfce/apps/$FOLDER
        ln -s libreoffice-draw.png drawio.png
    done
fi
update-icon-caches /usr/share/icons/*
