#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

function language_to_array() {
    local IFS
    IFS="_"
    LANG=($LOCALE)
}
language_to_array

apt-get $INSTALL_OPTIONS update >>$OUTPUT 2>&1

# install packages
if [ -f $SCRIPT_DIR/package.list ]; then
    if [ $DISTRIBUTION = "stretch" ] || [ $DISTRIBUTION = "buster" ]; then
        DEBIAN_FRONTEND=noninteractive \
            apt-get $INSTALL_OPTIONS install \
            $(grep -vE "^\s*#" $SCRIPT_DIR/package.list | sed "s,inkscape,inkscape/$DISTRIBUTION-backports,g;/telegram-desktop/d" | tr "\n" " ") >>$OUTPUT 2>&1
    elif [ $DISTRIBUTION = "bullseye" ]; then
        DEBIAN_FRONTEND=noninteractive \
            apt-get $INSTALL_OPTIONS install \
            $(grep -vE "^\s*#" $SCRIPT_DIR/package.list | sed "s,inkscape,inkscape/$DISTRIBUTION-backports,g;s,telegram-desktop,telegram-desktop/$DISTRIBUTION-backports,g" | tr "\n" " ") >>$OUTPUT 2>&1
    else
        DEBIAN_FRONTEND=noninteractive \
            apt-get $INSTALL_OPTIONS install \
            $(grep -vE "^\s*#" $SCRIPT_DIR/package.list | tr "\n" " ") >>$OUTPUT 2>&1
    fi
fi

if grep -q 'imagemagick' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    rm -f /usr/share/applications/display-im6.q16.desktop
fi
if grep -q 'obs-studio' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    if [ -f /usr/share/icons/hicolor/256x256/apps/com.obsproject.Studio.png ]; then
        mv /usr/share/icons/hicolor/256x256/apps/com.obsproject.Studio.png /usr/share/pixmaps/
    elif [ -f /usr/share/icons/hicolor/256x256/apps/obs.png ]; then
        mv /usr/share/icons/hicolor/256x256/apps/obs.png /usr/share/pixmaps/
    fi
fi
if grep -q 'pdfmod' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    for FOLDER in $(ls /usr/share/icons/elementary-xfce/apps | grep -E '^[0-9]+$'); do
        cd /usr/share/icons/elementary-xfce/apps/$FOLDER
        ln -s pdfshuffler.png pdfmod.png
    done
fi
if grep -q 'guake' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    for FOLDER in $(ls /usr/share/icons/elementary-xfce/apps | grep -E '^[0-9]+$'); do
        cd /usr/share/icons/elementary-xfce/apps/$FOLDER
        ln -s utilities-terminal.png guake.png
    done
fi
if grep -q 'drawio' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    for FOLDER in $(ls /usr/share/icons/elementary-xfce/apps | grep -E '^[0-9]+$'); do
        cd /usr/share/icons/elementary-xfce/apps/$FOLDER
        ln -s libreoffice-draw.png drawio.png
    done
fi
update-icon-caches /usr/share/icons/*
