#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

pkg update

if [ $DISTRIBUTION = "orel" ]; then
    pkg install opensc=0.16.0* opensc-pkcs11=0.16.0*
    apt-mark hold opensc opensc-pkcs11
fi

cd $SCRIPT_DIR
# install packages
pkg install cts libnss3-tools iptables

rm -f /etc/cts/.csum
cat <<EOF >/etc/cts/filelist.current
/etc/cts/defconfig
/etc/cts/defconfig1
/etc/cts/defconfig2
/etc/cts/request.xsl
/etc/init.d/cts
/usr/bin/autoctsic
/usr/bin/cts
/usr/bin/ctsg
/usr/sbin/ctsd
/usr/sbin/ctsic
EOF
ctsic compute

sed -i '/import_bookmarks/d' /etc/chromium/master_preferences

PACKAGE="cts"
echo "PACKAGE=$PACKAGE" >/.package
echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g' | sed 's/:/-/g')" >>/.package
