#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

apt-get update >>$OUTPUT 2>&1

if [ $DISTRIBUTION = "orel" ]; then
    apt-get install -y opensc=0.16.0* opensc-pkcs11=0.16.0*
    apt-mark hold opensc opensc-pkcs11
fi

cd $SCRIPT_DIR
#wget --no-check-certificate -c https://ftp2.minios.dev/cts-3.7.6-70.ks1.astra2.11_amd64.deb >>$OUTPUT 2>&1
wget --no-check-certificate -c https://ftp2.minios.dev/cts-3.7.6-70.ks1.$DISTRIBUTION\_amd64.deb >>$OUTPUT 2>&1
# install packages

#apt-get install -y $SCRIPT_DIR/cts-3.7.6-70.ks1.astra2.11_amd64.deb libnss3-tools iptables >>$OUTPUT 2>&1
apt-get install -y $SCRIPT_DIR/cts-3.7.6-70.ks1.$DISTRIBUTION\_amd64.deb libnss3-tools iptables >>$OUTPUT 2>&1
rm -f $SCRIPT_DIR/cts-3.7.6-70*.deb >>$OUTPUT 2>&1
#rm -f $SCRIPT_DIR/cts-3.7.6-70.ks1.astra2.11_amd64.deb >>$OUTPUT 2>&1

rm -f /etc/cts/.csum
cat <<EOF >/etc/cts/filelist.current
/etc/cts/defconfig
/etc/cts/defconfig1
/etc/cts/defconfig2
/etc/cts/request.xsl
/etc/init.d/cts
/usr/bin/autoctsic
/usr/bin/cts
/usr/bin/ctsg
/usr/sbin/ctsd
/usr/sbin/ctsic
EOF
ctsic compute >>$OUTPUT 2>&1

sed -i '/import_bookmarks/d' /etc/chromium/master_preferences

PACKAGE="cts"
echo "PACKAGE=$PACKAGE" >/.package
echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g' | sed 's/:/-/g')" >>/.package

