#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

apt-get update >>$OUTPUT 2>&1

# install packages
    apt-get install -y \
        snapd >>$OUTPUT 2>&1

snap install -y thincast-client
