#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

./setup-training-8.3.20.1789-x86_64.run
rm ./setup-training-8.3.20.1789-x86_64.run