#!/bin/bash

rm -Rf /usr/share/icons/Adwaita/256x256 
rm -Rf /usr/share/icons/Adwaita/512x512 
rm -Rf /usr/share/icons/hicolor/256x256 
rm -Rf /usr/share/icons/hicolor/512x512 
rm -Rf /usr/share/icons/gnome/256x256 
