#!/bin/bash

if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
    if ! grep -q slim $SCRIPT_DIR/$PACKAGE_VARIANT.list; then
        rm -rf /usr/share/slim
    fi
fi

if [ $PACKAGE_VARIANT = "minimum" ]; then
    find /usr/share/backgrounds -type f -not \( -name 'MiniOS-wallpaper-jungle.svg' -or -name 'MiniOS-background-jungle.svg' \) -delete
fi
