#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

echo "keyboard-configuration	keyboard-configuration/variant	select	English (US)" | debconf-set-selections

# install packages
if [ DESKTOP_ENVIRONMENT = "astra-fly" ]; then
    pkg update
    pkg install \
        xorg-all-main
elif [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
    install_packages
fi

if [ $PACKAGE_VARIANT != "minimum" ] && [ $PACKAGE_VARIANT != "standard" ]; then
    pkg install xrdp xorgxrdp
    adduser xrdp ssl-cert
    rm /etc/ssl/private/ssl-cert-snakeoil.key /etc/ssl/certs/ssl-cert-snakeoil.pem

    echo "Enable xrdp.service autostart."
    cat <<EOF >/usr/lib/systemd/system/xrdp-configure.service
[Unit]
Description=Configure xrdp service
Before=xrdp.service

[Service]
Type=oneshot
ExecStart=-/bin/sh -c 'if [ ! -f /var/log/xrdp.log ]; then touch /var/log/xrdp.log; chown xrdp:adm /var/log/xrdp.log; chmod 640 /var/log/xrdp.log; fi; if [ ! -f /etc/ssl/private/ssl-cert-snakeoil.key ]; then make-ssl-cert generate-default-snakeoil; fi'
RemainAfterExit=true
StandardOutput=journal

[Install]
WantedBy=multi-user.target
EOF
    systemctl enable xrdp-configure
    systemctl disable xrdp
fi

if [ $DESKTOP_ENVIRONMENT = "flux" ]; then
    USER_NAME="root"
fi
cat <<EOF >/usr/lib/systemd/system/xorg.service
[Unit]
Description=X-Window
ConditionKernelCommandLine=!text
After=systemd-user-sessions.service

[Service]
ExecStart=/bin/su --login -c "/usr/bin/startx -- :0 vt7 -ac -nolisten tcp" $USER_NAME

[Install]
[WantedBy]=graphical.target

EOF

if [ -d /etc/systemd/system ]; then
    mkdir -p /etc/systemd/system
fi
ln -s /usr/lib/systemd/system/xorg.service /etc/systemd/system/display-manager.service
if [ -L /etc/systemd/system/display-manager.service ]; then
    echo "Display manager link exists."
else
    exit 1
fi
