#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

LNG="$(echo $LOCALE | cut -d_ -f1)"

pkg update

echo "nodm nodm/enabled boolean true" | debconf-set-selections
echo "samba-common samba-common/dhcp boolean false" | debconf-set-selections

# install packages
if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
    install_packages --package-list="$SCRIPT_DIR/$PACKAGE_VARIANT.list"
fi
sleep 3
echo here1
if [ $LOCALE != "en_US" ]; then
    echo here2
    install_packages --package-list="$SCRIPT_DIR/$PACKAGE_VARIANT-l10n.list"
fi
echo here3
sleep 3

if [ -f /usr/share/applications/yad-icon-browser.desktop ]; then
    rm -f /usr/share/applications/yad-icon-browser.desktop
fi

rm -f /usr/share/applications/minios-installer.desktop

if grep -q slim $SCRIPT_DIR/$PACKAGE_VARIANT.list && ! grep -q "#slim" $SCRIPT_DIR/$PACKAGE_VARIANT.list; then
    sed -i 's,# hidecursor          false,hidecursor            false,g' /etc/slim.conf
    sed -i 's,screenshot_cmd      scrot /root/slim.png,# screenshot_cmd      scrot /root/slim.png,g' /etc/slim.conf
    sed -i 's,#auto_login          no,auto_login          yes,g' /etc/slim.conf
    sed -i 's,current_theme       debian-softwaves,current_theme       minios,g' /etc/slim.conf
    sed -i "s/#default_user        simone/default_user        $USER_NAME/g" /etc/slim.conf
fi

if ! grep -q pulseaudio $SCRIPT_DIR/$PACKAGE_VARIANT.list || grep -q "#slim" $SCRIPT_DIR/$PACKAGE_VARIANT.list; then
    cat <<EOF >/usr/bin/audio-allowuser.sh
#!/bin/bash
if ! grep audio /etc/group | grep \$(id -nu 1000) >/dev/null; then
    usermod -a -G audio \$(id -nu 1000)
fi
EOF
    chmod +x /usr/bin/audio-allowuser.sh
    cat <<EOF >/usr/lib/systemd/system/audio-allowuser.service
[Unit]
Description=Allow user to use ALSA
#After=network.target

[Service]
Type=oneshot
ExecStart=/usr/bin/audio-allowuser.sh
RemainAfterExit=true
ExecStop=
StandardOutput=journal

[Install]
WantedBy=multi-user.target
EOF
    systemctl enable audio-allowuser.service
fi
