#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

apt-get $INSTALL_OPTIONS update -y >>$OUTPUT 2>&1 &&
    curl -s https://api.github.com/repos/johnfactotum/foliate/releases/latest | grep browser_download_url | grep '\.deb' | cut -d '"' -f 4 | wget -i - &&
    apt-get $INSTALL_OPTIONS install ./*foliate*.deb >>$OUTPUT 2>&1
