#!/bin/bash
# Usage:    container_build_run [DISTRIBUTION] [DESKTOP_ENVIRONMENT] [PACKAGE_VARIANT] [DISTRIBUTION_ARCH] [INITRD_TYPE] [KERNEL_TYPE] [KERNEL_BPO] [KERNEL_AUFS] [CONP_TYPE] [LOCALE] [TIMEZONE]
# Example:  container_build_run bullseye       xfce                  standard          amd64               livekit       default       true         true          zstd        en_US    Etc/UTC

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

. $SCRIPT_DIR/linux-live/minioslib || exit 1

container_engine="docker"

container_build_run buster xfce maximum amd64 livekit rt true false zstd en_US Etc/UTC
container_build_run bullseye xfce standard amd64 uird default false true zstd ru_RU Europe/Moscow
