#!/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

. $SCRIPT_DIR/linux-live/minioslib || exit 1
. $SCRIPT_DIR/linux-live/config || exit 1
if [ -z $OUTPUT ]; then
    . $SCRIPT_DIR/linux-live/buildconfig || exit 1
fi

function build() {
    sed -i -e "/DISTRIBUTION_TYPE=/s/=.*/=\"$DISTRIBUTION_TYPE\"/" $SCRIPT_DIR/linux-live/buildconfig
    sed -i -e "/DISTRIBUTION=/s/=.*/=\"$DISTRIBUTION\"/" $SCRIPT_DIR/linux-live/buildconfig
    sed -i -e "/DISTRIBUTION_ARCH=/s/=.*/=\"$DISTRIBUTION_ARCH\"/" $SCRIPT_DIR/linux-live/buildconfig
    sed -i -e "/DESKTOP_ENVIRONMENT=/s/=.*/=\"$DESKTOP_ENVIRONMENT\"/" $SCRIPT_DIR/linux-live/buildconfig
    sed -i -e "/PACKAGE_VARIANT=/s/=.*/=\"$PACKAGE_VARIANT\"/" $SCRIPT_DIR/linux-live/buildconfig
    sed -i -e "/INITRD_TYPE=/s/=.*/=\"$INITRD_TYPE\"/" $SCRIPT_DIR/linux-live/buildconfig
    sed -i -e "/KERNEL_TYPE=/s/=.*/=\"$KERNEL_TYPE\"/" $SCRIPT_DIR/linux-live/buildconfig
    sed -i -e "/KERNEL_BPO=/s/=.*/=\"$KERNEL_BPO\"/" $SCRIPT_DIR/linux-live/buildconfig
    sed -i -e "/KERNEL_AUFS=/s/=.*/=\"$KERNEL_AUFS\"/" $SCRIPT_DIR/linux-live/buildconfig
    sed -i -e "/COMP_TYPE=/s/=.*/=\"$COMP_TYPE\"/" $SCRIPT_DIR/linux-live/buildconfig
    sed -i -e "/LOCALE=/s/=.*/=\"$LOCALE\"/" $SCRIPT_DIR/linux-live/buildconfig
    sed -i -e "/TIMEZONE=/s/=.*/=\"${TIMEZONE//\//\\/}\"/" $SCRIPT_DIR/linux-live/buildconfig
    $SCRIPT_DIR/install -
}

# bullseye xfce
DISTRIBUTION_TYPE="debian"
DISTRIBUTION="bullseye"
DISTRIBUTION_ARCH="amd64"
DESKTOP_ENVIRONMENT="xfce"
PACKAGE_VARIANT="standard"
INITRD_TYPE="livekit"
KERNEL_TYPE="default"
KERNEL_BPO="false"
KERNEL_AUFS="false"
COMP_TYPE="xz"
LOCALE="en_US"
TIMEZONE="Etc/UTC"
build

DISTRIBUTION_TYPE="debian"
DISTRIBUTION="bullseye"
DISTRIBUTION_ARCH="i386"
DESKTOP_ENVIRONMENT="xfce"
PACKAGE_VARIANT="standard"
INITRD_TYPE="livekit"
KERNEL_TYPE="default"
KERNEL_BPO="false"
KERNEL_AUFS="false"
COMP_TYPE="xz"
LOCALE="en_US"
TIMEZONE="Etc/UTC"
build

DISTRIBUTION_TYPE="debian"
DISTRIBUTION="bullseye"
DISTRIBUTION_ARCH="amd64"
DESKTOP_ENVIRONMENT="xfce"
INITRD_TYPE="livekit"
KERNEL_TYPE="default"
KERNEL_BPO="false"
KERNEL_AUFS="false"
COMP_TYPE="xz"
LOCALE="en_US"
TIMEZONE="Etc/UTC"
PACKAGE_VARIANT="minimal"
build

DISTRIBUTION_TYPE="debian"
DISTRIBUTION="bullseye"
DISTRIBUTION_ARCH="i386"
DESKTOP_ENVIRONMENT="xfce"
PACKAGE_VARIANT="minimal"
INITRD_TYPE="livekit"
KERNEL_TYPE="default"
KERNEL_BPO="false"
KERNEL_AUFS="false"
COMP_TYPE="xz"
LOCALE="en_US"
TIMEZONE="Etc/UTC"
build

# buster xfce
DISTRIBUTION_TYPE="debian"
DISTRIBUTION="buster"
DISTRIBUTION_ARCH="amd64"
DESKTOP_ENVIRONMENT="xfce"
PACKAGE_VARIANT="standard"
INITRD_TYPE="livekit"
KERNEL_TYPE="default"
KERNEL_BPO="false"
KERNEL_AUFS="false"
COMP_TYPE="xz"
LOCALE="en_US"
TIMEZONE="Etc/UTC"
build

DISTRIBUTION_TYPE="debian"
DISTRIBUTION="buster"
DISTRIBUTION_ARCH="i386"
DESKTOP_ENVIRONMENT="xfce"
PACKAGE_VARIANT="standard"
INITRD_TYPE="livekit"
KERNEL_TYPE="default"
KERNEL_BPO="false"
KERNEL_AUFS="false"
COMP_TYPE="xz"
LOCALE="en_US"
TIMEZONE="Etc/UTC"
build

DISTRIBUTION_TYPE="debian"
DISTRIBUTION="buster"
DISTRIBUTION_ARCH="amd64"
DESKTOP_ENVIRONMENT="xfce"
PACKAGE_VARIANT="minimal"
INITRD_TYPE="livekit"
KERNEL_TYPE="default"
KERNEL_BPO="false"
KERNEL_AUFS="false"
COMP_TYPE="xz"
LOCALE="en_US"
TIMEZONE="Etc/UTC"
build

DISTRIBUTION_TYPE="debian"
DISTRIBUTION="buster"
DISTRIBUTION_ARCH="i386"
DESKTOP_ENVIRONMENT="xfce"
PACKAGE_VARIANT="minimal"
INITRD_TYPE="livekit"
KERNEL_TYPE="default"
KERNEL_BPO="false"
KERNEL_AUFS="false"
COMP_TYPE="xz"
LOCALE="en_US"
TIMEZONE="Etc/UTC"
build

# buster flux
DISTRIBUTION_TYPE="debian"
DISTRIBUTION="buster"
DISTRIBUTION_ARCH="i386"
DESKTOP_ENVIRONMENT="flux"
PACKAGE_VARIANT="minimal"
INITRD_TYPE="livekit"
KERNEL_TYPE="default"
KERNEL_BPO="false"
KERNEL_AUFS="false"
COMP_TYPE="xz"
LOCALE="en_US"
TIMEZONE="Etc/UTC"
build

DISTRIBUTION_TYPE="debian"
DISTRIBUTION="buster"
DISTRIBUTION_ARCH="amd64"
DESKTOP_ENVIRONMENT="flux"
PACKAGE_VARIANT="minimal"
INITRD_TYPE="livekit"
KERNEL_TYPE="default"
KERNEL_BPO="false"
KERNEL_AUFS="false"
COMP_TYPE="xz"
LOCALE="en_US"
TIMEZONE="Etc/UTC"
build

# stretch xfce
DISTRIBUTION_TYPE="debian"
DISTRIBUTION="stretch"
DISTRIBUTION_ARCH="amd64"
DESKTOP_ENVIRONMENT="xfce"
PACKAGE_VARIANT="standard"
INITRD_TYPE="livekit"
KERNEL_TYPE="default"
KERNEL_BPO="false"
KERNEL_AUFS="false"
COMP_TYPE="xz"
LOCALE="en_US"
TIMEZONE="Etc/UTC"
build

DISTRIBUTION_TYPE="debian"
DISTRIBUTION="stretch"
DISTRIBUTION_ARCH="i386"
DESKTOP_ENVIRONMENT="xfce"
PACKAGE_VARIANT="standard"
INITRD_TYPE="livekit"
KERNEL_TYPE="default"
KERNEL_BPO="false"
KERNEL_AUFS="false"
COMP_TYPE="xz"
LOCALE="en_US"
TIMEZONE="Etc/UTC"
build

DISTRIBUTION_TYPE="debian"
DISTRIBUTION="stretch"
DISTRIBUTION_ARCH="amd64"
DESKTOP_ENVIRONMENT="xfce"
PACKAGE_VARIANT="minimal"
INITRD_TYPE="livekit"
KERNEL_TYPE="default"
KERNEL_BPO="false"
KERNEL_AUFS="false"
COMP_TYPE="xz"
LOCALE="en_US"
TIMEZONE="Etc/UTC"
build

DISTRIBUTION_TYPE="debian"
DISTRIBUTION="stretch"
DISTRIBUTION_ARCH="i386"
DESKTOP_ENVIRONMENT="xfce"
PACKAGE_VARIANT="minimal"
INITRD_TYPE="livekit"
KERNEL_TYPE="default"
KERNEL_BPO="false"
KERNEL_AUFS="false"
COMP_TYPE="xz"
LOCALE="en_US"
TIMEZONE="Etc/UTC"
build
