#!/bin/bash

# Author: Marcos Tischer Vallim. <https://github.com/mvallim>
# Author: crims0n. <https://minios.dev>

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SET_E=""
SET_U=""

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
BUILD_DIR="${SCRIPT_DIR}/build"
ISO_DIR="${BUILD_DIR}/iso"
KERNEL_DIR="${BUILD_DIR}/kernel"
LOCALES_DIR="${BUILD_DIR}/locales"

. "${SCRIPT_DIR}/linux-live/minioslib" || exit 1
toggle_shell_options u
if [ -z ${BATCH} ]; then
    . "${SCRIPT_DIR}/linux-live/config" || exit 1
fi
toggle_shell_options u
. "${SCRIPT_DIR}/linux-live/kernelconfig" || exit 1

CMD=(setup_host build_bootstrap build_chroot build_live build_config build_modules build_iso remove_sources)

# =============   main  ================

INSTALL_DIR=""

common_variables ${SCRIPT_DIR}/linux-live/layoutcodes.csv

console_colors

allow_root_only

if [ -f /.dockerenv ] || [ "$container" = "podman" ]; then
    new_run
fi

# check number of args
if [[ $# == 0 || $# > 3 ]]; then help; fi

# loop through args
DASH_FLAG="false"
START_INDEX="0"
END_INDEX="${#CMD[*]}"
for ii in "$@"; do
    if [[ "${ii}" == "-" ]]; then
        DASH_FLAG="true"
        continue
    fi
    find_index "${ii}"
    if [[ $DASH_FLAG == "false" ]]; then
        START_INDEX="${INDEX}"
    else
        END_INDEX=$((${INDEX} + 1))
    fi
done
if [[ $DASH_FLAG == "false" ]]; then
    END_INDEX=$((${START_INDEX} + 1))
fi

# loop through the commands
for ((ii = "${START_INDEX}"; ii < "${END_INDEX}"; ii++)); do
    setup_install_dir
    "${CMD[ii]}"
done

echo -e "${BOLD}${LIGHTYELLOW}$0${ENDCOLOR} - ${LIGHTGREEN}Command completed successfully!${ENDCOLOR}"
