#!/bin/bash
# данный способ сборки неактуален, так как добавлены механизмы, автоматически включающие фильтр модулей при сборке модулей, не входящих в основу системы.
# this method of building is irrelevant, since mechanisms have been added that automatically turn on the module filter when building modules that are not included in the system base.
BUILD_RU="true"
BUILD_EN="false"
if [ $BUILD_RU = "true" ]; then
    sed -i -e '/LOCALE=/s/=.*/="ru_RU"/' linux-live/buildconfig
    sed -i -e '/DESKTOP_ENVIRONMENT=/s/=.*/="xfce-frugal-base"/' linux-live/buildconfig
    sed -i -e '/FILTER_MODULES=/s/=.*/="false"/' linux-live/buildconfig
    minios-install - build_modules
    sed -i -e '/DESKTOP_ENVIRONMENT=/s/=.*/="xfce-frugal"/' linux-live/buildconfig
    sed -i -e '/FILTER_MODULES=/s/=.*/="true"/' linux-live/buildconfig
    sed -i -e '/FILTER_LEVEL=/s/=.*/="3"/' linux-live/buildconfig
    minios-install build_modules - && mv /build/minios-live/build/iso/minios-*.iso /build/850pro/
fi
if [ $BUILD_EN = "true" ]; then
    sed -i -e '/LOCALE=/s/=.*/="en_US"/' linux-live/buildconfig
    sed -i -e '/DESKTOP_ENVIRONMENT=/s/=.*/="xfce-frugal-base"/' linux-live/buildconfig
    sed -i -e '/FILTER_MODULES=/s/=.*/="false"/' linux-live/buildconfig
    minios-install - build_modules
    sed -i -e '/DESKTOP_ENVIRONMENT=/s/=.*/="xfce-frugal"/' linux-live/buildconfig
    sed -i -e '/FILTER_MODULES=/s/=.*/="true"/' linux-live/buildconfig
    sed -i -e '/FILTER_LEVEL=/s/=.*/="3"/' linux-live/buildconfig
    minios-install build_modules - && mv /build/minios-live/build/iso/minios-*.iso /build/850pro/
fi
