#!/bin/bash
# Note: MLC - minimumiOS Live Container

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

. $SCRIPT_DIR/linux-live/minioslib || exit 1

: 'container_build_run bullseye core standard amd64 xz
container_build_run bullseye core standard i386 xz
container_build_run bullseye core minimum amd64 xz
container_build_run bullseye core minimum i386 xz
container_build_run buster core standard amd64 xz
container_build_run buster core standard i386 xz
container_build_run buster core minimum amd64 xz
container_build_run buster core minimum i386 xz
container_build_run stretch core standard amd64 xz
container_build_run stretch core standard i386 xz
container_build_run stretch core minimum amd64 xz
container_build_run stretch core minimum i386 xz
container_build_run focal core standard amd64 xz
container_build_run focal core minimum amd64 xz
container_build_run kali-rolling core standard amd64 xz
container_build_run kali-rolling core standard i386 xz
container_build_run kali-rolling core minimum amd64 xz
container_build_run kali-rolling core minimum i386 xz'
container_build_run bullseye xfce maximum amd64 xz
#container_build_run bullseye xfce maximum i386 xz
container_build_run bullseye xfce standard amd64 xz
#container_build_run bullseye xfce standard i386 xz
#container_build_run bullseye xfce minimum amd64 xz
container_build_run bullseye xfce minimum i386 xz
container_build_run buster xfce maximum amd64 xz
#container_build_run buster xfce maximum i386 xz
container_build_run buster xfce standard amd64 xz
#container_build_run buster xfce standard i386 xz
#container_build_run buster xfce minimum amd64 xz
container_build_run buster xfce minimum i386 xz
#container_build_run buster slax minimum amd64 xz
#container_build_run buster slax minimum i386 xz
: 'container_build_run stretch xfce maximum amd64 xz
container_build_run stretch xfce maximum i386 xz
container_build_run stretch xfce standard amd64 xz
container_build_run stretch xfce standard i386 xz
container_build_run stretch xfce minimum amd64 xz
container_build_run stretch xfce minimum i386 xz
container_build_run stretch slax minimum amd64 xz
container_build_run stretch slax minimum i386 xz
container_build_run focal xfce maximum amd64 xz
container_build_run focal xfce standard amd64 xz
container_build_run focal xfce minimum amd64 xz
container_build_run kali-rolling xfce maximum amd64 xz
container_build_run kali-rolling xfce maximum i386 xz
container_build_run kali-rolling xfce standard amd64 xz
container_build_run kali-rolling xfce standard i386 xz
container_build_run kali-rolling xfce minimum amd64 xz
container_build_run kali-rolling xfce minimum i386 xz
container_build_run bookworm xfce maximum amd64 xz
container_build_run bookworm xfce maximum i386 xz
container_build_run bookworm xfce standard amd64 xz
container_build_run bookworm xfce standard i386 xz
container_build_run bookworm xfce minimum amd64 xz
container_build_run bookworm xfce minimum i386 xz'
