#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

pkg update
pkg install software-properties-common
add-apt-repository -y ppa:ubuntudde-dev/stable
pkg update

echo "nodm nodm/enabled boolean true" | debconf-set-selections
echo "samba-common samba-common/dhcp boolean false" | debconf-set-selections

if [ "$PACKAGE_VARIANT" != "puzzle" ]; then
    if [ -f $SCRIPT_DIR/package.list ]; then
        if grep -q slim $SCRIPT_DIR/package.list; then
            pkg install yad adwaita-icon-theme-fake
        elif grep -q adwaita-icon-theme-fake $SCRIPT_DIR/package.list; then
            pkg install yad
        else
            pkg install yad adwaita-icon-theme-antix
        fi
    fi

    if [ -f /usr/share/applications/yad-icon-browser.desktop ]; then
        rm -f /usr/share/applications/yad-icon-browser.desktop
    fi
fi

# install packages
if [ -f $SCRIPT_DIR/package.list ]; then
    install_packages -l $SCRIPT_DIR/package.list
fi

if grep -q slim $SCRIPT_DIR/package.list && ! grep -q "#slim" $SCRIPT_DIR/package.list; then
    sed -i 's,xserver_arguments   -nolisten tcp,xserver_arguments   -nolisten tcp vt07,g' /etc/slim.conf
    sed -i 's,# hidecursor          false,hidecursor            false,g' /etc/slim.conf
    sed -i 's,screenshot_cmd      scrot /root/slim.png,# screenshot_cmd      scrot /root/slim.png,g' /etc/slim.conf
    sed -i 's,#auto_login          no,auto_login          yes,g' /etc/slim.conf
    sed -i 's,current_theme       debian-softwaves,current_theme       minios,g' /etc/slim.conf
    sed -i "s/#default_user        simone/default_user        $USER_NAME/g" /etc/slim.conf
fi
