#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# install packages
if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
    apt-get update &&
        apt-get install -y \
            $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | tr "\n" " ") >>$OUTPUT 2>&1
fi

if [ $PACKAGE_VARIANT = "standard" ]; then
    if [ $DISTRIBUTION = "stretch" ]; then
        echo 'deb http://ftp.debian.org/debian stretch-backports main' | sudo tee --append /etc/apt/sources.list.d/stretch-backports.list >>$OUTPUT 2>&1
        apt-get update &&
            apt-get install -t stretch-backports -y \
                remmina remmina-plugin-rdp remmina-plugin-vnc >>$OUTPUT 2>&1
    else
        apt-get update &&
            apt-get install -y \
                remmina remmina-plugin-rdp remmina-plugin-vnc >>$OUTPUT 2>&1

    fi
fi

if [ $PACKAGE_VARIANT = "minimum" ]; then
    sed -i 's,create=xarchiver --add-to,create=xarchiver --compress,g' /usr/share/libfm/archivers.list
fi
