#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

cd $SCRIPT_DIR
wget -c https://cdimage.ch2.minios.ru/cap/cts-4.0.0-104.ks1_$DISTRIBUTION_ARCH.deb >>$OUTPUT 2>&1
# install packages
$APT_CMD update >>$OUTPUT 2>&1 &&
    apt-get install -y $SCRIPT_DIR/cts-4.0.0-104.ks1_$DISTRIBUTION_ARCH.deb libnss3-tools iptables >>$OUTPUT 2>&1
rm -f $SCRIPT_DIR/cts-4.0.0-104.ks1_$DISTRIBUTION_ARCH.deb >>$OUTPUT 2>&1

rm -f /etc/cts/.csum
rm -f /etc/cts/filelist.current
touch /etc/cts/filelist.current
/usr/share/cts/bin/ctsic compute >>$OUTPUT 2>&1
