#!/bin/bash
# Author: crims0n. <https://minios.dev>
# Author: Patrick Verner and Jason Vasquez

exec 19>/var/log/minios/minios-script-launcher.log
BASH_XTRACEFD=19
set -x

YELLOW="\e[33m"
CYAN="\e[36m"
ENDCOLOR="\e[0m"
FROM=$(cat /run/initramfs/var/log/from.log)
MEDIA="/run/initramfs/memory/data/$FROM"
FX=""

# Function to print a header before executing user scripts
script_header() {
    if [ -z "$FX" ]; then
        echo -e "${CYAN}Executing user scripts... ${YELLOW}\n"
        FX=FX
    fi
}

# Function to list and execute scripts in a given directory
_script_list() {
    for SCRIPT in $(ls $1/scripts/* 2>/dev/null); do
        script_header
        echo ">>> $SCRIPT"
        if [ -x "$SCRIPT"; then
            "$SCRIPT"
        else
            read FIRST_LINE <"$SCRIPT" &>/dev/null
            INTERPRETER=${FIRST_LINE###!}
            echo "$INTERPRETER"
            [ ".$INTERPRETER" != ".$FIRST_LINE" ] && INTERPRETER=${INTERPRETER%% } || INTERPRETER=
            [ -n "$INTERPRETER" ] && "$INTERPRETER" "$SCRIPT" || /bin/sh "$SCRIPT"
        fi
        [ -n "$2" ] && rm -f "$SCRIPT"
    done
}

script_list() { _script_list "$1" "$2"; }

if ls "$MEDIA/scripts/"* 2>/dev/null; then
    script_list "$MEDIA"
    [ -n "$FX" ] && echo -e "${ENDCOLOR}"
fi
