#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

wget -c https://github.com/VSCodium/vscodium/releases/download/1.57.1/codium_1.57.1-1623975230_amd64.deb &&
    $APT_CMD install $APT_OPTIONS ./codium_1.57.1-1623975230_amd64.deb &&
    rm -f ./codium_1.57.1-1623975230_amd64.deb
