#!/bin/bash
# This is a config file for MiniOS-Live build script and Linux Live Kit boot script.
# You shouldn't need to change anything expect PACKAGE_VARIANT OUTPUT COMP_TYPE

LIVEKITNAME="minios"

SYSTEMNAME="MiniOS"

DISTRIBUTION_TYPE="debian"

DISTRIBUTION="bullseye"

DISTRIBUTION_ARCH="amd64"

PACKAGE_VARIANT="standard"

LIVE_TYPE="livekit"

# default is output to log. you can use OUTPUT="/dev/stdout" if you want to route events to standard output.
OUTPUT="/dev/stdout"
#OUTPUT="/dev/null"

DEBIAN_FRONTEND_TYPE="noninteractive"

APT_CMD="apt-get"

APT_OPTIONS="-y"

UNION_BUILD_TYPE="overlayfs"

BEXT="sb"

# Compression method used for the system and modules.
COMP_TYPE="xz"