#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

language_to_array

pkg update

# install packages
if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
    install_packages
fi
if [ $PACKAGE_VARIANT = "standard" ] || [ $PACKAGE_VARIANT = "maximum" ] || [ $PACKAGE_VARIANT = "ultra" ]; then
    if [ $DISTRIBUTION = "stretch" ]; then
        pkg install \
            remmina/$DISTRIBUTION-backports remmina-plugin-rdp/$DISTRIBUTION-backports remmina-plugin-vnc/$DISTRIBUTION-backports libssh-4/$DISTRIBUTION-backports
    elif [ $DISTRIBUTION = "buster" ] || [ $DISTRIBUTION = "bullseye" ]; then
        pkg install \
            remmina/$DISTRIBUTION-backports remmina-plugin-rdp/$DISTRIBUTION-backports remmina-plugin-vnc/$DISTRIBUTION-backports
    else
        pkg install \
            remmina remmina-plugin-rdp remmina-plugin-vnc
    fi
fi

if [ -f /usr/share/applications/yad-icon-browser.desktop ]; then
    rm -f /usr/share/applications/yad-icon-browser.desktop
fi

if grep -q "imagemagick" $SCRIPT_DIR/$PACKAGE_VARIANT.list >/dev/null 2>&1; then
    rm -f /usr/share/applications/display-im6.q16.desktop
fi

if grep -q "vlc" $SCRIPT_DIR/$PACKAGE_VARIANT.list >/dev/null 2>&1; then
    if [ $LOCALE != "en_US" ]; then
        pkg install vlc-l10n
    fi
fi
if grep -q "xfce4-clipman" $SCRIPT_DIR/$PACKAGE_VARIANT.list >/dev/null 2>&1; then
    sed -i "15i Name[ru]=Настройки менеджера буфера обмена" /usr/share/applications/xfce4-clipman-settings.desktop &&
        sed -i "29i Comment[ru]=Настройте свой буфер обмена" /usr/share/applications/xfce4-clipman-settings.desktop
fi
if [ $LOCALE != "en_US" ]; then
    sed -i "s/doublecmd.en.po/doublecmd.${LNG[0]}.po/g" /etc/skel/.config/doublecmd/doublecmd.xml
fi
if grep -q "gnumeric" $SCRIPT_DIR/$PACKAGE_VARIANT.list >/dev/null 2>&1; then
    sed -i "s/Science;//g" /usr/share/applications/gnumeric.desktop
fi

if grep -q "xfce4-terminal" $SCRIPT_DIR/$PACKAGE_VARIANT.list >/dev/null 2>&1; then
    cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=

EOF
else
    cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=Thunar
WebBrowser=

EOF
fi

sed -i -e "/FontName=/s/=.*/=JetBrains Mono Light 10/" /etc/skel/.config/xfce4/terminal/terminalrc

if [ $DISTRIBUTION = "stretch" ] || [ $DISTRIBUTION = "buster" ] || [ $DISTRIBUTION = "orel" ]; then
    sed -i -e "/FontUseSystem=/s/=.*/=FALSE/" /etc/skel/.config/xfce4/terminal/terminalrc
fi
