#!/bin/bash

if [ $PACKAGE_VARIANT = "minimum" ]; then
    sed -i 's,create=xarchiver --add-to,create=xarchiver --compress,g' /usr/share/libfm/archivers.list
elif [ $PACKAGE_VARIANT = "standard" ] || [ $PACKAGE_VARIANT = "toolbox" ]; then
    update-alternatives --set x-terminal-emulator /usr/bin/xfce4-terminal.wrapper
elif [ $PACKAGE_VARIANT = "novice" ]; then
    mkdir -p /var/cache/swcatalog/cache
fi

