#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

function language_to_array() {
  local IFS
  IFS="_"
  LANG=($LOCALE)
}
language_to_array

apt-get update >>$OUTPUT 2>&1

if [ $LOCALE != "en_US" ]; then
  if [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
    apt-get install -y language-pack-gnome-$LANG-base >>$OUTPUT
  fi
fi

echo "nodm nodm/enabled boolean true" | debconf-set-selections
echo "samba-common samba-common/dhcp boolean false" | debconf-set-selections

# install packages
if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
  DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
    $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | sed "/wicd/d" | tr "\n" " ") librsvg2-common network-manager-gnome >>$OUTPUT 2>&1
fi
