#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

$APT_CMD update >>$OUTPUT 2>&1 &&
    $APT_CMD install $APT_OPTIONS gnupg >>$OUTPUT 2>&1

wget -qO- https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor >packages.google.gpg
install -o root -g root -m 644 packages.google.gpg /etc/apt/trusted.gpg.d/
rm -f packages.google.gpg
#apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 78BD65473CB3BD13
sh -c 'echo "deb [arch=amd64,i386,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.google.gpg] http://dl.google.com/linux/chrome/deb/ stable main" >/etc/apt/sources.list.d/google-chrome.list'

# install packages
$APT_CMD update >>$OUTPUT 2>&1 &&
    $APT_CMD install $APT_OPTIONS google-chrome-stable >>$OUTPUT 2>&1

if [ ! -d /etc/chrome.d/ ]; then
    mkdir /etc/chrome.d
fi
echo 'export CHROME_FLAGS="$CHROME_FLAGS --disk-cache-dir=/dev/null --disk-cache-size=1"' >>/etc/chrome.d/default-flags

if [[ $DESKTOP_ENVIRONMENT == *"xfce"* ]]; then
    if [ $PACKAGE_VARIANT = "minimum" ]; then
        cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=pcmanfm
WebBrowser=google-chrome

EOF
    elif [ $PACKAGE_VARIANT = "standard" ] || [ $PACKAGE_VARIANT = "maximum" ]; then
        cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=google-chrome

EOF
    fi
fi

if [ -f /usr/bin/fbliveapp ]; then
    FBLIVEAPP="google-chrome"
    FBLIVEAPPNAME="Google Chrome"
    FBLIVEAPPEXECUTABLE="google-chrome-stable"
    MODULENUMBER="5"

    cat <<EOF >/usr/bin/fblive-add-$FBLIVEAPP.sh
#!/bin/bash
if [ -f /var/cache/fblive-add-$FBLIVEAPP.addon ]; then
    if ! grep $FBLIVEAPPEXECUTABLE /usr/bin/fbliveapp >/dev/null; then
        cp /usr/bin/fbliveapp /usr/bin/fbliveapp.$FBLIVEAPP.bak
        sed -i "/shift/ e cat /var/cache/fblive-add-$FBLIVEAPP.addon" /usr/bin/fbliveapp
        #rm /var/cache/fblive-add-$FBLIVEAPP.addon
        rm /usr/share/applications/$FBLIVEAPP.desktop
    fi
fi

EOF
    chmod +x /usr/bin/fblive-add-$FBLIVEAPP.sh
    cat <<EOF >/usr/lib/systemd/system/fblive-add-$FBLIVEAPP.service
[Unit]
Description=Adding $FBLIVEAPPNAME to fbliveapp
#After=network.target

[Service]
Type=oneshot
ExecStart=/usr/bin/fblive-add-$FBLIVEAPP.sh
RemainAfterExit=true
ExecStop=
StandardOutput=journal

[Install]
WantedBy=multi-user.target

EOF
    cat <<EOF >/usr/share/applications/$MODULENUMBER$FBLIVEAPP.desktop
[Desktop Entry]
Version=1.0
Name=$FBLIVEAPPNAME
GenericName=$FBLIVEAPPNAME
Exec=fbliveapp $FBLIVEAPPEXECUTABLE %U
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=$FBLIVEAPP.png
Categories=Network;WebBrowser;
MimeType=audio/*;image/*;video/*;application/pdf;application/x-pdf;text/html;text/xml;application/xhtml_xml;application/x-mimearchive;x-scheme-handler/http;x-scheme-handler/https;
StartupWMClass=$FBLIVEAPP
StartupNotify=true

EOF
    cat <<EOF >/var/cache/fblive-add-$FBLIVEAPP.addon
if [ "\$1" = "$FBLIVEAPPEXECUTABLE" ]; then
   NAME="$FBLIVEAPPNAME"
   EXECUTABLE="/usr/bin/$FBLIVEAPPEXECUTABLE"
   GUEST=true
fi

EOF
systemctl enable fblive-add-$FBLIVEAPP.service >>$OUTPUT 2>&1
fi
