#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

wget -qO- https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor >packages.google.gpg
install -o root -g root -m 644 packages.google.gpg /etc/apt/trusted.gpg.d/
rm -f packages.google.gpg
#apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 78BD65473CB3BD13
sh -c 'echo "deb [arch=amd64,i386,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.google.gpg] http://dl.google.com/linux/chrome/deb/ stable main" >/etc/apt/sources.list.d/google-chrome.list'

# install packages
$APT_CMD update >>$OUTPUT 2>&1 &&
    $APT_CMD install $APT_OPTIONS google-chrome-stable >>$OUTPUT 2>&1

if [ ! -d /etc/chrome.d/ ]; then
    mkdir /etc/chrome.d
fi
echo 'export CHROME_FLAGS="$CHROME_FLAGS --disk-cache-dir=/dev/null --disk-cache-size=1"' >>/etc/chrome.d/default-flags

if [[ $DESKTOP_ENVIRONMENT == *"xfce"* ]]; then
    if [ $PACKAGE_VARIANT = "minimal" ]; then
        cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=pcmanfm
WebBrowser=google-chrome

EOF
    elif [ $PACKAGE_VARIANT = "std" ]; then
        cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=google-chrome

EOF
    fi
fi
