#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

wget https://inkscape.org/gallery/item/33450/Inkscape-dc2aeda-x86_64.AppImage
mkdir -p /opt/appimage
mv ./Inkscape-dc2aeda-x86_64.AppImage /opt/appimage
chmod +x /opt/appimage/Inkscape-dc2aeda-x86_64.AppImage
wget https://gitlab.com/inkscape/inkscape/-/raw/master/share/icons/application/scalable/org.inkscape.Inkscape.svg
mkdir -p /usr/share/icons/hicolor/scalable/apps
mv ./org.inkscape.Inkscape.svg  /usr/share/icons/hicolor/scalable/apps/

#PACKAGE=$APP_EXECUTABLE
#echo "PACKAGE=$PACKAGE" >/.package
#echo "VERSION=$(dpkg -s $PACKAGE | grep Version | egrep -o '[0-9].*-[0-9]')" >>/.package
