#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

wget -q http://drbl.sourceforge.net/GPG-KEY-DRBL -O- | apt-key add -
echo "deb http://drbl.sourceforge.net/drbl-core drbl stable" >/etc/apt/sources.list.d/drbl.list

# install packages
if [ -f $SCRIPT_DIR/package.list ]; then
    #sudo DEBIAN_FRONTEND=$DEBIAN_FRONTEND_TYPE \
    apt-get update >>$OUTPUT 2>&1 &&
        #sudo DEBIAN_FRONTEND=$DEBIAN_FRONTEND_TYPE \
        apt-get install -y $APT_OPTIONS2 \
            $(grep -vE "^\s*#" $SCRIPT_DIR/package.list | tr "\n" " ") >>$OUTPUT 2>&1
fi

drbl4imp -b