#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

apt-get update >>$OUTPUT 2>&1 &&
    apt-get install -y \
        software-properties-common >>$OUTPUT 2>&1

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5
add-apt-repository 'deb https://download.onlyoffice.com/repo/debian squeeze main'

# install packages
apt-get update >>$OUTPUT 2>&1 &&
    apt-get install -y \
        libpulse0 libnss3 onlyoffice-desktopeditors >>$OUTPUT 2>&1
