#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# install packages
$APT_CMD update >>$OUTPUT 2>&1 &&
    apt-get install -y \
        ttf-mscorefonts-installer >>$OUTPUT 2>&1
