#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

cd $SCRIPT_DIR
wget -c https://download.anydesk.com/linux/anydesk_6.1.1-1_$DISTRIBUTION_ARCH.deb >>$OUTPUT 2>&1
# install packages
$APT_CMD update >>$OUTPUT 2>&1 &&
    $APT_CMD install $APT_OPTIONS $SCRIPT_DIR/anydesk_6.1.1-1_$DISTRIBUTION_ARCH.deb gtk2-engines-pixbuf >>$OUTPUT 2>&1
rm -f $SCRIPT_DIR/anydesk_6.1.1-1_$DISTRIBUTION_ARCH.deb >>$OUTPUT 2>&1

systemctl disable anydesk