#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor >packages.sublimehq-pub.gpg
install -o root -g root -m 644 packages.sublimehq-pub.gpg /etc/apt/trusted.gpg.d/
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
rm -f packages.sublimehq-pub.gpg

# install packages
pkg update
pkg install sublime-text

PACKAGE="sublime-text"
echo "PACKAGE=$PACKAGE" >/.package
echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g' | sed 's/:/-/g')" >>/.package
