#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

#apt-get update >>$OUTPUT 2>&1 &&
#    apt-get install -y gnupg >>$OUTPUT 2>&1

wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor >packages.sublimehq-pub.gpg
install -o root -g root -m 644 packages.sublimehq-pub.gpg /etc/apt/trusted.gpg.d/
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
rm -f packages.sublimehq-pub.gpg

#apt-get update >>$OUTPUT 2>&1 &&
#    apt-get install -y apt-transport-https >>$OUTPUT 2>&1

# install packages
apt-get update >>$OUTPUT 2>&1 &&
    apt-get install -y sublime-text >>$OUTPUT 2>&1

PACKAGE="sublime-text"
echo "PACKAGE=$PACKAGE" >/.package
echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g' | sed 's/:/-/g')" >>/.package