#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

echo "firmware-ipw2x00 firmware-ipw2x00/license/accepted boolean true" | debconf-set-selections
echo "b43-fwcutter b43-fwcutter/install-unconditional boolean true" | debconf-set-selections

# install packages
if [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
    #sudo DEBIAN_FRONTEND=$DEBIAN_FRONTEND_TYPE \
    $APT_CMD install $APT_OPTIONS \
        linux-firmware firmware-b43-installer firmware-ath9k-htc >>$OUTPUT 2>&1
else
    if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
        #sudo DEBIAN_FRONTEND=$DEBIAN_FRONTEND_TYPE \
        $APT_CMD install $APT_OPTIONS \
            $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | tr "\n" " ") >>$OUTPUT 2>&1
    fi
fi
