#!/bin/sh
# /etc/live/config/0030-user-setup

. /usr/lib/live/config.sh
. /etc/os-release

## live-config(7) - System Configuration Components
## Copyright (C) 2016-2020 The Debian Live team
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

#set -e

Init() {
    # Checking if package is installed or already configured
    if component_was_executed "issue-setup"; then
        exit 0
    fi

    echo -n " issue-setup"
}

Config() {
    # Base banner
    cat <<EOF >/etc/issue


                                                                          \\l





                        Thank you for using MiniOS.
EOF

    # Append distribution info
    case "$ID" in
    debian)
        DIST="Based on [1;31mDebian GNU/Linux[0;29m."
        ;;
    ubuntu)
        DIST="Based on [1;38;5;214mUbuntu[0;29m."
        ;;
    kali)
        DIST="Based on [1;36mKali Linux[0;29m."
        ;;
    *)
        DIST=""
        ;;
    esac

    [ -n "$DIST" ] && printf "                        %s\n" "$DIST" >>"/etc/issue"

    # Append Slax info if installed
    if dpkg -l fluxbox-slax >/dev/null 2>&1; then
        printf "                        Powered by [1;32mSlax[0;29m.\n" >>"/etc/issue"
    fi

    # Append ASCII art
    cat >>"/etc/issue" <<'EOF'

    [1;1m::::    ::::  ::::::::::: ::::    ::: ::::::::::: ::::::::   ::::::::  [0;29m
    [1;1m+:+:+: :+:+:+     :+:     :+:+:   :+:     :+:    :+:    :+: :+:    :+: [0;29m
    [1;1m+:+ +:+:+ +:+     +:+     :+:+:+  +:+     +:+    +:+    +:+ +:+        [0;29m
    [1;1m+#+  +:+  +#+     +#+     +#+ +:+ +#+     +#+    +#+    +:+ +#++:++#++ [0;29m
    [1;1m+#+       +#+     +#+     +#+  +#+#+#     +#+    +#+    +#+        +#+ [0;29m
    [1;1m#+#       #+#     #+#     #+#   #+#+#     #+#    #+#    #+# #+#    #+# [0;29m
    [1;1m###       ### ########### ###    #### ########### ########   ########  [0;29m

EOF

    # Creating state file
    touch /var/lib/live/config/user-setup
}

Init
Config
