#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

language_to_array

pkg update

# install packages
#!!!the name of the main application of the module must be specified in the first line of package.list!!!
if [ -f $SCRIPT_DIR/package.list ]; then
    if [ $DISTRIBUTION = "bullseye" ]; then
        install_packages -t $DISTRIBUTION-backports -l $SCRIPT_DIR/package.list
    else
        install_packages -l $SCRIPT_DIR/package.list
    fi
    PACKAGE=$(head -n 1 $SCRIPT_DIR/package.list)
    echo "PACKAGE=$PACKAGE" >/.package
    echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g' | sed 's/:/-/g')" >>/.package
fi

if [ $LOCALE != "en_US" ]; then
    sed -i "s/doublecmd.en.po/doublecmd.${LNG[0]}.po/g" /etc/skel/.config/doublecmd/doublecmd.xml
fi
