#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1
. /minios-build.conf || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

pkg update

if [ -f $SCRIPT_DIR/package.list ]; then
    install_packages --package-list "$SCRIPT_DIR/package.list"
    PACKAGE=$(head -n 1 $SCRIPT_DIR/package.list)
    echo "PACKAGE=$PACKAGE" >/.package
    echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g' | sed 's/:/-/g')" >>/.package

    INSTALL_LOCALES=("${!LOCALES[@]}")
    [[ "${MULTILINGUAL}" = "false" ]] && INSTALL_LOCALES=("${LOCALE}")

    for locale in "${INSTALL_LOCALES[@]}"; do
        [[ "${locale}" = "en_US" ]] && continue

        if [[ ! -v LOCALES[${locale}] ]]; then
            echo "Locale ${locale} is not supported, skipping."
            continue
        fi

        oldIFS=$IFS
        IFS=',' read -ra LOCALE_VALUES <<<"${LOCALES[${locale}]}"
        IFS=$oldIFS

        LIBREOFFICE_LOCALE=${LOCALE_VALUES[4]:-${LOCALE_VALUES[0]}}

        if [ -n "${LIBREOFFICE_LOCALE}" ]; then
            pkg install "libreoffice-l10n-${LIBREOFFICE_LOCALE}"
        else
            echo "No package available for locale ${locale}, skipping."
        fi
    done
fi
