#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

echo "zfs-dkms        zfs-dkms/note-incompatible-licenses     note" | debconf-set-selections -v >>$OUTPUT 2>&1

if [ KERNEL_TYPE != "aufs" ]; then
    if [ -f /usr/bin/dpkg-query ] 2>/dev/null; then
        KERNEL=$(dpkg-query -W -f='${binary:Package}\n' linux-image-* | head -n 1 | sed 's/linux-image-//')
    else
        KERNEL=$(uname -r)
    fi
    echo "KERNEL=$KERNEL" >/livekit.conf

    if [ $DISTRIBUTION = "stretch" ] || [ $DISTRIBUTION = "buster" ]; then
        apt-get update >>$OUTPUT 2>&1
        apt-get install -y linux-headers-$KERNEL_ARCH gcc make >>$OUTPUT 2>&1
        apt-get install -y aufs-dkms >>$OUTPUT 2>&1
    fi
    if ([ $PACKAGE_VARIANT = "maximum" ] || [ $PACKAGE_VARIANT = "ultra" ]) && [ $DISTRIBUTION_ARCH = "amd64" ]; then
        apt-get update >>$OUTPUT 2>&1
        apt-get install -y linux-headers-$KERNEL_ARCH gcc make >>$OUTPUT 2>&1
        apt-get install -y zfs-dkms >>$OUTPUT 2>&1
    fi
fi
