#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

function language_to_array() {
    local IFS
    IFS="_"
    LANG=($LOCALE)
}
language_to_array

apt-get update >>$OUTPUT 2>&1

# install packages
if [ -f $SCRIPT_DIR/package.list ]; then
    if [ $DISTRIBUTION = "bookworm" ] || [ $DISTRIBUTION = "sid" ]; then
        apt-get install -y \
            $(grep -vE "^\s*#" $SCRIPT_DIR/package.list | sed "s,/bullseye-backports,,g" | tr "\n" " ") >>$OUTPUT 2>&1
    else
        apt-get install -y \
            $(grep -vE "^\s*#" $SCRIPT_DIR/package.list | tr "\n" " ") >>$OUTPUT 2>&1
    fi
fi

if grep -q 'imagemagick' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    rm -f /usr/share/applications/display-im6.q16.desktop
fi
if grep -q 'obs-studio' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    mv /usr/share/icons/hicolor/256x256/apps/com.obsproject.Studio.png /usr/share/pixmaps/
    #convert /usr/share/icons/hicolor/256x256/apps/com.obsproject.Studio.png -resize 128x128 /usr/share/icons/hicolor/128x128/apps/com.obsproject.Studio.png
fi
if grep -q 'pdfmod' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    for FOLDER in $(ls /usr/share/icons/elementary-xfce/apps | grep -E '^[0-9]+$'); do
        cd /usr/share/icons/elementary-xfce/apps/$FOLDER
        ln -s pdfshuffler.png pdfmod.png
    done
fi
if grep -q 'guake' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    for FOLDER in $(ls /usr/share/icons/elementary-xfce/apps | grep -E '^[0-9]+$'); do
        cd /usr/share/icons/elementary-xfce/apps/$FOLDER
        ln -s utilities-terminal.png guake.png
    done
fi
if grep -q 'drawio' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    for FOLDER in $(ls /usr/share/icons/elementary-xfce/apps | grep -E '^[0-9]+$'); do
        cd /usr/share/icons/elementary-xfce/apps/$FOLDER
        ln -s libreoffice-draw.png drawio.png
    done
fi
update-icon-caches /usr/share/icons/*
