#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

apt-get update >>$OUTPUT 2>&1

# install packages
if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
    apt-get install -y \
        $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | tr "\n" " ") >>$OUTPUT 2>&1
fi

if [ $PACKAGE_VARIANT = "maximum" ]; then
    if [ $DISTRIBUTION = "stretch" ]; then
        echo 'deb http://ftp.debian.org/debian stretch-backports main' | sudo tee --append /etc/apt/sources.list.d/stretch-backports.list >>$OUTPUT 2>&1
        apt-get update >>$OUTPUT 2>&1
        apt-get install -t stretch-backports -y \
            remmina remmina-plugin-rdp remmina-plugin-vnc >>$OUTPUT 2>&1
    else
        apt-get install -y \
            remmina remmina-plugin-rdp remmina-plugin-vnc >>$OUTPUT 2>&1

    fi
fi

if [ $PACKAGE_VARIANT = "minimum" ]; then
    cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=pcmanfm
WebBrowser=firefox

EOF
elif [ $PACKAGE_VARIANT = "standard" ] || [ $PACKAGE_VARIANT = "maximum" ]; then
    cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=firefox

EOF
fi
