#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

curl https://minios-linux.github.io/debian/minios-linux.asc | gpg --dearmor >/etc/apt/trusted.gpg.d/minios-linux.gpg
if [ $DISTRIBUTION = "kali-rolling" ]; then
    echo "deb https://minios-linux.github.io/debian/ bookworm main contrib non-free" >/etc/apt/sources.list.d/minios-linux.list
elif [ $DISTRIBUTION = "stretch" ] || [ $DISTRIBUTION = "buster" ] || [ $DISTRIBUTION = "bullseye" ]; then
    echo "deb https://minios-linux.github.io/debian/ $DISTRIBUTION main contrib non-free
deb https://minios-linux.github.io/debian/ $DISTRIBUTION-backports main contrib non-free" >/etc/apt/sources.list.d/minios-linux.list
else
    echo "deb https://minios-linux.github.io/debian/ $DISTRIBUTION main contrib non-free" >/etc/apt/sources.list.d/minios-linux.list
fi
cat <<EOF >/etc/apt/preferences.d/minios-linux
Package: *
Pin: release l=MiniOS Repository
Pin-Priority: 1001
EOF

cat <<EOF >/usr/lib/systemd/system/minios-shutdown.service
[Unit]
Description=MiniOS config file update on shutdown.

[Service]
Type=oneshot
RemainAfterExit=true
ExecStop=-/bin/sh -c "if [ -f /run/initramfs/memory/data/$LIVEKITNAME/$LIVEKITNAME.conf ]; then if [ /etc/$LIVEKITNAME/$LIVEKITNAME.conf -nt /run/initramfs/memory/data/$LIVEKITNAME/$LIVEKITNAME.conf ]; then cp -fp /etc/$LIVEKITNAME/$LIVEKITNAME.conf /run/initramfs/memory/data/$LIVEKITNAME/$LIVEKITNAME.conf; fi; fi"

[Install]
WantedBy=multi-user.target
EOF

systemctl enable minios-startup.service
systemctl enable minios-shutdown.service
systemctl enable minios-script-launcher.service

if [ $PACKAGE_VARIANT = "cloud" ] || [[ $DESKTOP_ENVIRONMENT == *"slax"* ]]; then
    if [ -d /usr/share/minios/html ]; then
        rm -rf /usr/share/minios/html
    fi
fi
