#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

cat <<EOF >/usr/lib/systemd/system/minios-shutdown.service
[Unit]
Description=MiniOS config file update on shutdown.

[Service]
Type=oneshot
RemainAfterExit=true
ExecStop=-/bin/sh -c "if [ -f /run/initramfs/memory/data/$LIVEKITNAME/$LIVEKITNAME.conf ]; then if [ /etc/$LIVEKITNAME/$LIVEKITNAME.conf -nt /run/initramfs/memory/data/$LIVEKITNAME/$LIVEKITNAME.conf ]; then cp -fp /etc/$LIVEKITNAME/$LIVEKITNAME.conf /run/initramfs/memory/data/$LIVEKITNAME/$LIVEKITNAME.conf; fi; fi"

[Install]
WantedBy=multi-user.target
EOF

systemctl enable minios-startup.service
systemctl enable minios-shutdown.service
systemctl enable minios-script-launcher.service
