#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

echo "nodm nodm/enabled boolean true" | debconf-set-selections
echo "samba-common samba-common/dhcp boolean false" | debconf-set-selections

# install packages
if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
  #sudo DEBIAN_FRONTEND=$DEBIAN_FRONTEND_TYPE \
  $APT_CMD update >>$OUTPUT 2>&1 &&
    #sudo DEBIAN_FRONTEND=$DEBIAN_FRONTEND_TYPE \
    $APT_CMD install $APT_OPTIONS $APT_OPTIONS2 \
      $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | tr "\n" " ") >>$OUTPUT 2>&1
fi

if grep slim $SCRIPT_DIR/$PACKAGE_VARIANT.list >>$OUTPUT 2>&1; then
    sed -i 's,# hidecursor          false,hidecursor            false,g' /etc/slim.conf
    sed -i 's,screenshot_cmd      scrot /root/slim.png,# screenshot_cmd      scrot /root/slim.png,g' /etc/slim.conf
    if [ $PACKAGE_VARIANT = "minimal" ]; then
        sed -i 's,#default_user        simone,default_user        root,g' /etc/slim.conf
    else
        sed -i 's,#default_user        simone,default_user        live,g' /etc/slim.conf
    fi
    sed -i 's,#auto_login          no,auto_login          yes,g' /etc/slim.conf
    sed -i 's,current_theme       debian-softwaves,current_theme       minios,g' /etc/slim.conf
fi

# create user directories
for dir in Desktop Documents Downloads Music Pictures Public Templates Videos; do
    mkdir -p /home/live/$dir >>$OUTPUT 2>&1
    mkdir -p /root/$dir >>$OUTPUT 2>&1
    mkdir -p /etc/skel/$dir >>$OUTPUT 2>&1
done

update-alternatives --install /usr/share/images/desktop-base/desktop-background desktop-background /usr/share/backgrounds/MiniOS-wallpaper.svg 100

     cat <<EOF >>/usr/share/applications/htop.desktop
[Desktop Entry]
Type=Application
Version=1.0
Name=Htop
GenericName=Process Viewer
GenericName[ca]=Visualitzador de processos
GenericName[da]=Procesfremviser
GenericName[de]=Prozessanzeige
GenericName[en_GB]=Process Viewer
GenericName[es]=Visor de procesos
GenericName[fi]=Prosessikatselin
GenericName[fr]=Visualiseur de processus
GenericName[gl]=Visor de procesos
GenericName[it]=Visore dei processi
GenericName[ko]=프로세스 뷰어
GenericName[nb]=Prosessviser
GenericName[nl]=Viewer van processen
GenericName[nn]=Prosessvisar
GenericName[pl]=Przeglądarka procesów
GenericName[pt]=Visualizador de Processos
GenericName[pt_BR]=Visualizador de processos
GenericName[ru]=Монитор процессов
GenericName[sk]=Prehliadač procesov
GenericName[sl]=Pregledovalnik opravil
GenericName[sr@ijekavian]=Приказивач процеса
GenericName[sr@ijekavianlatin]=Prikazivač procesa
GenericName[sr@latin]=Prikazivač procesa
GenericName[sr]=Приказивач процеса
GenericName[sv]=Processvisning
GenericName[tr]=Süreç Görüntüleyici
GenericName[uk]=Перегляд процесів
GenericName[zh_CN]=进程查看器
GenericName[zh_TW]=行程檢視器
Comment=Show System Processes
Comment[ca]=Visualitzeu els processos del sistema
Comment[da]=Vis systemprocesser
Comment[de]=Systemprozesse anzeigen
Comment[en_GB]=Show System Processes
Comment[es]=Mostrar procesos del sistema
Comment[fi]=Katsele järjestelmän prosesseja
Comment[fr]=Affiche les processus système
Comment[gl]=Mostrar os procesos do sistema.
Comment[it]=Mostra processi di sistema
Comment[ko]=시스템 프로세스 보기
Comment[nb]=Vis systemprosesser
Comment[nl]=Systeemprocessen tonen
Comment[nn]=Vis systemprosessar
Comment[pl]=Pokaż procesy systemowe
Comment[pt]=Mostrar os Processos do Sistema
Comment[pt_BR]=Mostra os processos do sistema
Comment[ru]=Просмотр списка процессов в системе
Comment[sk]=Zobraziť systémové procesy
Comment[sl]=Prikaz sistemskih opravil
Comment[sr@ijekavian]=Приказ системских процеса
Comment[sr@ijekavianlatin]=Prikaz sistemskih procesa
Comment[sr@latin]=Prikaz sistemskih procesa
Comment[sr]=Приказ системских процеса
Comment[sv]=Visa systemprocesser
Comment[tr]=Sistem Süreçlerini Göster
Comment[uk]=Перегляд системних процесів
Comment[zh_CN]=显示系统进程
Comment[zh_TW]=顯示系統行程
Icon=htop
Exec=htop
Terminal=true
Categories=System;Monitor;ConsoleOnly;
Keywords=system;process;task
EOF
    cat <<EOF >>/usr/share/applications/mc.desktop
[Desktop Entry]
Name=Midnight Commander
Name[af]=Middernag Kommandeur
Name[eo]=Meznokta komandanto
Name[fa]=فرمان‌دار نیمه شب
Name[ko]=미드나잇 커멘더
Name[lv]=Pusnakts Komandieris
Name[nso]=Molaedi wa Bosegogare
Name[th]=มิดไนท์คอมมานเดอร์
Name[ve]=Muhulwane wa vhukati ha vhusiku
Name[xh]=Umyaleli Waphakathi kobusuku
Name[zu]=Umyaleli waphakathi nobusuku
Comment=File manager
Comment[pl]=Menedżer plików
Exec=mc
Icon=file-manager.png
Terminal=true
Type=Application
Categories=ConsoleOnly;Utility;FileManager;System;FileTools;
Keywords=file manager;console;
EOF
    cat <<EOF >>/usr/share/applications/debian-xterm.desktop
[Desktop Entry]
Name=XTerm
#GenericName=Terminal
Comment=standard terminal emulator for the X window system
Exec=xterm
Terminal=false
Type=Application
#Encoding=UTF-8
Icon=Terminal
Categories=System;TerminalEmulator;
Keywords=shell;prompt;command;commandline;cmd;
X-Desktop-File-Install-Version=0.26
EOF
