#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

apt-get update >>$OUTPUT 2>&1

# install packages
if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
    apt-get install -y \
        $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | tr "\n" " ") >>$OUTPUT 2>&1
fi

if [ $PACKAGE_VARIANT = "maximum" ]; then
    if [ $DISTRIBUTION = "stretch" ]; then
        echo 'deb http://ftp.debian.org/debian stretch-backports main' | sudo tee --append /etc/apt/sources.list.d/stretch-backports.list >>$OUTPUT 2>&1
        apt-get update >>$OUTPUT 2>&1
        apt-get install -t stretch-backports -y \
            remmina remmina-plugin-rdp remmina-plugin-vnc >>$OUTPUT 2>&1
    else
        apt-get install -y \
            remmina remmina-plugin-rdp remmina-plugin-vnc >>$OUTPUT 2>&1

    fi

    sed -i 's,FontName=Monospace 10,FontName=JetBrains Mono Light 10,g' /etc/skel/.config/xfce4/terminal/terminalrc
fi

if grep -q 'galculator' $SCRIPT_DIR/$PACKAGE_VARIANT.list >/dev/null 2>&1; then
    for FOLDER in $(ls /usr/share/icons/elementary-xfce/apps | grep -E '^[0-9]+$'); do
        cd /usr/share/icons/elementary-xfce/apps/$FOLDER
        ln -s accessories-calculator.png galculator.png
    done
fi
if grep -q 'gsmartcontrol' $SCRIPT_DIR/$PACKAGE_VARIANT.list >/dev/null 2>&1; then
    for FOLDER in $(ls /usr/share/icons/elementary-xfce/apps | grep -E '^[0-9]+$'); do
        cd /usr/share/icons/elementary-xfce/apps/$FOLDER
        ln -s ../../devices/$FOLDER/drive-harddisk.png gsmartcontrol.png
    done
fi
if grep -q 'baobab' $SCRIPT_DIR/$PACKAGE_VARIANT.list >/dev/null 2>&1; then
    for FOLDER in $(ls /usr/share/icons/elementary-xfce/apps | grep -E '^[0-9]+$'); do
        cd /usr/share/icons/elementary-xfce/apps/$FOLDER
        ln -s baobab.png org.gnome.baobab.png
    done
fi
update-icon-caches /usr/share/icons/*

if [ $PACKAGE_VARIANT = "minimum" ]; then
    cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=pcmanfm
WebBrowser=firefox

EOF
elif [ $PACKAGE_VARIANT = "standard" ] || [ $PACKAGE_VARIANT = "maximum" ]; then
    cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=firefox

EOF
fi
