#!/bin/bash

if [ $PACKAGE_VARIANT = "minimum" ]; then
    sed -i 's,create=xarchiver --add-to,create=xarchiver --compress,g' /usr/share/libfm/archivers.list
fi

rm -Rf /usr/share/icons/hicolor/256x256 >>$OUTPUT 2>&1
rm -Rf /usr/share/icons/gnome/256x256 >>$OUTPUT 2>&1
rm -Rf /usr/share/icons/Adwaita/256x256 >>$OUTPUT 2>&1
rm -Rf /usr/share/icons/Adwaita/512x512 >>$OUTPUT 2>&1

if [ $PACKAGE_VARIANT = "standard" ]; then
    update-alternatives --set x-terminal-emulator /usr/bin/xfce4-terminal >>$OUTPUT 2>&1
fi
