#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

language_to_array

cat <<EOF >/etc/apt/sources.list.d//tde.list
deb http://mirror.ppa.trinitydesktop.org/trinity/deb/trinity-r14.0.x               $DISTRIBUTION main
deb http://mirror.ppa.trinitydesktop.org/trinity/deb/trinity-builddeps-r14.0.x     $DISTRIBUTION main
#deb-src http://mirror.ppa.trinitydesktop.org/trinity/deb/trinity-r14.0.x           $DISTRIBUTION main
#deb-src http://mirror.ppa.trinitydesktop.org/trinity/deb/trinity-builddeps-r14.0.x $DISTRIBUTION main
EOF

wget http://mirror.ppa.trinitydesktop.org/trinity/deb/trinity-keyring.deb
pkg install ./trinity-keyring.deb
rm ./trinity-keyring.deb

pkg update

pkg upgrade trinity-keyring

echo "nodm nodm/enabled boolean true" | debconf-set-selections
echo "samba-common samba-common/dhcp boolean false" | debconf-set-selections

# install packages
if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
    install_packages --delete-packages="wicd" --add-packages"librsvg2-common network-manager-gnome"
fi
