#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

function language_to_array() {
    local IFS
    IFS="_"
    LNG=($LOCALE)
}
language_to_array

apt-get $INSTALL_OPTIONS update >>$OUTPUT 2>&1

if [ $LOCALE != "en_US" ]; then
    if [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
        apt-get $INSTALL_OPTIONS install language-pack-gnome-$LNG-base >>$OUTPUT
    fi
fi

echo "nodm nodm/enabled boolean true" | debconf-set-selections
echo "samba-common samba-common/dhcp boolean false" | debconf-set-selections

# install packages
if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
    DEBIAN_FRONTEND=noninteractive \
        apt-get $INSTALL_OPTIONS install \
        $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list tr "\n" " ") >>$OUTPUT 2>&1
fi
