#!/bin/bash
#
# Сommand line parsing script.
# Author: crims0n. <http://minios.dev>
#

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

. /lib/minioslib

console_colors
allow_root_only

if [ ! -d /var/log/minios ]; then
    mkdir -p /var/log/minios
fi
exec 19>/var/log/minios/boot.log
BASH_XTRACEFD=19

set -x

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
CONFIG=/etc/minios/config
BUILDCONFIG=/etc/minios/buildconfig
if [ -f /cmdline ]; then
    CMDLINE=$(cat /cmdline)
    read_cmdline $CMDLINE
fi
if [ -f $CONFIG ]; then
    read_config $CONFIG LIVEKITNAME
else
    LIVEKITNAME="minios"
fi
MINIOSCONFIG=/etc/minios/$LIVEKITNAME.conf

if [ -z "$CLOUD" ]; then
    if [ -f $MINIOSCONFIG ]; then
        read_config $MINIOSCONFIG CLOUD
        if [ -z "$CLOUD" ]; then
            CLOUD="false"
        fi
    else
        CLOUD="false"
    fi
fi
if [ "$CLOUD" = "true" ]; then
    USER_NAME="root"
    DEFAULT_TARGET="multi-user"
    systemctl enable ssh
fi

if [ -z "$DEFAULT_TARGET" ]; then
    if [ -f $MINIOSCONFIG ]; then
        read_config $MINIOSCONFIG DEFAULT_TARGET
        if [ -z "$DEFAULT_TARGET" ]; then
            DEFAULT_TARGET="graphical"
        fi
    else
        DEFAULT_TARGET="graphical"
    fi
fi
if [ -n "$DEFAULT_TARGET" ]; then
    systemctl set-default $DEFAULT_TARGET
fi

if [ -z "$ENABLE_SERVICES" ]; then
    if [ "$SCRIPT_DIR" != "/usr/bin" ]; then
        if [ -f $MINIOSCONFIG ]; then
            read_config $MINIOSCONFIG ENABLE_SERVICES
        fi
    fi
fi
if [ -n "$ENABLE_SERVICES" ]; then
    SERVICES=$(echo $ENABLE_SERVICES | tr "," "\n")
    for SERVICE in $SERVICES; do
        if [ $SERVICE = "cockpit" ]; then
            systemctl enable cockpit.socket
        else
            systemctl enable $SERVICE
        fi
    done
fi

if [ -z "$DISABLE_SERVICES" ]; then
    if [ "$SCRIPT_DIR" != "/usr/bin" ]; then
        if [ -f $MINIOSCONFIG ]; then
            read_config $MINIOSCONFIG DISABLE_SERVICES
        fi
    fi
fi
if [ -n "$DISABLE_SERVICES" ]; then
    SERVICES=$(echo $DISABLE_SERVICES | tr "," "\n")
    for SERVICE in $SERVICES; do
        if [ $SERVICE = "cockpit" ]; then
            systemctl disable cockpit.socket
        else
            systemctl disable $SERVICE
        fi
    done
fi

if [ -z "$AUTOLOGIN" ]; then
    if [ -f $MINIOSCONFIG ]; then
        read_config $MINIOSCONFIG AUTOLOGIN
        if [ -z "$AUTOLOGIN" ]; then
            AUTOLOGIN="true"
        fi
    else
        AUTOLOGIN="true"
    fi
fi

if [ -z "$USER_NAME" ]; then
    if [ "$SCRIPT_DIR" != "/usr/bin" ]; then
        if [ -f $MINIOSCONFIG ]; then
            read_config $MINIOSCONFIG USER_NAME
        fi
    fi
fi

if [ $AUTOLOGIN = "true" ]; then
    if [ -f /usr/lib/systemd/system/xorg.service ]; then
        cat <<EOF >/usr/lib/systemd/system/xorg.service
[Unit]
Description=X-Window
ConditionKernelCommandLine=!text
After=systemd-user-sessions.service

[Service]
ExecStart=/bin/su --login -c "/usr/bin/startx -- :0 vt7 -ac -nolisten tcp" $USER_NAME

EOF
    fi
fi

if [ -f /usr/bin/x11vnc ]; then
    sed -i "s,-auth guess,-auth /home/$USER_NAME/.Xauthority,g" /usr/lib/systemd/system/x11vnc.service
fi

echo ""
echo "/etc/minios/$LIVEKITNAME.conf configuration file contents:"
cat /etc/minios/$LIVEKITNAME.conf
echo ""
