#!/bin/bash

. /usr/lib/minioslib
BUILDCONFIG=/etc/minios/buildconfig

if [ -f /usr/share/firefox-esr/browser/defaults/preferences/firefox-branding.js ]; then
    if ! grep -q minios /usr/share/firefox-esr/browser/defaults/preferences/firefox-branding.js; then
        sed -i "s,about:welcome,file:///usr/share/minios/html/index.html,g" /usr/share/firefox-esr/browser/defaults/preferences/firefox-branding.js
        read_config $BUILDCONFIG DESKTOP_ENVIRONMENT
        if [[ $DESKTOP_ENVIRONMENT == *"flux"* ]]; then
            cat <<'EOF' >>/usr/share/firefox-esr/browser/defaults/preferences/firefox-branding.js

pref("general.smoothScroll", false);
pref("browser.uidensity", 1);
pref("browser.newtabpage.activity-stream.feeds.topsites", false);
pref("browser.toolbars.bookmarks.visibility", "never");

EOF
        else
            cat <<'EOF' >>/usr/share/firefox-esr/browser/defaults/preferences/firefox-branding.js

pref("browser.tabs.drawInTitlebar", true);
pref("general.smoothScroll", false);
pref("browser.compactmode.show", true);
pref("browser.uidensity", 1);
pref("browser.tabs.inTitlebar", 1);
pref("browser.newtabpage.activity-stream.feeds.topsites", false);
pref("browser.toolbars.bookmarks.visibility", "never");

EOF
        fi
    fi
fi
