#!/bin/bash
#
# Сommand line parsing script.
# Author: crims0n. <http://minios.dev>
#

. /usr/lib/minioslib || exit 1

console_colors
allow_root_only

if [ ! -d /var/log/minios ]; then
    mkdir -p /var/log/minios
fi
exec 19>/var/log/minios/startup.log
BASH_XTRACEFD=19
set -x

# Variables
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
CMDLINE=$(cat /proc/cmdline)
CONFIG=/etc/minios/config
BUILDCONFIG=/etc/minios/buildconfig
if [ -f $CONFIG ]; then
    read_config $CONFIG LIVEKITNAME
else
    LIVEKITNAME="minios"
fi
read_cmdline $CMDLINE
if [ -d /run/initramfs/memory/bundles ]; then
    BUNDLES=/run/initramfs/memory/bundles
    INITRD_TYPE="livekit"
elif [ -d /memory/bundles ]; then
    BUNDLES=/memory/bundles
    INITRD_TYPE="uird"
fi
if [ -n $SFLAGS ] && [ -z $FLAGS ]; then
    FLAGS=$SFLAGS
fi
CORE_BUNDLE_PREFIX=00-
BEXT=sb
if [ "$INITRD_TYPE" = "livekit" ]; then
    if [ "$FLAGS" = "toram" ]; then
        MEDIA="/run/initramfs/memory/toram"
    else
        MEDIA="/run/initramfs/memory/data/$LIVEKITNAME"
    fi
elif [ "$INITRD_TYPE" = "uird" ]; then
    MEDIA="/memory/data/from/0/$LIVEKITNAME"
fi
if id -nu 1000 2>/dev/null; then
    CURRENT_USER_NAME=$(id -nu 1000)
    CURRENT_USER_GROUP=$(id -ng 1000)
fi

# Comparison of configuration files on the media and in the system
touch "$MEDIA/.empty" 2>/dev/null && rm -f "$MEDIA/.empty" 2>/dev/null
if [ $? -ne 0 ]; then
    WRITABLE="false"
    if [ -z $SSH_KEY ]; then
        SSH_KEY="authorized_keys"
    fi
    if [ -f $MEDIA/$LIVEKITNAME.conf ]; then
        if [ ! -f /etc/$LIVEKITNAME/$LIVEKITNAME.conf ]; then
            cp -fp $MEDIA/$LIVEKITNAME.conf /etc/$LIVEKITNAME/$LIVEKITNAME.conf
        fi
    fi
    if [ -f $MEDIA/$SSH_KEY ]; then
        if [ ! -d /root/.ssh ]; then
            mkdir /root/.ssh
            chmod 700 /root/.ssh
            cp -fp $MEDIA/$SSH_KEY /root/.ssh/authorized_keys
            chmod 600 /root/.ssh/authorized_keys
        fi
    fi
else
    WRITABLE="true"
    if [ -d $MEDIA ]; then
        if [ -f $MEDIA/$LIVEKITNAME.conf ] && [ -f /etc/$LIVEKITNAME/$LIVEKITNAME.conf ]; then
            if [ "$MEDIA/$LIVEKITNAME.conf" -nt "/etc/$LIVEKITNAME/$LIVEKITNAME.conf" ]; then
                cp -fp $MEDIA/$LIVEKITNAME.conf /etc/$LIVEKITNAME/$LIVEKITNAME.conf
            elif [ "$MEDIA/$LIVEKITNAME.conf" -ot "/etc/$LIVEKITNAME/$LIVEKITNAME.conf" ]; then
                cp -fp /etc/$LIVEKITNAME/$LIVEKITNAME.conf $MEDIA/$LIVEKITNAME.conf
            fi
        elif [ -f $MEDIA/$LIVEKITNAME.conf ]; then
            cp -fp $MEDIA/$LIVEKITNAME.conf /etc/$LIVEKITNAME/$LIVEKITNAME.conf
        elif [ -f /etc/$LIVEKITNAME/$LIVEKITNAME.conf ]; then
            cp -fp /etc/$LIVEKITNAME/$LIVEKITNAME.conf $MEDIA/$LIVEKITNAME.conf
        fi
        if [ -z $SSH_KEY ]; then
            SSH_KEY=$(read_config_value /etc/$LIVEKITNAME/$LIVEKITNAME.conf SSH_KEY)
            if [ -z $SSH_KEY ]; then
                SSH_KEY="authorized_keys"
            fi
        fi
        if [ ! -d /root/.ssh ]; then
            mkdir /root/.ssh
            chmod 700 /root/.ssh
        fi
        if [ -f $MEDIA/$SSH_KEY ] && [ -f /root/.ssh/authorized_keys ]; then
            if [ "$MEDIA/$SSH_KEY" -nt "/root/.ssh/authorized_keys" ]; then
                cp -fp $MEDIA/$SSH_KEY /root/.ssh/authorized_keys
                chmod 600 /root/.ssh/authorized_keys
            elif [ "$MEDIA/$SSH_KEY" -ot "/root/.ssh/authorized_keys" ]; then
                cp -fp /root/.ssh/authorized_keys $MEDIA/$SSH_KEY
            fi
        elif [ -f $MEDIA/$SSH_KEY ]; then
            cp -fp $MEDIA/$SSH_KEY /root/.ssh/authorized_keys
            chmod 600 /root/.ssh/authorized_keys
        elif [ -f /root/.ssh/authorized_keys ]; then
            cp -fp /root/.ssh/authorized_keys $MEDIA/$SSH_KEY
        fi
    fi
fi
if [ "$WRITABLE" = "true" ]; then
    if [ -f /etc/$LIVEKITNAME/$LIVEKITNAME.conf ]; then
        cp -fp /etc/$LIVEKITNAME/$LIVEKITNAME.conf $MEDIA/$LIVEKITNAME.conf
    fi
    if [ -f /root/.ssh/authorized_keys ]; then
        cp -fp /root/.ssh/authorized_keys $MEDIA/$SSH_KEY
    fi
fi

# Copying bootloader configuration files to the system
cp -fp $MEDIA/boot/grub/grub.cfg /etc/$LIVEKITNAME/grub.cfg
cp -fp $MEDIA/boot/syslinux.cfg /etc/$LIVEKITNAME/syslinux.cfg

echo "Original /etc/$LIVEKITNAME/$LIVEKITNAME.conf configuration file contents:"
cat /etc/$LIVEKITNAME/$LIVEKITNAME.conf
echo ""

cat <<EOF >/etc/issue


                                                                          \\l





                        Thank you for using MiniOS.
EOF

if [ -f $BUILDCONFIG ]; then
    read_config $BUILDCONFIG DISTRIBUTION DESKTOP_ENVIRONMENT
    if [ $DISTRIBUTION = "stretch" ] || [ $DISTRIBUTION = "buster" ] || [ $DISTRIBUTION = "bullseye" ] || [ $DISTRIBUTION = "bookworm" ] || [ $DISTRIBUTION = "kali-rolling" ] || [ $DISTRIBUTION = "sid" ] || [ $DISTRIBUTION = "orel" ]; then
        DISTRIBUTION_TYPE="debian"
    elif [ $DISTRIBUTION = "bionic" ] || [ $DISTRIBUTION = "focal" ] || [ $DISTRIBUTION = "jammy" ]; then
        DISTRIBUTION_TYPE="ubuntu"
    fi
    if [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
        cat <<EOF >>/etc/issue
                        Based on [1;33mUbuntu[0;29m.
EOF
    elif [ $DISTRIBUTION_TYPE = "debian" ] && [ $DISTRIBUTION = "kali-rolling" ]; then
        cat <<EOF >>/etc/issue
                        Based on [1;36mKali Linux[0;29m.
EOF
    elif [ $DISTRIBUTION_TYPE = "debian" ] && [ $DISTRIBUTION = "orel" ]; then
        cat <<EOF >>/etc/issue
                        Based on [1;34mAstra Linux[0;29m.
EOF
    elif [ $DISTRIBUTION_TYPE = "debian" ] && [ $DISTRIBUTION != "kali-rolling" ]; then
        cat <<EOF >>/etc/issue
                        Based on [1;31mDebian GNU/Linux[0;29m.
EOF
    else
        cat <<EOF >>/etc/issue
                        Based on [1;31mDebian GNU/Linux[0;29m.
EOF
    fi
    if [ $DESKTOP_ENVIRONMENT = "slax" ]; then
        cat <<EOF >>/etc/issue
                        Powered by [1;32mSlax[0;29m.
EOF
    fi
else
    cat <<EOF >>/etc/issue
                        Based on [1;31mDebian GNU/Linux[0;29m.
EOF
fi

cat <<EOF >>/etc/issue

    [1;1m::::    ::::  ::::::::::: ::::    ::: ::::::::::: ::::::::   ::::::::  [0;29m
    [1;1m+:+:+: :+:+:+     :+:     :+:+:   :+:     :+:    :+:    :+: :+:    :+: [0;29m
    [1;1m+:+ +:+:+ +:+     +:+     :+:+:+  +:+     +:+    +:+    +:+ +:+        [0;29m
    [1;1m+#+  +:+  +#+     +#+     +#+ +:+ +#+     +#+    +#+    +:+ +#++:++#++ [0;29m
    [1;1m+#+       +#+     +#+     +#+  +#+#+#     +#+    +#+    +#+        +#+ [0;29m
    [1;1m#+#       #+#     #+#     #+#   #+#+#     #+#    #+#    #+# #+#    #+# [0;29m
    [1;1m###       ### ########### ###    #### ########### ########   ########  [0;29m 

EOF

# Reading variables
if [ -z "$USER_NAME" ]; then
    read_config /etc/$LIVEKITNAME/$LIVEKITNAME.conf USER_NAME
    if [ -z "$USER_NAME" ]; then
        USER_NAME="live"
    fi
fi
if [ -z "$USER_PASSWORD" ]; then
    read_config /etc/$LIVEKITNAME/$LIVEKITNAME.conf USER_PASSWORD
    if [ -z "$USER_PASSWORD" ]; then
        USER_PASSWORD="evil"
    fi
fi
if [ -z "$ROOT_PASSWORD" ]; then
    read_config /etc/$LIVEKITNAME/$LIVEKITNAME.conf ROOT_PASSWORD
    if [ -z "$ROOT_PASSWORD" ]; then
        ROOT_PASSWORD="toor"
    fi
fi
if [ -z "$HOST_NAME" ]; then
    read_config /etc/$LIVEKITNAME/$LIVEKITNAME.conf HOST_NAME
    if [ -z "$HOST_NAME" ]; then
        HOST_NAME="minios"
    fi
fi
if [ -z "$DEFAULT_TARGET" ]; then
    read_config /etc/$LIVEKITNAME/$LIVEKITNAME.conf DEFAULT_TARGET
    if [ -z "$DEFAULT_TARGET" ]; then
        DEFAULT_TARGET="graphical"
    fi
fi
if [ -z "$SSH_KEY" ]; then
    read_config /etc/$LIVEKITNAME/$LIVEKITNAME.conf SSH_KEY
    if [ -z "$SSH_KEY" ]; then
        SSH_KEY="authorized_keys"
    fi
fi
if [ -z "$CLOUD" ]; then
    read_config /etc/$LIVEKITNAME/$LIVEKITNAME.conf CLOUD
    if [ -z "$CLOUD" ]; then
        CLOUD="false"
    fi
fi
if [ -z "$SCRIPTS" ]; then
    read_config /etc/$LIVEKITNAME/$LIVEKITNAME.conf SCRIPTS
    if [ -z "$SCRIPTS" ]; then
        SCRIPTS="true"
    fi
    if [ "$SCRIPTS" = "true" ]; then
        SCRIPTS="interactive"
    fi
fi
if [ -z "$HIDE_CREDENTIALS" ]; then
    read_config /etc/$LIVEKITNAME/$LIVEKITNAME.conf HIDE_CREDENTIALS
    if [ -z "$HIDE_CREDENTIALS" ]; then
        HIDE_CREDENTIALS="false"
    fi
fi

# fix users
users-fix $BUNDLES #&
# fix caches
update-cache $BUNDLES &
# fix dpkg
dpkg-fix $BUNDLES &

# Set up user 'root'
if [ ! -f /var/.minios-setup-completed ]; then
    cp -rT /etc/skel /root
    # create root directories
    if [ -d /root ]; then
        for dir in Desktop Documents Downloads Music Pictures Public Templates Videos; do
            mkdir -p /root/$dir
        done
    fi
    chown 0:0 /root
    chown -R 0:0 /root
fi

if [ -f /usr/bin/x11vnc ]; then
    x11vnc -storepasswd "$ROOT_PASSWORD" /etc/vncpassword
fi

#sed -i -e "/CLOUD=/s/=.*/=$CLOUD/" /etc/$LIVEKITNAME/$LIVEKITNAME.conf
if [ "$CLOUD" != "true" ]; then
    if [ "$USER_NAME" != "root" ]; then
        echo "User name is $USER_NAME"
        # Set up user
        #USER_NAME="live"
        #USER_GROUP="live"
        USER_GROUP=$USER_NAME
        if [ ! -f /var/.minios-setup-completed ]; then
            adduser --uid 1000 --gecos '' $USER_NAME --disabled-password
            usermod -a -G sudo $USER_NAME
        elif [ -n $CURRENT_USER_NAME ] && [ "$USER_NAME" != "$CURRENT_USER_NAME" ]; then
            usermod -l $USER_NAME $CURRENT_USER_NAME
            usermod -m -d /home/$USER_NAME $USER_NAME
            groupmod -n $USER_GROUP $CURRENT_USER_GROUP
        fi
    fi
else
    USER_NAME="root"
    DEFAULT_TARGET="multi-user"
fi

if [ ! -f /var/.minios-setup-completed ]; then
    if [ "$USER_NAME" != "root" ]; then
        cp -rT /etc/skel /home/$USER_NAME
        # create user directories
        if [ -d /home/$USER_NAME ]; then
            for dir in Desktop Documents Downloads Music Pictures Public Templates Videos; do
                mkdir -p /home/$USER_NAME/$dir
            done
            if [ ! -d /home/$USER_NAME/.ssh ]; then
                mkdir /home/$USER_NAME/.ssh
                chmod 700 /home/$USER_NAME/.ssh
            fi
            if [ -f /root/.ssh/authorized_keys ]; then
                cp /root/.ssh/authorized_keys /home/$USER_NAME/.ssh/authorized_keys
            fi
            USER_ID=$(id -u $USER_NAME)
            GROUP_ID=$(id -g $USER_NAME)
            chown $USER_ID:$GROUP_ID /home/$USER_NAME
            chown -R $USER_ID:$GROUP_ID /home/$USER_NAME
        fi
    fi
fi

#awk '!x[$0]++' /etc/shadow >/etc/shadow.tmp
#mv /etc/shadow.tmp /etc/shadow

# Set up password for root
echo root:$ROOT_PASSWORD | chpasswd
if [ "$USER_NAME" != "root" ]; then
    # Set up password for user
    echo $USER_NAME:$USER_PASSWORD | chpasswd
fi

if [ "$USER_NAME" != "root" ]; then
    cat <<EOF >/etc/sudoers.d/90-minios
# live user is default user in minios.
# It needs passwordless sudo functionality.
$USER_NAME ALL=(ALL) NOPASSWD:ALL
EOF
fi

if [ "$HIDE_CREDENTIALS" != "true" ]; then
    echo "HIDE_CREDENTIALS is $HIDE_CREDENTIALS"
    if [ "$CLOUD" != "true" ]; then
        if [ "$USER_NAME" != "root" ]; then
            cat <<EOF >>/etc/issue
                        Root login name: [1;33mroot[0;29m
                        Password: [1;33m$ROOT_PASSWORD[0;29m
                        User login name: [1;33m$USER_NAME[0;29m
                        Password: [1;33m$USER_PASSWORD[0;29m





EOF
        else
            cat <<EOF >>/etc/issue
                        Root login name: [1;33mroot[0;29m
                        Password: [1;33m$ROOT_PASSWORD[0;29m







EOF
        fi
    else
        cat <<EOF >>/etc/issue
                        User login name set by
                        cloud-init. You must use
                        your ssh key to login.
                        Root login name: [1;33mroot[0;29m
                        Password: [1;33m$ROOT_PASSWORD[0;29m






EOF
    fi
else
    cat <<EOF >>/etc/issue









EOF
fi

if [ "$CLOUD" != "true" ]; then
    if [ -n "$HOST_NAME" ]; then
        echo $HOST_NAME >/etc/hostname
        cat <<EOF >/etc/hosts
127.0.0.1       localhost $HOST_NAME
::1             localhost ip6-localhost ip6-loopback $HOST_NAME
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

EOF
    fi
fi

echo "=====> Making changes to the configuration file..."
echo "Changes:"

CONFIG_USER_NAME=$(read_config_value /etc/$LIVEKITNAME/$LIVEKITNAME.conf USER_NAME)
if [ "$USER_NAME" != "$CONFIG_USER_NAME" ]; then
    echo "USER_NAME=$USER_NAME, CONFIG_USER_NAME=$CONFIG_USER_NAME"
    if [ -n "$USER_NAME" ]; then
        sed -i -e "/USER_NAME=/s/=.*/=\"$USER_NAME\"/" /etc/$LIVEKITNAME/$LIVEKITNAME.conf
    fi
fi
CONFIG_USER_PASSWORD=$(read_config_value /etc/$LIVEKITNAME/$LIVEKITNAME.conf USER_PASSWORD)
if [ "$USER_PASSWORD" != "$CONFIG_USER_PASSWORD" ]; then
    echo "USER_PASSWORD=$USER_PASSWORD, CONFIG_USER_PASSWORD=$CONFIG_USER_PASSWORD"
    if [ -n "$USER_PASSWORD" ]; then
        sed -i -e "/USER_PASSWORD=/s/=.*/=\"$USER_PASSWORD\"/" /etc/$LIVEKITNAME/$LIVEKITNAME.conf
    fi
fi
CONFIG_ROOT_PASSWORD=$(read_config_value /etc/$LIVEKITNAME/$LIVEKITNAME.conf ROOT_PASSWORD)
if [ "$ROOT_PASSWORD" != "$CONFIG_ROOT_PASSWORD" ]; then
    echo "ROOT_PASSWORD=$ROOT_PASSWORD, CONFIG_ROOT_PASSWORD=$CONFIG_ROOT_PASSWORD"
    if [ -n "$ROOT_PASSWORD" ]; then
        sed -i -e "/ROOT_PASSWORD=/s/=.*/=\"$ROOT_PASSWORD\"/" /etc/$LIVEKITNAME/$LIVEKITNAME.conf
    fi
fi
CONFIG_HOST_NAME=$(read_config_value /etc/$LIVEKITNAME/$LIVEKITNAME.conf HOST_NAME)
if [ "$HOST_NAME" != "$CONFIG_HOST_NAME" ]; then
    echo "HOST_NAME=$HOST_NAME, CONFIG_HOST_NAME=$CONFIG_HOST_NAME"
    if [ -n "$HOST_NAME" ]; then
        sed -i -e "/HOST_NAME=/s/=.*/=\"$HOST_NAME\"/" /etc/$LIVEKITNAME/$LIVEKITNAME.conf
    fi
fi
CONFIG_DEFAULT_TARGET=$(read_config_value /etc/$LIVEKITNAME/$LIVEKITNAME.conf DEFAULT_TARGET)
if [ "$DEFAULT_TARGET" != "$CONFIG_DEFAULT_TARGET" ]; then
    echo "DEFAULT_TARGET=$DEFAULT_TARGET, CONFIG_DEFAULT_TARGET=$CONFIG_DEFAULT_TARGET"
    if [ -n "$DEFAULT_TARGET" ]; then
        sed -i -e "/DEFAULT_TARGET=/s/=.*/=\"$DEFAULT_TARGET\"/" /etc/$LIVEKITNAME/$LIVEKITNAME.conf
    fi
fi
CONFIG_ENABLE_SERVICES=$(read_config_value /etc/$LIVEKITNAME/$LIVEKITNAME.conf ENABLE_SERVICES)
if [ "$ENABLE_SERVICES" != "$CONFIG_ENABLE_SERVICES" ]; then
    echo "ENABLE_SERVICES=$ENABLE_SERVICES, CONFIG_ENABLE_SERVICES=$CONFIG_ENABLE_SERVICES"
    if [ -n "$ENABLE_SERVICES" ]; then
        sed -i -e "/ENABLE_SERVICES=/s/=.*/=\"$ENABLE_SERVICES\"/" /etc/$LIVEKITNAME/$LIVEKITNAME.conf
    fi
fi
CONFIG_DISABLE_SERVICES=$(read_config_value /etc/$LIVEKITNAME/$LIVEKITNAME.conf DISABLE_SERVICES)
if [ "$DISABLE_SERVICES" != "$CONFIG_DISABLE_SERVICES" ]; then
    echo "DISABLE_SERVICES=$DISABLE_SERVICES, CONFIG_DISABLE_SERVICES=$CONFIG_DISABLE_SERVICES"
    if [ -n "$DISABLE_SERVICES" ]; then
        sed -i -e "/DISABLE_SERVICES=/s/=.*/=\"$DISABLE_SERVICES\"/" /etc/$LIVEKITNAME/$LIVEKITNAME.conf
    fi
fi
CONFIG_SSH_KEY=$(read_config_value /etc/$LIVEKITNAME/$LIVEKITNAME.conf SSH_KEY)
echo "SSH_KEY=$SSH_KEY, CONFIG_SSH_KEY=$CONFIG_SSH_KEY"
if [ "$SSH_KEY" != "$CONFIG_SSH_KEY" ]; then
    if [ -n "$SSH_KEY" ]; then
        sed -i -e "/SSH_KEY=/s/=.*/=\"$SSH_KEY\"/" /etc/$LIVEKITNAME/$LIVEKITNAME.conf
    fi
fi
CONFIG_SCRIPTS=$(read_config_value /etc/$LIVEKITNAME/$LIVEKITNAME.conf SCRIPTS)
if [ "$SCRIPTS" != "$CONFIG_SCRIPTS" ]; then
    echo "SCRIPTS=$SCRIPTS, CONFIG_SCRIPTS=$CONFIG_SCRIPTS"
    if [ -n "$SCRIPTS" ]; then
        sed -i -e "/SCRIPTS=/s/=.*/=\"$SCRIPTS\"/" /etc/$LIVEKITNAME/$LIVEKITNAME.conf
    fi
fi
CONFIG_CLOUD=$(read_config_value /etc/$LIVEKITNAME/$LIVEKITNAME.conf CLOUD)
if [ "$CLOUD" != "$CONFIG_CLOUD" ]; then
    echo "CLOUD=$CLOUD, CONFIG_CLOUD=$CONFIG_CLOUD"
    if [ -n "$CLOUD" ]; then
        sed -i -e "/CLOUD=/s/=.*/=\"$CLOUD\"/" /etc/$LIVEKITNAME/$LIVEKITNAME.conf
    fi
fi
CONFIG_HIDE_CREDENTIALS=$(read_config_value /etc/$LIVEKITNAME/$LIVEKITNAME.conf HIDE_CREDENTIALS)
if [ "$HIDE_CREDENTIALS" != "$CONFIG_HIDE_CREDENTIALS" ]; then
    echo "HIDE_CREDENTIALS=$HIDE_CREDENTIALS, CONFIG_HIDE_CREDENTIALS=$CONFIG_HIDE_CREDENTIALS"
    if [ -n "$HIDE_CREDENTIALS" ]; then
        sed -i -e "/HIDE_CREDENTIALS=/s/=.*/=\"$HIDE_CREDENTIALS\"/" /etc/$LIVEKITNAME/$LIVEKITNAME.conf
    fi
fi
CONFIG_INITRD_TYPE=$(read_config_value /etc/$LIVEKITNAME/$LIVEKITNAME.conf INITRD_TYPE)
if [ "$INITRD_TYPE" != "$CONFIG_INITRD_TYPE" ]; then
    echo "INITRD_TYPE=$INITRD_TYPE, CONFIG_INITRD_TYPE=$CONFIG_INITRD_TYPE"
    if [ -n "$INITRD_TYPE" ]; then
        sed -i -e "/INITRD_TYPE=/s/=.*/=\"$INITRD_TYPE\"/" /etc/$LIVEKITNAME/$LIVEKITNAME.conf
        sed -i -e "/INITRD_TYPE=/s/=.*/=\"$INITRD_TYPE\"/" /etc/$LIVEKITNAME/buildconfig
    fi
fi

echo "
New /etc/$LIVEKITNAME/$LIVEKITNAME.conf configuration file contents:"
cat /etc/$LIVEKITNAME/$LIVEKITNAME.conf
echo ""

# If newer kernels are used, then xorg will not run on hyper-v without this configuration file.
read_config $BUILDCONFIG DISTRIBUTION DISTRIBUTION_TYPE KERNEL_BPO KERNEL_AUFS
if ([ "$DISTRIBUTION" = "bookworm" ] || [ "$DISTRIBUTION" = "kali-rolling" ] || [ "$DISTRIBUTION" = "sid" ]) || ([ "$DISTRIBUTION" = "bullseye" ] && [ $KERNEL_BPO = "true" ]) || ([ $DISTRIBUTION_TYPE = "ubuntu" ] && [ $KERNEL_AUFS = "true" ]); then
    if [ "$(virt-what)" = "hyperv" ]; then
        if [ ! -d /etc/X11/xorg.conf.d ]; then
            mkdir -p /etc/X11/xorg.conf.d
        fi
        cat <<EOF >/etc/X11/xorg.conf.d/30-hyperv.conf
Section "Device"
    Identifier  "HYPER-V Framebuffer"
    Driver      "fbdev"
EndSection

EOF
    fi
fi

if [ -f /etc/default/nodm ]; then
    sed -i "s/NODM_USER=live/NODM_USER=$USER_NAME/g" /etc/default/nodm
fi
if [ -f /etc/slim.conf ]; then
    #sed -i "s/#default_user        simone/default_user        $USER_NAME/g" /etc/slim.conf
    sed -i "s/default_user        live/default_user        $USER_NAME/g" /etc/slim.conf
fi
if [ -f /etc/lightdm/lightdm.conf ]; then
    sed -i "s/#autologin-user=/autologin-user=$USER_NAME/g" /etc/lightdm/lightdm.conf
    sed -i "s/#autologin-user-timeout=0/autologin-user-timeout=0/g" /etc/lightdm/lightdm.conf
fi

if [ ! -f /var/.minios-setup-completed ]; then
    echo "MiniOS setup is completed." >/var/.minios-setup-completed
fi

exit 0
