#!/bin/bash

# Author: crims0n. <https://minios.dev>
# Author: Patrick Verner and Jason Vasquez

. /etc/minios/config || exit 1
. /etc/minios/buildconfig || exit 1
. /usr/lib/minioslib || exit 1

CMDLINE=$(cat /proc/cmdline)
read_cmdline $CMDLINE

if [ -d /run/initramfs/memory/bundles ]; then
    BUNDLES=/run/initramfs/memory/bundles
    INITRD="livekit"
elif [ -d /memory/bundles ]; then
    BUNDLES=/memory/bundles
    INITRD="uird"
fi
if [ "$INITRD" = "livekit" ]; then
    if [ "$FLAGS" = "toram" ]; then
        MEDIA="/run/initramfs/memory/toram"
    else
        MEDIA="/run/initramfs/memory/data/$LIVEKITNAME"
    fi
elif [ "$INITRD" = "uird" ]; then
    MEDIA="/memory/data/from/0/$LIVEKITNAME"
fi

FX=
script_header() {
    if [ -z "$FX" ]; then
        echo -e "${CYAN}Executing user scripts... ${YELLOW}\n"
        FX=FX
    fi
}

_script_list() {
    for F in $(ls $1/scripts/* 2>/dev/null); do
        script_header
        echo ">>> $F"
        if [ -x $F ]; then
            $F
        else
            read FF <$F &>/dev/null
            FFF=${FF###!}
            echo $FFF
            [ ".$FFF" != ".$FF" ] && FFF=${FFF%% } || FFF=
            [ -n "$FFF" ] && $FFF $F || /bin/sh $F
        fi
        [ -n "$2" ] && rm -f $F
    done
}

script_list() { _script_list $1 $2; }

if [ "$scripts" != "no" ]; then
    if $(ls $MEDIA/scripts/* 2>/dev/null); then
        script_list $MEDIA
        [ -n "$FX" ] && echo -e "${ENDCOLOR}"
    fi
fi
