#!/bin/bash

# Author: crims0n. <https://minios.dev>
# Author: Patrick Verner and Jason Vasquez

exec 19>/var/log/minios/minios-script-launcher.log
BASH_XTRACEFD=19
set -x

. /etc/minios/config || exit 1
. /etc/minios/buildconfig || exit 1
. /usr/lib/minioslib || exit 1

CMDLINE=$(cat /proc/cmdline)
read_cmdline $CMDLINE

if [ -d /run/initramfs/memory/bundles ]; then
    BUNDLES=/run/initramfs/memory/bundles
    INITRD="livekit"
elif [ -d /memory/bundles ]; then
    BUNDLES=/memory/bundles
    INITRD="uird"
fi
if [ "$INITRD" = "livekit" ]; then
    if [ "$FLAGS" = "toram" ]; then
        MEDIA="/run/initramfs/memory/toram"
    else
        MEDIA="/run/initramfs/memory/data/$LIVEKITNAME"
    fi
elif [ "$INITRD" = "uird" ]; then
    MEDIA="/memory/data/from/0/$LIVEKITNAME"
fi

FX=
# Function to print a header before executing user scripts
script_header() {
    if [ -z "$FX" ]; then
        echo -e "${CYAN}Executing user scripts... ${YELLOW}\n"
        FX=FX
    fi
}

# Function to list and execute scripts in a given directory
_script_list() {
    for SCRIPT in $(ls $1/scripts/* 2>/dev/null); do
        script_header
        echo ">>> $SCRIPT"
        if [ -x $SCRIPT ]; then
            $SCRIPT
        else
            read FIRST_LINE <$SCRIPT &>/dev/null
            INTERPRETER=${FIRST_LINE###!}
            echo $INTERPRETER
            [ ".$INTERPRETER" != ".$FIRST_LINE" ] && INTERPRETER=${INTERPRETER%% } || INTERPRETER=
            [ -n "$INTERPRETER" ] && $INTERPRETER $SCRIPT || /bin/sh $SCRIPT
        fi
        [ -n "$2" ] && rm -f $SCRIPT
    done
}

script_list() { _script_list $1 $2; }

if [ "$scripts" != "false" ]; then
    if ls $MEDIA/scripts/* 2>/dev/null; then
        script_list $MEDIA
        [ -n "$FX" ] && echo -e "${ENDCOLOR}"
    fi
fi
