#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

function language_to_array() {
    local IFS
    IFS="_"
    LANG=($LOCALE)
}
language_to_array

apt-get update >>$OUTPUT 2>&1

# install packages
if [ $DISTRIBUTION = "stretch" ]; then
    apt-get install -y chromium >>$OUTPUT 2>&1
else
    apt-get install -y \
        chromium chromium-sandbox >>$OUTPUT 2>&1
fi
if [ $LOCALE != "en_US" ]; then
    apt-get install -y chromium-l10n >>$OUTPUT 2>&1
fi

if [ ! -d /etc/chromium.d/ ]; then
    mkdir /etc/chromium.d
fi
echo 'export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --disk-cache-dir=/dev/null --disk-cache-size=1"' >>/etc/chromium.d/default-flags

if [[ $DESKTOP_ENVIRONMENT == *"xfce"* ]]; then
    if [ ! -d /etc/skel/.config/xfce4 ]; then
        mkdir -p /etc/skel/.config/xfce4
    fi
    if [ $PACKAGE_VARIANT = "minimum" ]; then
        cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=Thunar
WebBrowser=chromium

EOF
    elif [ $PACKAGE_VARIANT = "standard" ] || [ $PACKAGE_VARIANT = "maximum" ] || [ $PACKAGE_VARIANT = "ultra" ]; then
        cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=chromium

EOF
    fi
fi