#!/bin/bash

CWD=$(dirname $(readlink -f $0))

NAME=fluxbox
VERSION=1.3.5

# first install stock version

apt-get update >>$OUTPUT 2>&1
apt-get install --no-install-recommends --yes \
    $NAME \
    feh \
    compton \
    volumeicon-alsa \
    murrine-themes \
    libnotify4 \
    scrot >>$OUTPUT 2>&1

(cd /rootcopy-install && cp --parents -afr * /)

if [ $DISTRIBUTION = "stretch" ]; then
    sed -i "s,chromium chromium-sandbox,chromium,g" /usr/bin/fbliveapp
fi
