#!/bin/bash

CWD=$(dirname $(readlink -f $0))

NAME=fluxbox
VERSION=1.3.5

# first install stock version

apt-get update >>$OUTPUT 2>&1

wget http://mirror.yandex.ru/mirrors/MX-Linux/MX-Packages/antix/sid/pool/main/a/adwaita-icon-theme-antix/adwaita-icon-theme-antix_3.30.2~antix1_all.deb

apt-get install --no-install-recommends --yes \
    $NAME \
    feh \
    compton \
    volumeicon-alsa \
    murrine-themes \
    libnotify4 \
    scrot \
    ./adwaita-icon-theme-antix_3.30.2~antix1_all.deb >>$OUTPUT 2>&1

rm -f ./adwaita-icon-theme-antix_3.30.2~antix1_all.deb >>$OUTPUT 2>&1

(cd /rootcopy-install && cp --parents -afr * /)

if [ $DISTRIBUTION = "stretch" ]; then
    sed -i "s,chromium chromium-sandbox,chromium,g" /usr/bin/fbliveapp
    sed -i "s,connman-gtk,wicd-gtk,g" /etc/skel/.fluxbox/menu
fi
