#!/bin/bash

cp -rT /etc/skel /home/$USER_NAME
cp -rT /etc/skel /root
chown 1000:1000 /home/$USER_NAME
chown -R 1000:1000 /home/$USER_NAME
chown 0:0 /root
chown -R 0:0 /root

if [ $PACKAGE_VARIANT = "minimal" ]; then
    sed -i 's,create=xarchiver --add-to,create=xarchiver --compress,g' /usr/share/libfm/archivers.list
fi

rm -Rf /usr/share/icons/gnome/256x256 >>$OUTPUT 2>&1
rm -Rf /usr/share/icons/Adwaita/256x256 >>$OUTPUT 2>&1
rm -Rf /usr/share/icons/Adwaita/512x512 >>$OUTPUT 2>&1
