#!/bin/bash

. /minioslib || exit 1

CWD=$(dirname $(readlink -f $0))

NAME=fluxbox
VERSION=1.3.5
if [ $DISTRIBUTION = "stretch" ] || [ $DISTRIBUTION = "buster" ]; then
    XLUNCH=4.5.3
    CBATTICON=1.6.7
else
    XLUNCH=4.7.3
    CBATTICON=1.6.10
fi

cat <<EOF >/etc/apt/sources.list.d/src.list
deb-src http://deb.debian.org/debian/ $DISTRIBUTION main contrib non-free

EOF

cd /

REBUILD=/tmp/$NAME-rebuild-$$

pkg update
pkg build-dep $NAME

mkdir -p $REBUILD
cd $REBUILD

pkg source $NAME

cd $NAME-$VERSION

cat $CWD/patches/fluxbox-slax.diff >debian/patches/fluxbox-slax.diff
echo fluxbox-slax.diff >>debian/patches/series

dpkg-buildpackage -us -uc

rm -Rf debian/$NAME/DEBIAN
rm -Rf debian/$NAME/usr/share/doc
rm -Rf debian/$NAME/usr/share/images

cp debian/$NAME/usr/bin/fluxbox /squashfs-root/usr/bin

# add xlunch from sources
wget -O /tmp/xlunch.tar.gz https://github.com/Tomas-M/xlunch/archive/v$XLUNCH.tar.gz
cd /tmp
tar -xf xlunch.tar.gz
cd xlunch-$XLUNCH
make
cp xlunch /squashfs-root/usr/bin
cp extra/gentriesquick /squashfs-root/usr/bin/xlunch_genquick
mkdir -p /squashfs-root/usr/share/icons/hicolor/48x48/apps/
cp extra/ghost.png /squashfs-root/usr/share/icons/hicolor/48x48/apps/xlunch_ghost.png

# add tray icon launcher
wget -O /tmp/systrayiconlauncher.tar.gz https://github.com/Tomas-M/SystrayIconLauncher/archive/master.tar.gz
cd /tmp
tar -xf systrayiconlauncher.tar.gz
cd SystrayIconLauncher-master
pkg install libgtk2.0-dev
make
cp systrayicon /squashfs-root/usr/bin

# add gtkdialog
wget -O /tmp/gtkdialog.tar.gz https://github.com/Tomas-M/GTKdialog/archive/master.tar.gz
cd /tmp
tar -xf gtkdialog.tar.gz
cd GTKdialog-master
make
cp gtkdialog /squashfs-root/usr/bin

# battery icon app
cd /tmp
wget https://github.com/valr/cbatticon/archive/$CBATTICON.tar.gz
tar -xf $CBATTICON.tar.gz
cd cbatticon-$CBATTICON
cp -R /usr/include/glib-2.0/* /usr/include
cp -R /usr/include/gtk-2.0/* /usr/include
pkg install libnotify-dev
sed -i "s/WITH_GTK3 = 1/WITH_GTK3 = 0/" Makefile
CFLAGS="-O2 \
-I/usr/lib/x86_64-linux-gnu/glib-2.0/include/ \
-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include/ \
-I/usr/include/gdk-pixbuf-2.0/ \
-I/usr/include/atk-1.0/ \
-I/usr/include/cairo \
-I/usr/include/pango-1.0 \
-I/usr/include/glib-2.0 \
-I/usr/include/gtk-2.0" \
    make
cp cbatticon /squashfs-root/usr/bin

if [ $COMP_TYPE = "zstd" ]; then
    time mksquashfs /squashfs-root /$MODULE.$BEXT -comp $COMP_TYPE -Xcompression-level 19 -b 1024K -always-use-fragments -noappend
else
    time mksquashfs /squashfs-root /$MODULE.$BEXT -comp $COMP_TYPE -b 1024K -always-use-fragments -noappend
fi
