#!/bin/bash

. /minioslib || exit 1

CWD=$(dirname $(readlink -f $0))

NAME=fluxbox
VERSION=1.3.5

# first install stock version

pkg update

pkg install \
    $NAME \
    feh \
    compton \
    volumeicon-alsa \
    murrine-themes \
    libnotify4 \
    scrot \
    adwaita-icon-theme-antix

(cd /rootcopy-install && cp --parents -afr * /)

if [ $DISTRIBUTION = "stretch" ]; then
    sed -i "s,chromium chromium-sandbox,chromium,g" /usr/bin/fbliveapp
    sed -i "s,connman-gtk,wicd-gtk,g" /etc/skel/.fluxbox/menu
fi

rm -f /usr/share/applications/5chromium.desktop

if [ $LOCALE = "ru_RU" ]; then
    pkg install fbxkb
    # Locale
    echo 'LC_ALL="ru_RU.UTF-8"
    ' >/etc/profile.d/locale_ru.sh
    sed -i '37G' /etc/skel/.fluxbox/startup
    sed -i '38i# layout selector' /etc/skel/.fluxbox/startup
    sed -i '39ifbxkb &' /etc/skel/.fluxbox/startup
    # Fluxbox menu
    sed -i "s/Desktop menu/Меню рабочего стола/g" /etc/skel/.fluxbox/menu
    sed -i "s/Terminal/Терминал/g" /etc/skel/.fluxbox/menu
    sed -i "s/File Manager/Менеджер файлов/g" /etc/skel/.fluxbox/menu
    sed -i "s/Web Browser/Браузер/g" /etc/skel/.fluxbox/menu
    sed -i "s/Text Editor/Текстовый редактор/g" /etc/skel/.fluxbox/menu
    sed -i "s/Calculator/Калькулятор/g" /etc/skel/.fluxbox/menu
    sed -i "s/Network Manager/Менеджер сети/g" /etc/skel/.fluxbox/menu
    sed -i "s/Run/Запустить/g" /etc/skel/.fluxbox/menu
    sed -i "s/Workspaces                .../Рабочие пространства    .../g" /etc/skel/.fluxbox/menu
    sed -i "s/Screen resolution         .../Разрешение экрана       .../g" /etc/skel/.fluxbox/menu
    sed -i "s/Keyboard layout           .../Раскладка клавиатуры    .../g" /etc/skel/.fluxbox/menu
    sed -i "s/Exit \/ Logout/Выход/g" /etc/skel/.fluxbox/menu
    sed -ie '15d;17,21d;23,64d' /etc/skel/.fluxbox/menu
    sed -ie '3d;5,7d' /etc/skel/.fluxbox/menu
    # Apps
    sed -i "s/Name=Terminal/Name=Терминал/g" /usr/share/applications/1terminal.desktop
    sed -i "s/Name=Web Browser/Name=Браузер/g" /usr/share/applications/5chromium.desktop
    sed -i "s/Name=Web Browser/Name=Браузер/g" /usr/share/applications/5firefox.desktop
    sed -i "s/Name=Video Player/Name=Видео-плеер/g" /usr/share/applications/videoplayer.desktop
elif [ $LOCALE = "es_ES" ]; then
    pkg install fbxkb
    # Locale
    echo 'LC_ALL="es_ES.UTF-8"
    ' >/etc/profile.d/locale_es.sh
    sed -i '37G' /etc/skel/.fluxbox/startup
    sed -i '38i# layout selector' /etc/skel/.fluxbox/startup
    sed -i '39ifbxkb &' /etc/skel/.fluxbox/startup
    # Fluxbox menu
    sed -i "s/Desktop menu/Menú de escritorio/g" /etc/skel/.fluxbox/menu
    #sed -i "s/Terminal/Terminal/g" /etc/skel/.fluxbox/menu
    sed -i "s/File Manager/Gestor de archivos/g" /etc/skel/.fluxbox/menu
    sed -i "s/Web Browser/Navegador web/g" /etc/skel/.fluxbox/menu
    sed -i "s/Text Editor/Editor de texto/g" /etc/skel/.fluxbox/menu
    sed -i "s/Calculator/Calculadora/g" /etc/skel/.fluxbox/menu
    sed -i "s/Network Manager/Gestor de red/g" /etc/skel/.fluxbox/menu
    sed -i "s/Run/Ejecutar/g" /etc/skel/.fluxbox/menu
    sed -i "s/Workspaces                .../Espacios de trabajo     .../g" /etc/skel/.fluxbox/menu
    sed -i "s/Screen resolution         .../Resolución de pantalla  .../g" /etc/skel/.fluxbox/menu
    sed -i "s/Keyboard layout           .../Disposición del teclado .../g" /etc/skel/.fluxbox/menu
    sed -i "s/Exit \/ Logout/Salida/g" /etc/skel/.fluxbox/menu
    sed -ie '15d;17,21d;23,64d' /etc/skel/.fluxbox/menu
    sed -ie '3d;5,7d' /etc/skel/.fluxbox/menu
    # Apps
    #sed -i "s/Name=Terminal/Name=Терминал/g" /usr/share/applications/1terminal.desktop
    sed -i "s/Name=Web Browser/Name=Navegador/g" /usr/share/applications/5chromium.desktop
    sed -i "s/Name=Web Browser/Name=Navegador/g" /usr/share/applications/5firefox.desktop
    sed -i "s/Name=Video Player/Name=Reproductor de vídeo/g" /usr/share/applications/videoplayer.desktop
fi
