#!/bin/bash

. /minioslib || exit 1

language_to_array

pkg update

if [ $DISTRIBUTION = "bookworm" ]; then
    pkg install \
        fluxbox-slax \
        feh \
        compton \
        volumeicon-alsa \
        murrine-themes \
        libnotify4 \
        scrot \
        adwaita-icon-theme-antix \
        xlunch-slax \
        systrayicon \
        gtkdialog-slax \
        cbatticon
else
    pkg install \
        fluxbox \
        feh \
        compton \
        volumeicon-alsa \
        murrine-themes \
        libnotify4 \
        scrot \
        adwaita-icon-theme-antix
fi

sleep 10

(cd /rootcopy-install && cp --parents -afr * /)

if [ $DISTRIBUTION = "stretch" ]; then
    sed -i "s,chromium chromium-sandbox,chromium,g" /usr/bin/fbliveapp
    sed -i "s,connman-gtk,wicd-gtk,g" /etc/skel/.fluxbox/menu
fi

rm -f /usr/share/applications/5chromium.desktop

# Fluxbox menu
for file in /etc/skel/.fluxbox/menu*; do
    if [ $file != "/etc/skel/.fluxbox/menu_${LNG[0]}" ]; then
        rm $file
    fi
done
mv /etc/skel/.fluxbox/menu_${LNG[0]} /etc/skel/.fluxbox/menu
if [ $LOCALE = "ru_RU" ]; then
    pkg install fbxkb
    # Locale
    echo 'LC_ALL="ru_RU.UTF-8"
    ' >/etc/profile.d/locale_ru.sh
    sed -i '37G' /etc/skel/.fluxbox/startup
    sed -i '38i# layout selector' /etc/skel/.fluxbox/startup
    sed -i '39ifbxkb &' /etc/skel/.fluxbox/startup
    # Apps
    sed -i "s/Name=Terminal/Name=Терминал/g" /usr/share/applications/1terminal.desktop
    sed -i "s/Name=Web Browser/Name=Браузер/g" /usr/share/applications/5chromium.desktop
    sed -i "s/Name=Web Browser/Name=Браузер/g" /usr/share/applications/5firefox.desktop
    sed -i "s/Name=Video Player/Name=Видео-плеер/g" /usr/share/applications/videoplayer.desktop
    sed -i "s/Name=Install/Name=Установить/g" /usr/share/applications/minios-installer.desktop
elif [ $LOCALE = "es_ES" ]; then
    pkg install fbxkb
    # Locale
    echo 'LC_ALL="es_ES.UTF-8"
    ' >/etc/profile.d/locale_es.sh
    sed -i '37G' /etc/skel/.fluxbox/startup
    sed -i '38i# layout selector' /etc/skel/.fluxbox/startup
    sed -i '39ifbxkb &' /etc/skel/.fluxbox/startup
    # Apps
    #sed -i "s/Name=Terminal/Name=Терминал/g" /usr/share/applications/1terminal.desktop
    sed -i "s/Name=Web Browser/Name=Navegador/g" /usr/share/applications/5chromium.desktop
    sed -i "s/Name=Web Browser/Name=Navegador/g" /usr/share/applications/5firefox.desktop
    sed -i "s/Name=Video Player/Name=Reproductor de vídeo/g" /usr/share/applications/videoplayer.desktop
    sed -i "s/Name=Install/Name=Instalar/g" /usr/share/applications/minios-installer.desktop
fi
