#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

function language_to_array() {
    local IFS
    IFS="_"
    LANG=($LOCALE)
}
language_to_array

apt-get update >>$OUTPUT 2>&1

# install packages
if [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
    DEBIAN_FRONTEND=noninteractive \
        apt-get install -y \
        firefox >>$OUTPUT 2>&1
elif [ $DISTRIBUTION_TYPE = "debian" ]; then
    DEBIAN_FRONTEND=noninteractive \
        apt-get install -y \
        firefox-esr >>$OUTPUT 2>&1
    if [ $LOCALE != "en_US" ]; then
        DEBIAN_FRONTEND=noninteractive \
            apt-get install -y firefox-esr-l10n-${LANG[0]} >>$OUTPUT 2>&1
    fi
fi

if [[ $DESKTOP_ENVIRONMENT == *"xfce"* ]]; then
    if [ ! -d /etc/skel/.config/xfce4 ]; then
        mkdir -p /etc/skel/.config/xfce4
    fi

    if [ $PACKAGE_VARIANT = "minimum" ]; then
        cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=Thunar
WebBrowser=firefox

EOF
    elif [ $PACKAGE_VARIANT = "standard" ] || [ $PACKAGE_VARIANT = "maximum" ] || [ $PACKAGE_VARIANT = "ultra" ]; then
        cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=firefox

EOF
    fi
fi

echo "application/pdf=firefox-esr.desktop" >>/usr/share/applications/mimeapps.list
if [ ${LANG[0]} = "en" ] || [ ${LANG[0]} = "ru" ]; then
    sed -i "s,about:welcome,file:///usr/share/minios/html/${LANG[0]}.html,g" /usr/share/firefox-esr/browser/defaults/preferences/firefox-branding.js
else
    sed -i "s,about:welcome,file:///usr/share/minios/html/index.html,g" /usr/share/firefox-esr/browser/defaults/preferences/firefox-branding.js
fi
cat <<'EOF' >>/usr/share/firefox-esr/browser/defaults/preferences/firefox-branding.js

pref("browser.tabs.drawInTitlebar", true);
pref("general.smoothScroll", false);
pref("browser.compactmode.show", true);
pref("browser.uidensity", 1);

EOF

if [ $DISTRIBUTION_TYPE = "debian" ] && [[ $DESKTOP_ENVIRONMENT == *"xfce"* ]]; then
    if [ $DISTRIBUTION = "buster" ] || [ $DISTRIBUTION = "stretch" ]; then
        sed -i "s/exo-open/env XDG_CURRENT_DESKTOP=XFCE exo-open/g" /usr/share/applications/exo-web-browser.desktop
    else
        sed -i "s/exo-open/env XDG_CURRENT_DESKTOP=XFCE exo-open/g" /usr/share/applications/xfce4-web-browser.desktop
    fi
    sed -i "s/exo-open/env XDG_CURRENT_DESKTOP=XFCE exo-open/g" /etc/skel/.config/xfce4/panel/launcher-5/WebBrowser.desktop
    sed -i "s,/usr/lib,env XDG_CURRENT_DESKTOP=XFCE /usr/lib,g" /usr/share/applications/firefox-esr.desktop
fi

PACKAGE="firefox-esr"
echo "PACKAGE=$PACKAGE" >/.package
echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g')" >>/.package