#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# install packages
if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
    $APT_CMD update >>$OUTPUT 2>&1 &&
        $APT_CMD install $APT_OPTIONS \
            $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | tr "\n" " ") >>$OUTPUT 2>&1
fi

echo 'export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --disk-cache-dir=/dev/null --disk-cache-size=1"' >>/etc/chromium.d/default-flags

if [ $PACKAGE_VARIANT = "minimal" ]; then
    cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=pcmanfm
WebBrowser=chromium

EOF
elif [ $PACKAGE_VARIANT = "standard" ]; then
    cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=chromium

EOF
fi