#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

apt-get $INSTALL_OPTIONS update >>$OUTPUT 2>&1

# install packages
if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
    if [ $DISTRIBUTION = "stretch" ] || [ $DISTRIBUTION = "buster" ]; then
        DEBIAN_FRONTEND=noninteractive \
            apt-get $INSTALL_OPTIONS install \
            $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | sed "s/libgdk-pixbuf-2.0-0/libgdk-pixbuf2.0-0/g;/libgdk-pixbuf-xlib-2.0-0/d" | tr "\n" " ") >>$OUTPUT 2>&1
    elif [ $DISTRIBUTION = "bionic" ]; then
        DEBIAN_FRONTEND=noninteractive \
            apt-get $INSTALL_OPTIONS install \
            $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | sed "s/libgdk-pixbuf-2.0-0/libgdk-pixbuf2.0-0/g;/libgdk-pixbuf-xlib-2.0-0/d;s/libjpeg62-turbo/libjpeg-turbo8/g;/libdeflate0/d" | tr "\n" " ") >>$OUTPUT 2>&1
    elif [ $DISTRIBUTION = "focal" ]; then
        DEBIAN_FRONTEND=noninteractive \
            apt-get $INSTALL_OPTIONS install \
            $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | sed "s/libgdk-pixbuf-2.0-0/libgdk-pixbuf2.0-0/g;/libgdk-pixbuf-xlib-2.0-0/d;s/libjpeg62-turbo/libjpeg-turbo8/g" | tr "\n" " ") >>$OUTPUT 2>&1
    elif [ $DISTRIBUTION = "jammy" ]; then
        DEBIAN_FRONTEND=noninteractive \
            apt-get $INSTALL_OPTIONS install \
            $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | sed "s/libjpeg62-turbo/libjpeg-turbo8/g;s/libwebp6/libwebp7/g" | tr "\n" " ") >>$OUTPUT 2>&1
    elif [ $DISTRIBUTION = "bookworm" ] || [ $DISTRIBUTION = "kali-rolling" ]; then
        DEBIAN_FRONTEND=noninteractive \
            apt-get $INSTALL_OPTIONS install \
            $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | sed "s/libwebp6/libwebp7/g;/libatk1.0-data/d;s/librest-0.7-0/librest-1.0-0/g" | tr "\n" " ") >>$OUTPUT 2>&1
    elif [ $DISTRIBUTION = "sid" ]; then
        DEBIAN_FRONTEND=noninteractive \
            apt-get $INSTALL_OPTIONS install \
            $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | sed "s/libwebp6/libwebp7/g;/libatk1.0-data/d" | tr "\n" " ") >>$OUTPUT 2>&1
    else
        DEBIAN_FRONTEND=noninteractive \
            apt-get $INSTALL_OPTIONS install \
            $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | tr "\n" " ") >>$OUTPUT 2>&1
    fi
fi
if [ -f /usr/share/applications/yad-icon-browser.desktop ]; then
    rm -f /usr/share/applications/yad-icon-browser.desktop
fi

if [ ! -L /usr/bin/gdk-pixbuf-query-loaders ]; then
    ln -s /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders /usr/bin/gdk-pixbuf-query-loaders
fi

cat <<EOF >/usr/lib/systemd/system/xorg.service
[Unit]
Description=X-Window
ConditionKernelCommandLine=!text
After=systemd-user-sessions.service

[Service]
ExecStart=/bin/su --login -c "/usr/bin/startx -- :0 vt7 -ac -nolisten tcp" $USER_NAME

EOF

if [ -d /etc/systemd/system ]; then
    mkdir -p /etc/systemd/system
fi
if [ ! -L /etc/systemd/system/display-manager.service ]; then
    ln -s /usr/lib/systemd/system/xorg.service /etc/systemd/system/display-manager.service
fi
if [ -L /etc/systemd/system/display-manager.service ]; then
    echo "Display manager link exists."
else
    exit 1
fi
