#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

language_to_array

if [ $PACKAGE_VARIANT = "minimum1" ]; then
    if [ $DISTRIBUTION_TYPE = "debian" ]; then
        echo 'deb http://download.opensuse.org/repositories/home:/stevenpusser/Debian_10/ /' | tee /etc/apt/sources.list.d/home:stevenpusser.list
        curl -fsSL https://download.opensuse.org/repositories/home:stevenpusser/Debian_10/Release.key | gpg --dearmor >/etc/apt/trusted.gpg.d/home_stevenpusser.gpg
    elif [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
        echo 'deb http://download.opensuse.org/repositories/home:/stevenpusser/xUbuntu_20.04/ /' | tee /etc/apt/sources.list.d/home:stevenpusser.list
        curl -fsSL https://download.opensuse.org/repositories/home:stevenpusser/xUbuntu_20.04/Release.key | gpg --dearmor >/etc/apt/trusted.gpg.d/home_stevenpusser.gpg
    fi

    # install packages
    pkg update
    pkg install palemoon

    if [[ $DESKTOP_ENVIRONMENT == *"xfce"* ]]; then
        if [ ! -d /etc/skel/.config/xfce4 ]; then
            mkdir -p /etc/skel/.config/xfce4
        fi
        if [ $PACKAGE_VARIANT = "minimum" ]; then
            cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=pcmanfm
WebBrowser=palemoon

EOF

        elif [ $PACKAGE_VARIANT = "standard" ] || [ $PACKAGE_VARIANT = "maximum" ] || [ $PACKAGE_VARIANT = "ultra" ]; then
            cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=palemoon

EOF
        fi
    fi
    rm -rf /usr/share/minios/html
elif [ $PACKAGE_VARIANT = "minimum2" ]; then
    pkg update
    pkg install epiphany-browser gstreamer1.0-plugins-bad
    if [[ $DESKTOP_ENVIRONMENT == *"xfce"* ]]; then
        if [ ! -d /etc/skel/.config/xfce4 ]; then
            mkdir -p /etc/skel/.config/xfce4
        fi
        if [ $PACKAGE_VARIANT = "minimum" ]; then
            cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=pcmanfm
WebBrowser=epiphany

EOF
        elif [ $PACKAGE_VARIANT = "standard" ] || [ $PACKAGE_VARIANT = "maximum" ] || [ $PACKAGE_VARIANT = "ultra" ]; then
            cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=epiphany

EOF
        fi
    fi
    cat <<EOF >/etc/skel/.config/mimeapps.list
[Default Applications]
inode/directory=xfce4-file-manager.desktop
x-scheme-handler/trash=xfce4-file-manager.desktop
x-scheme-handler/http=org.gnome.Epiphany.desktop
x-scheme-handler/https=org.gnome.Epiphany.desktop
text/html=org.gnome.Epiphany.desktop
application/xhtml+xml=org.gnome.Epiphany.desktop

[Added Associations]
inode/directory=xfce4-file-manager.desktop;
x-scheme-handler/trash=xfce4-file-manager.desktop;
x-scheme-handler/http=org.gnome.Epiphany.desktop;
x-scheme-handler/https=org.gnome.Epiphany.desktop;
text/html=org.gnome.Epiphany.desktop;
application/xhtml+xml=org.gnome.Epiphany.desktop;

EOF
    rm -rf /usr/share/minios/html
else
    pkg update

    # install packages
    if [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
        pkg install firefox
    elif [ $DISTRIBUTION_TYPE = "debian" ]; then
        pkg install firefox-esr
        if [ $LOCALE != "en_US" ]; then
            pkg install firefox-esr-l10n-${LNG[0]}
        fi
    fi

    if [[ $DESKTOP_ENVIRONMENT == *"xfce"* ]]; then
        if [ ! -d /etc/skel/.config/xfce4 ]; then
            mkdir -p /etc/skel/.config/xfce4
        fi
        if [ $PACKAGE_VARIANT = "minimum" ]; then
            cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=Thunar
WebBrowser=firefox

EOF
        elif [ $PACKAGE_VARIANT = "standard" ] || [ $PACKAGE_VARIANT = "maximum" ] || [ $PACKAGE_VARIANT = "ultra" ]; then
            cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=firefox

EOF
        fi
    fi

    echo "application/pdf=firefox-esr.desktop" >>/usr/share/applications/mimeapps.list
    if [ ${LNG[0]} = "en" ] || [ ${LNG[0]} = "ru" ]; then
        sed -i "s,about:welcome,file:///usr/share/minios/html/${LNG[0]}.html,g" /usr/share/firefox-esr/browser/defaults/preferences/firefox-branding.js
    else
        sed -i "s,about:welcome,file:///usr/share/minios/html/index.html,g" /usr/share/firefox-esr/browser/defaults/preferences/firefox-branding.js
    fi
    cat <<'EOF' >>/usr/share/firefox-esr/browser/defaults/preferences/firefox-branding.js

pref("browser.tabs.drawInTitlebar", true);
pref("general.smoothScroll", false);
pref("browser.compactmode.show", true);
pref("browser.uidensity", 1);

EOF
fi

if [ $DISTRIBUTION_TYPE = "debian" ] && [[ $DESKTOP_ENVIRONMENT == *"xfce"* ]]; then
    if [ $DISTRIBUTION = "buster" ] || [ $DISTRIBUTION = "stretch" ]; then
        sed -i "s/exo-open/env XDG_CURRENT_DESKTOP=XFCE exo-open/g" /usr/share/applications/exo-web-browser.desktop
    else
        sed -i "s/exo-open/env XDG_CURRENT_DESKTOP=XFCE exo-open/g" /usr/share/applications/xfce4-web-browser.desktop
    fi
    sed -i "s/exo-open/env XDG_CURRENT_DESKTOP=XFCE exo-open/g" /etc/skel/.config/xfce4/panel/launcher-5/WebBrowser.desktop
    if [ -f /usr/share/applications/firefox-esr.desktop ]; then
        sed -i "s,/usr/lib,env XDG_CURRENT_DESKTOP=XFCE /usr/lib,g" /usr/share/applications/firefox-esr.desktop
    fi
fi
