#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

$APT_CMD update $APT_OPTIONS &&
  $APT_CMD install $APT_OPTIONS xdg-utils

wget -c https://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/10920/wps-office_11.1.0.10920.XA_amd64.deb &&
  $APT_CMD install $APT_OPTIONS ./$(ls wps-office*.deb) &&
  rm -f ./$(ls wps-office*.deb)
