#!/bin/bash

CWD=$(dirname $(readlink -f $0))

NAME=fluxbox
VERSION=1.3.5

# first install stock version

apt-get $INSTALL_OPTIONS update >>$OUTPUT 2>&1

apt-get $INSTALL_OPTIONS install --no-install-recommends --yes \
    $NAME \
    feh \
    compton \
    volumeicon-alsa \
    murrine-themes \
    libnotify4 \
    scrot \
    adwaita-icon-theme-fake >>$OUTPUT 2>&1

(cd /rootcopy-install && cp --parents -afr * /)

if [ $DISTRIBUTION = "stretch" ]; then
    sed -i "s,chromium chromium-sandbox,chromium,g" /usr/bin/fbliveapp
    sed -i "s,connman-gtk,wicd-gtk,g" /etc/skel/.fluxbox/menu
fi

rm -f /usr/share/applications/5chromium.desktop
