#!/bin/bash

. /minioslib || exit 1

CWD=$(dirname $(readlink -f $0))

pkg update

pkg install mousepad pcmanfm galculator lxtask xarchiver xdg-utils libgconf-2-4

pkg install connman-gtk
if [ $LOCALE = "en_US" ]; then
    sed -i '114G' /etc/skel/.fluxbox/startup
    sed -i '115i# Launch connman, we no longer need the network manager icon in the application menu.' /etc/skel/.fluxbox/startup
    sed -i '116iexec connman-gtk &' /etc/skel/.fluxbox/startup
else
    sed -i '117G' /etc/skel/.fluxbox/startup
    sed -i '118i# Launch connman, we no longer need the network manager icon in the application menu.' /etc/skel/.fluxbox/startup
    sed -i '119iexec connman-gtk &' /etc/skel/.fluxbox/startup
fi

rm -f /usr/share/applications/6connman.desktop

rm -f /usr/share/applications/mousepad.desktop
rm -f /usr/share/applications/org.xfce.mousepad.desktop
rm -f /usr/share/applications/org.xfce.mousepad-settings.desktop
rm -f /usr/share/applications/qalculate-gtk.desktop
rm -f /usr/share/applications/galculator.desktop
rm -f /usr/share/applications/pcmanfm.desktop
rm -f /usr/share/applications/connman-gtk.desktop
rm -f /usr/share/applications/nm-applet.desktop
rm -f /usr/share/applications/nm-connection-editor.desktop
rm -f /usr/share/applications/xarchiver.desktop
rm -f /usr/share/applications/lxtask.desktop

if [ $LOCALE = "ru_RU" ]; then
    # Apps
    sed -i "s/Name=File Manager/Name=Менеджер файлов/g" /usr/share/applications/2pcmanfm.desktop
    sed -i "s/Name=Calculator/Name=Калькулятор/g" /usr/share/applications/3calculator.desktop
    sed -i "s/Name=Text editor/Name=Текстовый редактор/g" /usr/share/applications/4mousepad.desktop
    sed -i "s/Name=Net Manager/Name=Менеджер сети/g" /usr/share/applications/6connman.desktop
    sed -i "s/Name=Archiver/Name=Архиватор/g" /usr/share/applications/zxarchiver.desktop
    sed -i "s/Name=Task Manager/Name=Диспетчер задач/g" /usr/share/applications/zlxtask.desktop
elif [ $LOCALE = "es_ES" ]; then
    # Apps
    sed -i "s/Name=File Manager/Name=Gestor de archivos/g" /usr/share/applications/2pcmanfm.desktop
    sed -i "s/Name=Calculator/Name=Calculadora/g" /usr/share/applications/3calculator.desktop
    sed -i "s/Name=Text editor/Name=Editor de texto/g" /usr/share/applications/4mousepad.desktop
    sed -i "s/Name=Net Manager/Name=Gestor de redes/g" /usr/share/applications/6connman.desktop
    sed -i "s/Name=Archiver/Name=Archivador/g" /usr/share/applications/zxarchiver.desktop
    sed -i "s/Name=Task Manager/Name=Gestor de tareas/g" /usr/share/applications/zlxtask.desktop
fi
