#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

apt-get update >>$OUTPUT 2>&1

cat <<EOF >/etc/hosts
127.0.0.1       localhost
192.168.0.100       $LIVEKITNAME

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

EOF

apt-get install -y \
    proxmox-ve postfix open-iscsi >>$OUTPUT 2>&1
