#!/bin/bash

apt-get purge -y vim* grub* debconf-i18n installation-report >>$OUTPUT 2>&1
apt-get autoremove -y

if [[ $DISTRIBUTION_TYPE != "ubuntu" || $PACKAGE_VARIANT != "cloud" ]]; then
    cd /tmp
    apt -y update >>$OUTPUT 2>&1
    apt-get download acpi-support >>$OUTPUT 2>&1
    dpkg -x acpi-support*.deb /tmp/acpisupport >>$OUTPUT 2>&1
    if [ -L "/lib" ]; then
        mkdir -p /tmp/acpisupport/usr/lib
        (cd /tmp/acpisupport/lib && cp --parents -afr * /tmp/acpisupport/usr/lib)
        rm -rf /tmp/acpisupport/lib
    fi
    cd /tmp/acpisupport
    cp -aR * / >>$OUTPUT 2>&1
fi
