#!/bin/bash

apt-get remove --yes vim* grub* debconf-i18n installation-report  >>$OUTPUT 2>&1

cd /tmp
apt -y update >>$OUTPUT 2>&1
apt-get download acpi-support >>$OUTPUT 2>&1
dpkg -x acpi-support*.deb /tmp/acpisupport >>$OUTPUT 2>&1
cd /tmp/acpisupport
cp -aR * / >>$OUTPUT 2>&1