#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

echo "firmware-ipw2x00 firmware-ipw2x00/license/accepted boolean true" | debconf-set-selections
echo "b43-fwcutter b43-fwcutter/install-unconditional boolean true" | debconf-set-selections

apt-get update >>$OUTPUT 2>&1

# install packages
if [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
    if [ $DISTRIBUTION = "bionic" ] || [ $DISTRIBUTION = "focal" ] ||  [ $DISTRIBUTION = "jammy" ]; then
        apt-get install -y \
            linux-firmware firmware-b43-installer firmware-ath9k-htc >>$OUTPUT 2>&1
    else
        apt-get install $APT_OPTIONS
        #linux-firmware >>$OUTPUT 2>&1 #firmware-b43-installer
        #linux-image-generic-hwe-20.04 >>$OUTPUT 2>&1
        linux-image-generic >>$OUTPUT 2>&1
    fi
elif [ $DISTRIBUTION = "bullseye" ] && [ $KERNEL_ARCH = "amd64" ] && [ $KERNEL_TYPE = "pve" ]; then
    apt-get install -y \
        pve-kernel-5.15 >>$OUTPUT 2>&1
elif [ $DISTRIBUTION = "orel" ]; then
    apt-get install -y \
        linux-firmware >>$OUTPUT 2>&1
else
    # install packages
    if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
        if [ $DESKTOP_ENVIRONMENT = "slax" ] && [ $DISTRIBUTION = "bullseye" ]; then
            #Slax 11 no longer uses firmware-nonfree
            apt-get install -y \
                $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | sed "s/firmware-linux-nonfree//g" | tr "\n" " ") >>$OUTPUT 2>&1
        else
            apt-get install -y \
                $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | tr "\n" " ") >>$OUTPUT 2>&1
        fi
    fi
fi
