#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib

get_latest_package_url() {
    curl --silent "https://api.github.com/repos/$1/releases/latest" |      # Get latest release from GitHub api
        grep '"browser_download_url":' | grep "$DISTRIBUTION_ARCH.deb"\" | # Get tag line
        sed -E 's/.*"([^"]+)".*/\1/'                                       # Pluck JSON value
}

URL=$(get_latest_package_url Bin-Huang/chatbox)
FILENAME=$(basename $URL)

wget $URL &&
    apt-get update &&
    apt-get -y install ./$FILENAME
