#!/bin/bash

CWD=$(dirname $(readlink -f $0))

echo "wicd-daemon	wicd/users	multiselect	live" | debconf-set-selections

apt-get update >>$OUTPUT 2>&1
apt-get install --no-install-recommends --yes \
    mousepad \
    qalculate-gtk \
    pcmanfm \
    lxtask \
    xarchiver xdg-utils libgconf-2-4 >>$OUTPUT 2>&1

apt-mark manual pcmanfm libfm-gtk4

if [ $PACKAGE_VARIANT = "min" ]; then
    if [ $DISTRIBUTION != "bullseye" ] || [ $DISTRIBUTION != "bookworm" ] || [ $DISTRIBUTION != "kali-rolling" ]; then
        apt-get install --no-install-recommends --yes \
            wicd >>$OUTPUT 2>&1
    else
        apt-get install --no-install-recommends --yes \
            network-manager-gnome >>$OUTPUT 2>&1
        rm -f /usr/share/applications/6wicd.desktop
    fi
fi

if [ $PACKAGE_VARIANT = "std" ]; then
    apt-get install --no-install-recommends --yes \
        network-manager-gnome >>$OUTPUT 2>&1
    rm -f /usr/share/applications/6wicd.desktop
fi

(cd /rootcopy-install && cp --parents -afr * /)
