#!/bin/bash

CWD=$(dirname $(readlink -f $0))

echo "wicd-daemon	wicd/users	multiselect	live" | debconf-set-selections

apt-get update >>$OUTPUT 2>&1
apt-get install --no-install-recommends --yes \
    medit \
    qalculate-gtk \
    pcmanfm \
    lxtask \
    xarchiver xdg-utils libgconf-2-4 \
    wicd >>$OUTPUT 2>&1

(cd /rootcopy && cp --parents -afr * /)

chown live:live /home/live
chown -R live:live /home/live