#!/bin/bash

CWD=$(dirname $(readlink -f $0))

cd /

#rm -Rf /squashfs-root/root/.fluxbox >>$OUTPUT 2>&1
#rm -f /squashfs-root/root/.gtk-bookmarks >>$OUTPUT 2>&1

# we want to patch pcmanfm it to hide ugly root warning icon
# so we will recompile whole package

REBUILD=/tmp/pcmanfm-rebuild-$$

apt-get update >>$OUTPUT 2>&1
apt-get --yes build-dep pcmanfm >>$OUTPUT 2>&1

mkdir -p -m 0777 $REBUILD
cd $REBUILD

apt-get source pcmanfm >>$OUTPUT 2>&1

cd pcmanfm-1.3.1
dpkg-buildpackage -us -uc >>$OUTPUT 2>&1
patch -p1 < $CWD/patches/pcmanfm-slax.diff >>$OUTPUT 2>&1
make >>$OUTPUT 2>&1

strip --strip-unneeded src/pcmanfm >>$OUTPUT 2>&1
cp src/pcmanfm /squashfs-root/usr/bin >>$OUTPUT 2>&1

rm -f /squashfs-root/usr/share/applications/leafpad.desktop >>$OUTPUT 2>&1
rm -f /squashfs-root/usr/share/applications/qalculate-gtk.desktop >>$OUTPUT 2>&1
rm -f /squashfs-root/usr/share/applications/pcmanfm.desktop >>$OUTPUT 2>&1
rm -f /squashfs-root/usr/share/applications/wicd.desktop >>$OUTPUT 2>&1
rm -f /squashfs-root/usr/share/applications/lxtask.desktop >>$OUTPUT 2>&1

dir2sb /squashfs-root /04-apps.sb >>$OUTPUT 2>&1
