#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

pkg update

# install packages
if [ -f $SCRIPT_DIR/package.list ]; then
    install_packages -l $SCRIPT_DIR/package.list
fi

if [ -f /usr/share/applications/yad-icon-browser.desktop ]; then
    rm -f /usr/share/applications/yad-icon-browser.desktop
fi

if grep -q "imagemagick" $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    rm -f /usr/share/applications/display-im6.q16.desktop
fi

if grep -q "vlc" $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    if [ "$LOCALE" != "en_US" ]; then
        pkg install vlc-l10n
    fi
fi
