#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
#set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
APP="virtualbox"
APP_NAME="VirtualBox"
APP_GROUP="vboxusers"

apt-get update >>$OUTPUT 2>&1
apt-get install -y fasttrack-archive-keyring >>$OUTPUT 2>&1
echo "deb http://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib" >/etc/apt/sources.list.d/fasttrack.list
echo "deb http://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib" >>/etc/apt/sources.list.d/fasttrack.list
apt-get update >>$OUTPUT 2>&1
if [ $KERNEL_AUFS = "true" ] && [ $KERNEL_BPO != "true" ]; then
    wget https://github.com/minios-linux/aufs-kernel/releases/download/5.10.127/linux-headers-5.10.127_5.10.127-1_$DISTRIBUTION_ARCH.deb
    apt-get install -y ./linux-headers-5.10.127_5.10.127-1_$DISTRIBUTION_ARCH.deb >>$OUTPUT 2>&1
    rm ./linux-headers-5.10.127_5.10.127-1_$DISTRIBUTION_ARCH.deb
else
    apt-get install linux-headers-$DISTRIBUTION_ARCH  >>$OUTPUT 2>&1
fi
apt-get install -y virtualbox-qt >>$OUTPUT 2>&1

cat <<EOF >/usr/bin/$APP-allowuser.sh
#!/bin/bash
if ! grep $APP_GROUP group | grep \$(id -nu 1000) >/dev/null; then
    usermod -a -G $APP_GROUP $(id -nu 1000)
fi
EOF
chmod +x /usr/bin/$APP-allowuser.sh
cat <<EOF >/usr/lib/systemd/system/$APP-allowuser.service
[Unit]
Description=Allow user to use $APP_NAME
#After=network.target

[Service]
Type=oneshot
ExecStart=/usr/bin/$APP-allowuser.sh
RemainAfterExit=true
ExecStop=
StandardOutput=journal

[Install]
WantedBy=multi-user.target
EOF
systemctl enable $APP-allowuser.service >>$OUTPUT 2>&1

PACKAGE="virtualbox"
echo "PACKAGE=$PACKAGE" >/.package
echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g' | sed 's/:/-/g')" >>/.package
