#!/bin/bash

CWD=$(dirname $(readlink -f $0))

NAME=fluxbox
VERSION=1.3.5

# first install stock version

apt-get update >>$OUTPUT 2>&1
apt-get install --no-install-recommends --yes \
    $NAME \
    feh \
    compton \
    volumeicon-alsa \
    murrine-themes \
    libnotify4 \
    scrot >>$OUTPUT 2>&1

(cd /rootcopy && cp --parents -afr * /)

chown live.users /home/live
chown -R live.users /home/live/.gtkrc-2.0
chown -R live.users /home/live/.config

chown -R live.users /home/live