#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

echo "keyboard-configuration	keyboard-configuration/variant	select	English (US)" | debconf-set-selections

pkg update

# install packages
if [ DESKTOP_ENVIRONMENT = "astra-fly" ]; then
    pkg install \
        xorg-all-main
elif [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
    pkg install \
        $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | tr "\n" " ")
fi

if [ $PACKAGE_VARIANT = "maximum" ] || [ $PACKAGE_VARIANT = "ultra" ]; then
    if [ $DISTRIBUTION = "stretch" ] || [ $DISTRIBUTION = "buster" ] || [ $DISTRIBUTION = "bullseye" ]; then
        if [ $DISTRIBUTION = "buster" ]; then
            apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 276ECD5CEF864D8F
        fi
        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F942E0D4E1C726CD
        cat <<EOF >/etc/apt/sources.list.d/mx.list
# MX Community Main and Test Repos
deb http://mxrepo.com/mx/repo/ $DISTRIBUTION main non-free
#deb http://mxrepo.com/mx/testrepo/ $DISTRIBUTION test

#ahs hardware stack repo
deb http://mxrepo.com/mx/repo/ $DISTRIBUTION ahs
EOF
        pkg update
        pkg install virtualbox-guest-x11
        rm /etc/apt/sources.list.d/mx.list
    fi
fi

if [ $DESKTOP_ENVIRONMENT = "flux" ]; then
    USER_NAME="root"
fi
cat <<EOF >/usr/lib/systemd/system/xorg.service
[Unit]
Description=X-Window
ConditionKernelCommandLine=!text
After=systemd-user-sessions.service

[Service]
ExecStart=/bin/su --login -c "/usr/bin/startx -- :0 vt7 -ac -nolisten tcp" $USER_NAME

EOF

if [ -d /etc/systemd/system ]; then
    mkdir -p /etc/systemd/system
fi

if [ -L /etc/systemd/system/display-manager.service ]; then
    echo "Display manager link exists."
else
    ln -s /usr/lib/systemd/system/xorg.service /etc/systemd/system/display-manager.service
fi
