#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor >packages.microsoft.gpg
install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" >/etc/apt/sources.list.d/microsoft-edge.list'
rm -f packages.microsoft.gpg

# install packages
$APT_CMD update >>$OUTPUT 2>&1 &&
    $APT_CMD install $APT_OPTIONS microsoft-edge-stable >>$OUTPUT 2>&1

if [ ! -d /etc/edge.d/ ]; then
    mkdir /etc/edge.d
fi
echo 'export EDGE_FLAGS="$EDGE_FLAGS --disk-cache-dir=/dev/null --disk-cache-size=1"' >>/etc/edge.d/default-flags

if [[ $DESKTOP_ENVIRONMENT == *"xfce"* ]]; then
    if [ $PACKAGE_VARIANT = "min" ]; then
        cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=pcmanfm
WebBrowser=microsoft-edge

EOF
    elif [ $PACKAGE_VARIANT = "std" ]; then
        cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=microsoft-edge

EOF
    fi
fi
