#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

apt-get $INSTALL_OPTIONS update >>$OUTPUT 2>&1

# install packages
if [ -f $SCRIPT_DIR/package.list ]; then
    DEBIAN_FRONTEND=noninteractive \
        apt-get $INSTALL_OPTIONS install \
        $(grep -vE "^\s*#" $SCRIPT_DIR/package.list | tr "\n" " ") >>$OUTPUT 2>&1
fi
