#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

if [ $DISTRIBUTION_TYPE = "debian" ]; then
    FIREFOX_BRANDING="/usr/share/firefox-esr/browser/defaults/preferences/firefox-branding.js"
elif [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
    FIREFOX_BRANDING="/etc/firefox/syspref.js"
fi

language_to_array

pkg update

# install packages
if [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
    if [ $DISTRIBUTION = "jammy" ] || [ $DISTRIBUTION = "lunar" ]; then
        pkg install software-properties-common
        add-apt-repository ppa:mozillateam/ppa
        cat <<EOF >/etc/apt/preferences.d/mozilla-firefox
Package: *
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1001
EOF
    fi
    pkg install \
        firefox
    if [ $LOCALE != "en_US" ]; then
        pkg install \
            firefox-locale-${LNG[0]}
    fi
elif [ $DISTRIBUTION_TYPE = "debian" ]; then
    pkg install \
        firefox-esr
    if [ $LOCALE = "es_ES" ]; then
        pkg install \
            firefox-esr-l10n-es-es
    elif [ $LOCALE != "en_US" ]; then
        pkg install \
            firefox-esr-l10n-${LNG[0]}
    fi
fi

if [[ $DESKTOP_ENVIRONMENT == *"xfce"* ]] && [ $PACKAGE_VARIANT != "puzzle" ]; then
    if [ ! -d /etc/skel/.config/xfce4 ]; then
        mkdir -p /etc/skel/.config/xfce4
    fi

    if [ $PACKAGE_VARIANT = "minimum" ]; then
        cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=Thunar
WebBrowser=firefox

EOF
    elif [ $PACKAGE_VARIANT = "standard" ] || [ $PACKAGE_VARIANT = "maximum" ] || [ $PACKAGE_VARIANT = "ultra" ]; then
        cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=firefox

EOF
    fi
fi

echo "application/pdf=firefox-esr.desktop" >>/usr/share/applications/mimeapps.list

if [ $DISTRIBUTION_TYPE = "debian" ]; then
    if [ ${LNG[0]} = "en" ] || [ ${LNG[0]} = "ru" ] || [ ${LNG[0]} = "es" ]; then
        sed -i "s,about:welcome,file:///usr/share/minios/html/${LNG[0]}.html,g" $FIREFOX_BRANDING
    else
        sed -i "s,about:welcome,file:///usr/share/minios/html/index.html,g" $FIREFOX_BRANDING
    fi
elif [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
    if [ ${LNG[0]} = "en" ] || [ ${LNG[0]} = "ru" ] || [ ${LNG[0]} = "es" ]; then
        cat <<EOF >>$FIREFOX_BRANDING

pref("startup.homepage_welcome_url", "file:///usr/share/minios/html/${LNG[0]}.html");
EOF
    else
        cat <<EOF >>$FIREFOX_BRANDING

pref("startup.homepage_welcome_url", "file:///usr/share/minios/html/index.html");
EOF
    fi
fi
cat <<'EOF' >>$FIREFOX_BRANDING

pref("browser.tabs.drawInTitlebar", true);
pref("general.smoothScroll", false);
pref("browser.compactmode.show", true);
pref("browser.uidensity", 1);

EOF

if [ $DISTRIBUTION_TYPE = "debian" ]; then
    sed -i "s,/usr/lib,env XDG_CURRENT_DESKTOP=XFCE /usr/lib,g" /usr/share/applications/firefox-esr.desktop
fi

if [ $DISTRIBUTION_TYPE = "debian" ]; then
    PACKAGE="firefox-esr"
elif [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
    PACKAGE="firefox"
fi
echo "PACKAGE=$PACKAGE" >/.package
echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g' | sed 's/:/-/g')" >>/.package
