#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

#export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true

debconf-set-selections preseed.txt

# install packages
if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
    $APT_CMD update >>$OUTPUT 2>&1 &&
        $APT_CMD install $APT_OPTIONS locales >>$OUTPUT 2>&1
fi

dpkg-reconfigure locales >>$OUTPUT 2>&1
dpkg-reconfigure keyboard-configuration >>$OUTPUT 2>&1
dpkg-reconfigure tzdata >>$OUTPUT 2>&1
