#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

pkg update

# install packages
#!!!the name of the main application of the module must be specified in the first line of package.list!!!
if [ -f $SCRIPT_DIR/package.list ]; then
    install_packages --package-list "$SCRIPT_DIR/package.list"
    PACKAGE=$(head -n 1 $SCRIPT_DIR/package.list)
    echo "PACKAGE=$PACKAGE" >/.package
    echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g' | sed 's/:/-/g')" >>/.package
fi

if grep -q 'obs-studio' $SCRIPT_DIR/package.list >/dev/null 2>&1; then
    if [ -f /usr/share/icons/hicolor/256x256/apps/com.obsproject.Studio.png ]; then
        mv /usr/share/icons/hicolor/256x256/apps/com.obsproject.Studio.png /usr/share/pixmaps/
    elif [ -f /usr/share/icons/hicolor/256x256/apps/obs.png ]; then
        mv /usr/share/icons/hicolor/256x256/apps/obs.png /usr/share/pixmaps/
    fi
fi
