#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

#export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true

#debconf-set-selections /preseed.txt

# install packages
apt-get update >>$OUTPUT 2>&1 &&
    apt-get install --reinstall -y locales >>$OUTPUT 2>&1

dpkg-reconfigure locales >>$OUTPUT 2>&1
dpkg-reconfigure keyboard-configuration >>$OUTPUT 2>&1
dpkg-reconfigure tzdata >>$OUTPUT 2>&1

if [ ! -d /etc/systemd/system/console-setup.service.d ]; then
    mkdir -p /etc/systemd/system/console-setup.service.d
fi
cat >/etc/systemd/system/console-setup.service.d/override.conf <<EOF
[Unit]
After=systemd-tmpfiles-setup.service
EOF
