#!/bin/bash

# distribution type
# тип дистрибутива
DISTRIBUTION_TYPE=debian

# distribution
# дистрибутив
DISTRIBUTION=buster

# distribution arch
# архитектура дистрибутива
DISTRIBUTION_ARCH=amd64

# окружение рабочего стола
# desktop environment
DESKTOP_ENVIRONMENT=mediaplayer

# system variant, indicates the used list of packages in modules
# вариант системы, указывает на используемый список пакетов в модулях
PACKAGE_VARIANT=minimal

# тип сжатия
# compresssion type
COMP_TYPE=xz

# bootstrap variant (used to build Ubuntu)
# вариант bootstrap (используется для сборки Ubuntu)
DISTRIBUTION_VARIANT="minbase"

# if core, then executing scripts will not build modules.
# если core, то выполнение скриптов не будет собирать модули.
#SYSTEM_TYPE="core"

# path of the log file
# путь файла лога
LOGPATH="/var/log"

# default is output to stdout. you can use OUTPUT="$LOGPATH/$LIVEKITNAME.log" if you want to route events to log file.
# по умолчанию выводится на стандартный вывод. вы можете использовать OUTPUT="$LOGPATH/$LIVEKITNAME.log", если хотите направлять события в файл журнала.
OUTPUT="/dev/stdout"
#OUTPUT="$LOGPATH/$LIVEKITNAME.log"
#OUTPUT="/dev/null"

# if = "1", creates a second iso with a constant filename
# если ="1", создаёт второй iso с постоянным именем файла
BUILD_TEST_ISO="1"

# удаляет старые файлы iso для данного типа сборки
REMOVE_OLD_ISO="1"

# if = "1", creates a copy of minios-live in chroot /opt
# если ="1", создаёт копию minios-live в chroot /opt
DEV_SYSTEM="0"

# if ="1", creates backup in parent folder
# если ="1", создаёт резервную копию в родительской папке
CREATE_BACKUP="0"

DEBIAN_FRONTEND_TYPE="noninteractive"
#DEBIAN_FRONTEND_TYPE="dialog"
#DEBIAN_FRONTEND_TYPE="text"

APT_CMD="apt-get"
APT_OPTIONS="-y"

# iso type
# тип iso
BOOT_TYPE="hybrid"
#BOOT_TYPE=""

# union type used to build the system
# тип union, используемый для сборки системы
UNION_BUILD_TYPE="overlayfs"
#UNION_BUILD_TYPE="aufs"

# Used when assigned to the ISO name when building Minios-Live
SYSTEMNAME="MiniOS"

# using a ready-made bootstrap file during installation. If absent, then it is downloaded and packaged. Subsequent builds unpack the existing bootstrap.
# использование готового файла bootstrap при установке. Если отсутствует, то скачивается и упаковывается. При последующих сборках распаковывается существующий файл bootstrap.
USE_BOOTSTRAP="1"

# using a ready-made rootfs file during installation. If absent, then it is downloaded and packaged. Subsequent builds will unpack the existing rootfs file.
# использование готового файла rootfs при установке. Если отсутствует, то скачивается и упаковывается. При последующих сборках распаковывается существующий файл rootfs.
USE_ROOTFS="1"

# deleting sources after building
# удаление исходников после сборки
REMOVE_SOURCES="false"