#!/bin/bash

: ${BUILD_SCRIPTS:="linux-live"}

export PATH=.:./tools:../tools:/usr/sbin:/usr/bin:/sbin:/bin:/

. /minioslib || exit 1
. /minios_build.conf || exit 1
KERNEL="${KERNEL:-$(file /boot/vmlinuz-* | grep -oP 'version \K[^\s]+')}"

console_colors

# build initramfs image
if [ "${VERBOSITY_LEVEL}" -ge 1 ]; then
	echo -e "   ${YELLOW}KERNEL=${KERNEL}${ENDCOLOR}"
	echo -e "   ${YELLOW}KERNEL_BPO=${KERNEL_BPO}${ENDCOLOR}"
	echo -e "   ${YELLOW}KERNEL_AUFS=${KERNEL_AUFS}${ENDCOLOR}"
fi

cd /$BUILD_SCRIPTS/initramfs/livekit-mos
chmod 755 ./mkinitrfs

TMPFILE=$(mktemp)
./mkinitrfs -k "$KERNEL" -dm >"$TMPFILE" 2>&1 &
MKINIT_PID=$!
spinner "${MKINIT_PID}" "Building initramfs image"
wait "${MKINIT_PID}"

INITRAMFS=$(tail -n 1 "$TMPFILE" | xargs)
rm "$TMPFILE"

if [ -n "$INITRAMFS" ]; then
	mv "$INITRAMFS" /boot/initrfs.img
fi
