#!/bin/bash

: ${BUILD_SCRIPTS_DIR:="linux-live"}

export PATH=.:./tools:../tools:/usr/sbin:/usr/bin:/sbin:/bin:/

if [ -f /$BUILD_SCRIPTS_DIR/container_config ]; then
	. /$BUILD_SCRIPTS_DIR/container_config || exit 1
else
	. /$BUILD_SCRIPTS_DIR/config || exit 1
fi
. /minioslib || exit 1
. /minios-build.conf || exit 1

console_colors

# build initramfs image
echo -e "=====> ${CYAN}Building intramfs image ...${ENDCOLOR}"
echo -e "=====  ${YELLOW}KERNEL=${KERNEL}${ENDCOLOR}"
echo -e "=====  ${YELLOW}KERNEL_BPO=${KERNEL_BPO}${ENDCOLOR}"
echo -e "=====  ${YELLOW}KERNEL_AUFS=${KERNEL_AUFS}${ENDCOLOR}"

cd /$BUILD_SCRIPTS_DIR/initramfs/livekit-mos
chmod 755 ./mkinitrfs
INITRAMFS=$(./mkinitrfs "$KERNEL")
if [ -n "$INITRAMFS" ]; then
	mv "$INITRAMFS" /boot/initrfs.img
fi
