#!/bin/bash

export PATH=.:./tools:../tools:/usr/sbin:/usr/bin:/sbin:/bin:/

if [ -f /linux-live/container_buildconfig ]; then
	. /linux-live/container_buildconfig || exit 1
else
	. /linux-live/buildconfig || exit 1
fi
. /linux-live/kernelconfig || exit 1
. /linux-live/minioslib || exit 1
if [ -z $KERNEL ]; then
	. /miniosbuild.conf || exit 1
fi

console_colors

# build initramfs image
echo -e "=====> ${CYAN}Building intramfs image ...${ENDCOLOR}"
echo -e "=====  ${YELLOW}KERNEL=$KERNEL${ENDCOLOR}"
echo -e "=====  ${YELLOW}KERNEL_BPO=$KERNEL_BPO${ENDCOLOR}"
echo -e "=====  ${YELLOW}KERNEL_AUFS=$KERNEL_AUFS${ENDCOLOR}"

cd /linux-live/initramfs/livekit-mos
chmod 755 ./initramfs_create
INITRAMFS=$(./initramfs_create $KERNEL)
if [ "$INITRAMFS" != "" ]; then
	mv "$INITRAMFS" /boot/initrfs.img
fi
