#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SET_E=""
SET_U=""

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
BUILD_SCRIPTS_DIR="$SCRIPT_DIR"
BUILD_CONF="$SCRIPT_DIR/build.conf"

. "$SCRIPT_DIR/minioslib" || exit 1
. "$BUILD_CONF" || exit 1

# =============   main  ================

common_variables

console_colors

allow_root_only

install_core_packages
