#!/bin/bash

##########################################

if [ $DISTRIBUTION_ARCH = "amd64" ]; then
    KERNEL_ARCH="amd64"
elif [ $DISTRIBUTION_ARCH = "i386-pae" ]; then
    KERNEL_ARCH="686-pae"
elif [ $DISTRIBUTION_ARCH = "i386" ]; then
    KERNEL_ARCH="686"
elif [ $DISTRIBUTION_ARCH = "arm64" ]; then
    KERNEL_ARCH="arm64"
fi

if [ $PACKAGE_VARIANT = "pve" ]; then
    KERNEL_TYPE="pve"
elif [ $PACKAGE_VARIANT = "pve" ] && [ $DISTRIBUTION_ARCH != "amd64" ]; then
    echo "You can't build PVE with i386"
    exit 0
fi
if [ $KERNEL_TYPE = "pve" ] && [ $DISTRIBUTION_ARCH != "amd64" ]; then
    KERNEL_TYPE = "default"
fi

if [ $KERNEL_AUFS = "true" ] && ! { [ $DISTRIBUTION = "stretch" ] || [ $DISTRIBUTION = "buster" ] || [ $DISTRIBUTION = "orel" ]; }; then
    if [ $KERNEL_BPO = "true" ]; then
        KERNEL_VERSION="6.0"
    else
        KERNEL_VERSION="5.10"
    fi
    if [ $KERNEL_TYPE = "default" ]; then
        KERNEL=$(apt-cache depends linux-image-$KERNEL_VERSION-mos-$KERNEL_ARCH | grep 'Depends' | sed 's/  Depends: //g' | sed 's/linux-image-//')
    else
        KERNEL=$(apt-cache depends linux-image-$KERNEL_VERSION-mos-$KERNEL_TYPE-$KERNEL_ARCH | grep 'Depends' | sed 's/  Depends: //g' | sed 's/linux-image-//')
    fi
elif [ $KERNEL_TYPE = "none" ]; then
    KERNEL=""
elif [ -f /usr/bin/dpkg-query ] 2>/dev/null; then
    KERNEL=$(dpkg-query -W -f='${binary:Package}\n' linux-image-* 2>/dev/null | head -n 1 | sed 's/linux-image-//')
    KERNEL_VERSION=""
else
    KERNEL=$(uname -r)
    KERNEL_VERSION=""
fi
if echo $KERNEL | grep -q 'pve'; then
    KERNEL=${KERNEL::-6}
fi
