#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

echo "keyboard-configuration	keyboard-configuration/variant	select	English (US)" | debconf-set-selections

$APT_CMD update >>$OUTPUT 2>&1

# install packages
if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
    $APT_CMD install $APT_OPTIONS \
        $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | tr "\n" " ") >>$OUTPUT 2>&1
fi

if [ $DISTRIBUTION_VARIANT != "minimal" ]; then
    if [ $DISTRIBUTION = "stretch" ]; then
        wget -c http://ftp.debian.org/debian/pool/main/f/fonts-noto-color-emoji/fonts-noto-color-emoji_0~20180810-1_all.deb
        dpkg -i ./fonts-noto-color-emoji_0~20180810-1_all.deb
        rm -f ./fonts-noto-color-emoji_0~20180810-1_all.deb
    else
        $APT_CMD install $APT_OPTIONS fonts-noto-color-emoji
    fi
fi

cat <<EOF >/usr/lib/systemd/system/xorg.service
[Unit]
Description=X-Window
ConditionKernelCommandLine=!text
After=systemd-user-sessions.service

[Service]
ExecStart=/bin/su --login -c "/usr/bin/startx -- :0 vt7 -ac -nolisten tcp" live

EOF

ln -s /usr/lib/systemd/system/xorg.service /etc/systemd/system/display-manager.service
