#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

if [ $PACKAGE_VARIANT = "minimum" ]; then
    if [ $DISTRIBUTION_TYPE = "debian" ]; then
        echo 'deb http://download.opensuse.org/repositories/home:/stevenpusser/Debian_10/ /' | tee /etc/apt/sources.list.d/home:stevenpusser.list
        curl -fsSL https://download.opensuse.org/repositories/home:stevenpusser/Debian_10/Release.key | gpg --dearmor >/etc/apt/trusted.gpg.d/home_stevenpusser.gpg
    elif [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
        echo 'deb http://download.opensuse.org/repositories/home:/stevenpusser/xUbuntu_20.04/ /' | tee /etc/apt/sources.list.d/home:stevenpusser.list
        curl -fsSL https://download.opensuse.org/repositories/home:stevenpusser/xUbuntu_20.04/Release.key | gpg --dearmor >/etc/apt/trusted.gpg.d/home_stevenpusser.gpg
    fi

    # install packages
    apt-get update >>$OUTPUT 2>&1 &&
        apt-get install -y palemoon >>$OUTPUT 2>&1

    if [[ $DESKTOP_ENVIRONMENT == *"xfce"* ]]; then
        if [ ! -d /etc/skel/.config/xfce4 ]; then
            mkdir -p /etc/skel/.config/xfce4
        fi
        if [ $PACKAGE_VARIANT = "minimum" ]; then
            cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=pcmanfm
WebBrowser=palemoon

EOF

        elif [ $PACKAGE_VARIANT = "standard" ] || [ $PACKAGE_VARIANT = "maximum" ]; then
            cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=palemoon

EOF
        fi
    fi
else
    apt-get update >>$OUTPUT 2>&1

    # install packages
    if [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
        apt-get install -y \
            firefox >>$OUTPUT 2>&1
    elif [ $DISTRIBUTION_TYPE = "debian" ]; then
        apt-get install -y \
            firefox-esr >>$OUTPUT 2>&1
    fi

    if [[ $DESKTOP_ENVIRONMENT == *"xfce"* ]]; then
        if [ ! -d /etc/skel/.config/xfce4 ]; then
            mkdir -p /etc/skel/.config/xfce4
        fi
        if [ $PACKAGE_VARIANT = "minimum" ]; then
            cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=pcmanfm
WebBrowser=firefox

EOF
        elif [ $PACKAGE_VARIANT = "standard" ] || [ $PACKAGE_VARIANT = "maximum" ]; then
            cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=firefox

EOF
        fi
    fi
fi
