#!/bin/bash

apt-get autoremove -y $APT_OPTIONS2 \
    software-properties-common gnupg >>$OUTPUT 2>&1

#rm -Rf /usr/share/icons/Adwaita/256x256 >>$OUTPUT 2>&1
#rm -Rf /usr/share/icons/Adwaita/512x512 >>$OUTPUT 2>&1
#rm -Rf /usr/share/icons/hicolor/256x256 >>$OUTPUT 2>&1
#rm -Rf /usr/share/icons/hicolor/512x512 >>$OUTPUT 2>&1
#rm -Rf /usr/share/icons/gnome/256x256 >>$OUTPUT 2>&1
