#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
BROWSER="opera"
BROWSER_NAME="Opera"
BROWSER_EXECUTABLE="opera"
BROWSER_MODULE_NUMBER="5"

$APT_CMD update >>$OUTPUT 2>&1 &&
    $APT_CMD install $APT_OPTIONS gnupg apt-transport-https >>$OUTPUT 2>&1

wget -qO- https://deb.opera.com/archive.key | gpg --dearmor | dd of=/usr/share/keyrings/opera-browser.gpg
echo "deb [signed-by=/usr/share/keyrings/opera-browser.gpg] https://deb.opera.com/opera-stable/ stable non-free" | sudo dd of=/etc/apt/sources.list.d/opera-archive.list

# install packages
$APT_CMD update >>$OUTPUT 2>&1 &&
    $APT_CMD install $APT_OPTIONS opera-stable >>$OUTPUT 2>&1

if [ ! -d /etc/$BROWSER.d/ ]; then
    mkdir /etc/$BROWSER.d
fi
echo "export ${BROWSER^^}_FLAGS=\"${BROWSER^^}_FLAGS --disk-cache-dir=/dev/null --disk-cache-size=1\"" >>/etc/$BROWSER.d/default-flags

if [[ $DESKTOP_ENVIRONMENT == *"xfce"* ]]; then
    if [ $PACKAGE_VARIANT = "minimum" ]; then
        cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xterm
FileManager=pcmanfm
WebBrowser=$BROWSER_EXECUTABLE

EOF
    elif [ $PACKAGE_VARIANT = "standard" ] || [ $PACKAGE_VARIANT = "maximum" ]; then
        cat <<EOF >/etc/skel/.config/xfce4/helpers.rc
TerminalEmulator=xfce4-terminal
FileManager=Thunar
WebBrowser=$BROWSER_EXECUTABLE

EOF
    fi
fi

if [ -f /usr/bin/fbliveapp ]; then
    cat <<EOF >/usr/bin/fblive-add-$BROWSER.sh
#!/bin/bash
if [ -f /var/cache/fblive-add-$BROWSER.addon ]; then
    if ! grep $BROWSER_EXECUTABLE /usr/bin/fbliveapp >/dev/null; then
        cp /usr/bin/fbliveapp /usr/bin/fbliveapp.$BROWSER.bak
        sed -i "/shift/ e cat /var/cache/fblive-add-$BROWSER.addon" /usr/bin/fbliveapp
        #rm /var/cache/fblive-add-$BROWSER.addon
        rm /usr/share/applications/$BROWSER.desktop
    fi
fi

EOF
    chmod +x /usr/bin/fblive-add-$BROWSER.sh
    cat <<EOF >/usr/lib/systemd/system/fblive-add-$BROWSER.service
[Unit]
Description=Adding $BROWSER_NAME to fbliveapp
#After=network.target

[Service]
Type=oneshot
ExecStart=/usr/bin/fblive-add-$BROWSER.sh
RemainAfterExit=true
ExecStop=
StandardOutput=journal

[Install]
WantedBy=multi-user.target

EOF
    cat <<EOF >/usr/share/applications/$BROWSER_MODULE_NUMBER$BROWSER.desktop
[Desktop Entry]
Version=1.0
Name=$BROWSER_NAME
GenericName=$BROWSER_NAME
Exec=fbliveapp $BROWSER_EXECUTABLE %U
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=$BROWSER.png
Categories=Network;WebBrowser;
MimeType=audio/*;image/*;video/*;application/pdf;application/x-pdf;text/html;text/xml;application/xhtml_xml;application/x-mimearchive;x-scheme-handler/http;x-scheme-handler/https;
StartupWMClass=$BROWSER
StartupNotify=true

EOF
    cat <<EOF >/var/cache/fblive-add-$BROWSER.addon
if [ "\$1" = "$BROWSER_EXECUTABLE" ]; then
   NAME="$BROWSER_NAME"
   EXECUTABLE="/usr/bin/$BROWSER_EXECUTABLE"
   GUEST=true
fi

EOF
    systemctl enable fblive-add-$BROWSER.service >>$OUTPUT 2>&1
fi
