#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# install packages
if [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
        apt-add-repository ppa:remmina-ppa-team/remmina-next
        cat <<EOF >/etc/apt/preferences.d/remmina-next
Package: *
Pin: release o=LP-PPA-remmina-ppa-team-remmina-next
Pin-Priority: 1001
EOF
fi
#!!!the name of the main application of the module must be specified in the first line of package.list!!!
if [ -f $SCRIPT_DIR/package.list ]; then
        /install_packages -l "$SCRIPT_DIR/package.list" -c "${SCRIPT_DIR}/minios-build.conf" "$SCRIPT_DIR/package.list"

        PACKAGE=$(head -n 1 $SCRIPT_DIR/package.list)
        echo "PACKAGE=$PACKAGE" >/.package
        echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g' | sed 's/:/-/g')" >>/.package
fi
