#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

#
function language_to_array() {
    local IFS
    IFS="_"
    LANG=($LOCALE)
}
language_to_array

apt-get update >>$OUTPUT 2>&1

# install packages
if [ $DISTRIBUTION = "jammy" ]; then
    DEBIAN_FRONTEND=noninteractive \
        apt-add-repository ppa:remmina-ppa-team/remmina-next >>$OUTPUT 2>&1
    cat <<EOF >/etc/apt/preferences.d/remmina-next
Package: *
Pin: release o=LP-PPA-remmina-ppa-team-remmina-next
Pin-Priority: 1001
EOF
fi
#!!!the name of the main application of the module must be specified in the first line of package.list!!!
if [ -f $SCRIPT_DIR/package.list ]; then
    DEBIAN_FRONTEND=noninteractive \
        apt-get install -y \
        $(grep -vE "^\s*#" $SCRIPT_DIR/package.list | tr "\n" " ") >>$OUTPUT 2>&1
    PACKAGE=$(head -n 1 $SCRIPT_DIR/package.list)
    echo "PACKAGE=$PACKAGE" >/.package
    echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g' | sed 's/:/-/g')" >>/.package
fi
