#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

wget -qO - https://shop.softmaker.com/repo/linux-repo-public.key | apt-key add -
echo "deb https://shop.softmaker.com/repo/apt stable non-free" > /etc/apt/sources.list.d/softmaker.list

# install packages
apt-get update >>$OUTPUT 2>&1 &&
    apt-get install -y \
        softmaker-freeoffice-2021 >>$OUTPUT 2>&1

PACKAGE="softmaker-freeoffice-2021"
echo "PACKAGE=$PACKAGE" >/.package
echo "VERSION=$(dpkg -s $PACKAGE | grep Version | egrep -o '[0-9]*[0-9]')" >>/.package