#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

cd $SCRIPT_DIR
wget https://ftp2.minios.dev/cts-4.0.0-104.ks1_$DISTRIBUTION_ARCH.deb
# install packages
pkg update
pkg install $SCRIPT_DIR/cts-4.0.0-104.ks1_$DISTRIBUTION_ARCH.deb libnss3-tools iptables
rm -f $SCRIPT_DIR/cts-4.0.0-104.ks1_$DISTRIBUTION_ARCH.deb

rm -f /etc/cts/.csum
rm -f /etc/cts/filelist.current
touch /etc/cts/filelist.current
/usr/share/cts/bin/ctsic compute
