#!/bin/bash
# Usage:    container_build_run [DISTRIBUTION] [DESKTOP_ENVIRONMENT] [PACKAGE_VARIANT] [DISTRIBUTION_ARCH] [INITRD_TYPE] [KERNEL_TYPE] [KERNEL_BPO] [KERNEL_AUFS] [KERNEL_BUILD_DKMS] [CONP_TYPE] [LOCALE] [TIMEZONE]
# Example:  container_build_run bookworm       xfce                  standard          amd64               livekit       default       true         true          true             zstd        en_US    Etc/UTC

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
PARENT_DIR="$(dirname $SCRIPT_DIR)"

. $PARENT_DIR/linux-live/minioslib || exit 1
SCRIPT_DIR=$PARENT_DIR

container_engine="docker"

# English
container_build_run bookworm flux minimum amd64 livekit-mos default false true false zstd en_US Etc/UTC
container_build_run bookworm flux minimum i386 livekit-mos default false true false zstd en_US Etc/UTC
container_build_run buster xfce minimum amd64 livekit-mos default false true false zstd en_US Etc/UTC
container_build_run buster xfce minimum i386 livekit-mos default false true false zstd en_US Etc/UTC
container_build_run bookworm xfce maximum amd64 livekit-mos default false true true zstd en_US Etc/UTC
container_build_run bookworm xfce-ultra ultra amd64 livekit-mos default false true true zstd en_US Etc/UTC
container_build_run bookworm xfce-puzzle puzzle amd64 livekit-mos default false true true zstd en_US Etc/UTC
container_build_run bookworm xfce-puzzle-base puzzle amd64 livekit-mos default false true true zstd en_US Etc/UTC
container_build_run bookworm xfce standard amd64 livekit-mos default false true false zstd en_US Etc/UTC
container_build_run bookworm xfce standard i386 livekit-mos default false true false zstd en_US Etc/UTC
# Russian
container_build_run bookworm flux minimum amd64 livekit-mos default false true false zstd ru_RU Etc/UTC
container_build_run bookworm flux minimum i386 livekit-mos default false true false zstd ru_RU Etc/UTC
container_build_run buster xfce minimum amd64 livekit-mos default false true false zstd ru_RU Etc/UTC
container_build_run buster xfce minimum i386 livekit-mos default false true false zstd ru_RU Etc/UTC
container_build_run bookworm xfce standard amd64 livekit-mos default false true false zstd ru_RU Etc/UTC
container_build_run bookworm xfce standard i386 livekit-mos default false true false zstd ru_RU Etc/UTC
container_build_run bookworm xfce maximum amd64 livekit-mos default false true true zstd ru_RU Etc/UTC
container_build_run bookworm xfce-ultra ultra amd64 livekit-mos default false true true zstd ru_RU Etc/UTC
container_build_run bookworm xfce-puzzle puzzle amd64 livekit-mos default false true true zstd ru_RU Etc/UTC
container_build_run bookworm xfce-puzzle-base puzzle amd64 livekit-mos default false true true zstd ru_RU Etc/UTC
# Spanish
container_build_run bookworm flux minimum amd64 livekit-mos default false true false zstd es_ES Etc/UTC
container_build_run bookworm flux minimum i386 livekit-mos default false true false zstd es_ES Etc/UTC
container_build_run buster xfce minimum amd64 livekit-mos default false true false zstd es_ES Etc/UTC
container_build_run buster xfce minimum i386 livekit-mos default false true false zstd es_ES Etc/UTC
container_build_run bookworm xfce maximum amd64 livekit-mos default false true true zstd es_ES Etc/UTC
container_build_run bookworm xfce-ultra ultra amd64 livekit-mos default false true true zstd es_ES Etc/UTC
container_build_run bookworm xfce-puzzle puzzle amd64 livekit-mos default false true true zstd es_ES Etc/UTC
container_build_run bookworm xfce-puzzle-base puzzle amd64 livekit-mos default false true true zstd es_ES Etc/UTC
container_build_run bookworm xfce standard amd64 livekit-mos default false true false zstd es_ES Etc/UTC
container_build_run bookworm xfce standard i386 livekit-mos default false true false zstd es_ES Etc/UTC
# Portugal
container_build_run bookworm flux minimum amd64 livekit-mos default false true false zstd pt_BR Etc/UTC
container_build_run bookworm flux minimum i386 livekit-mos default false true false zstd pt_BR Etc/UTC
container_build_run buster xfce minimum amd64 livekit-mos default false true false zstd pt_BR Etc/UTC
container_build_run buster xfce minimum i386 livekit-mos default false true false zstd pt_BR Etc/UTC
container_build_run bookworm xfce maximum amd64 livekit-mos default false true true zstd pt_BR Etc/UTC
container_build_run bookworm xfce-ultra ultra amd64 livekit-mos default false true true zstd pt_BR Etc/UTC
container_build_run bookworm xfce-puzzle puzzle amd64 livekit-mos default false true true zstd pt_BR Etc/UTC
container_build_run bookworm xfce-puzzle-base puzzle amd64 livekit-mos default false true true zstd pt_BR Etc/UTC
container_build_run bookworm xfce standard amd64 livekit-mos default false true false zstd pt_BR Etc/UTC
container_build_run bookworm xfce standard i386 livekit-mos default false true false zstd pt_BR Etc/UTC
