#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

apt-get update

# install packages
#!!!the name of the main application of the module must be specified in the first line of package.list!!!
if [ -f $SCRIPT_DIR/package.list ]; then
        case $DISTRIBUTION in
        bookworm | trixie | testing | sid | jammy | noble)
                install_packages --package-list "$SCRIPT_DIR/package.list"
                ;;
        *)
                install_packages --package-list "$SCRIPT_DIR/package.list"
                ;;
        esac
        PACKAGE=$(head -n 1 $SCRIPT_DIR/package.list)
        echo "PACKAGE=$PACKAGE" >/.package
        echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g' | sed 's/:/-/g')" >>/.package
fi

echo "nbd
" >>/etc/modules

if grep -q nfs-common "$SCRIPT_DIR/package.list"; then
    systemctl disable rpcbind
fi
