#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

apt-get update -y >>$OUTPUT 2>&1 &&
    curl -s https://api.github.com/repos/rescuezilla/rescuezilla/releases/latest | grep browser_download_url | grep '\.deb' | cut -d '"' -f 4 | wget -i - &&
    apt-get -y install ./rescuezilla*.deb >>$OUTPUT 2>&1

