#!/bin/bash

apt-get update >>$OUTPUT 2>&1
apt-get install --yes --no-install-recommends chromium chromium-sandbox >>$OUTPUT 2>&1

echo 'export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --disk-cache-dir=/dev/null --disk-cache-size=1"' >>/etc/chromium.d/default-flags

rm -Rf /usr/share/icons/gnome/256x256 >>$OUTPUT 2>&1
#rm -Rf /root/.fluxbox
#rm -Rf /root/.fluxbox/kblayout
#rm -Rf /root/.gtk-bookmarks
#rm -Rf /var/lib/wicd/dhclient.conf
rm -Rf /usr/share/applications/chromium.desktop >>$OUTPUT 2>&1
