#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

language_to_array

pkg update

# install packages
#!!!the name of the main application of the module must be specified in the first line of package.list!!!
if [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
    add-apt-repository ppa:atareao/telegram
    cat <<EOF >/etc/apt/preferences.d/telegram
Package: *
Pin: release o=LP-PPA-atareao-telegram
Pin-Priority: 1001
EOF
fi
if [ -f $SCRIPT_DIR/package.list ]; then
    case $DISTRIBUTION in
    buster | bullseye)
        install_packages --package-list="$SCRIPT_DIR/package.list" --sed-script="s,$,/$DISTRIBUTION-backports,"
        PACKAGE="$(head -n 1 $SCRIPT_DIR/package.list)"
        ;;
    *)
        if [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
            pkg install telegram
            PACKAGE="telegram"
        else
            install_packages --package-list="$SCRIPT_DIR/package.list"
            PACKAGE="$(head -n 1 $SCRIPT_DIR/package.list)"
        fi
        ;;
    esac

    echo "PACKAGE=$PACKAGE" >/.package
    echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g' | sed 's/:/-/g')" >>/.package
fi
