#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

local VERSION
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

get_latest_release() {
  wget -q -O- "https://api.github.com/repos/$1/releases/latest" | # Get latest release from GitHub api
    grep '"tag_name":' |                                          # Get tag line
    sed -E 's/.*"([^"]+)".*/\1/'                                  # Pluck JSON value
}

KERNEL_ARCH="amd64"

get_latest_package_url() {
  wget -q -O- "https://api.github.com/repos/$1/releases/latest" | # Get latest release from GitHub api
    grep '"browser_download_url":' | grep "$KERNEL_ARCH.deb"\" |  # Get tag line
    sed -E 's/.*"([^"]+)".*/\1/'                                  # Pluck JSON value
}

URL=$(get_latest_package VSCodium/vscodium)
PACKAGE=$(ls codium*$KERNEL_ARCH.deb)

wget -c $URL &&
  $APT_CMD update $APT_OPTIONS &&
  $APT_CMD install $APT_OPTIONS ./$PACKAGE &&
  rm -f ./$PACKAGE
