#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

get_latest_package_url() {
  wget -q -O- "https://api.github.com/repos/$1/releases/latest" |      # Get latest release from GitHub api
    grep '"browser_download_url":' | grep "$DISTRIBUTION_ARCH.deb"\" | # Get tag line
    sed -E 's/.*"([^"]+)".*/\1/'                                       # Pluck JSON value
}

URL=$(get_latest_package_url VSCodium/vscodium)

wget -c $URL &&
  $APT_CMD update $APT_OPTIONS &&
  $APT_CMD install $APT_OPTIONS ./$(ls codium*$DISTRIBUTION_ARCH.deb) &&
  rm -f ./$(ls codium*$DISTRIBUTION_ARCH.deb)
