#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# install packages
if [ -f $SCRIPT_DIR/package.list ]; then
    #sudo DEBIAN_FRONTEND=$DEBIAN_FRONTEND_TYPE \
        $APT_CMD update >>$OUTPUT 2>&1 &&
        #sudo DEBIAN_FRONTEND=$DEBIAN_FRONTEND_TYPE \
            $APT_CMD install $APT_OPTIONS \
            $(grep -vE "^\s*#" $SCRIPT_DIR/package.list | tr "\n" " ") >>$OUTPUT 2>&1
fi
