#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

apt-get $INSTALL_OPTIONS update >>$OUTPUT 2>&1 &&
    DEBIAN_FRONTEND=noninteractive \
        apt-get $INSTALL_OPTIONS install \
        software-properties-common >>$OUTPUT 2>&1

#apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5
curl -fsSL https://download.onlyoffice.com/GPG-KEY-ONLYOFFICE | gpg --dearmor >/etc/apt/trusted.gpg.d/onlyoffice.gpg
add-apt-repository 'deb https://download.onlyoffice.com/repo/debian squeeze main'

# install packages
apt-get $INSTALL_OPTIONS update >>$OUTPUT 2>&1 &&
    DEBIAN_FRONTEND=noninteractive \
        apt-get $INSTALL_OPTIONS install \
        onlyoffice-desktopeditors >>$OUTPUT 2>&1

PACKAGE="onlyoffice-desktopeditors"
echo "PACKAGE=$PACKAGE" >/.package
echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g' | sed 's/:/-/g')" >>/.package
