#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

pkg update

pkg install software-properties-common

add-apt-repository ppa:elementary-os/stable
add-apt-repository ppa:elementary-os/os-patches

pkg update
pkg upgrade

# install packages
pkg install gdm3 mesa-vulkan-drivers mesa-vdpau-drivers mesa-va-drivers mesa-utils gnome-session \
    elementary-icon-theme elementary-default-settings elementary-desktop
