#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
#set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

$APT_CMD update >>$OUTPUT 2>&1 &&
    $APT_CMD install $APT_OPTIONS gnupg >>$OUTPUT 2>&1

if [ -f /usr/bin/dpkg-query ] 2>/dev/null; then
    KERNEL=$(dpkg-query -W -f='${binary:Package}\n' linux-image-* | head -n 1 | sed 's/linux-image-//')
else
    KERNEL=$(uname -r)
fi

VBOX_VERSION=$(wget -O- https://download.virtualbox.org/virtualbox/LATEST.TXT)

#$APT_CMD update >>$OUTPUT 2>&1
#$APT_CMD install $APT_OPTIONS dirmngr apt-transport-https >>$OUTPUT 2>&1

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A2F683C52980AECF

echo "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian $DISTRIBUTION contrib" >/etc/apt/sources.list.d/virtualbox.list

# install packages
$APT_CMD update >>$OUTPUT 2>&1
$APT_CMD install $APT_OPTIONS virtualbox-6.1 >>$OUTPUT 2>&1

cat <<'EOF' >/usr/bin/vbox-allowuser.sh
#!/bin/bash
if ! grep vboxusers group | grep $(id -nu 1000) >/dev/null; then
    usermod -a -G vboxusers $(id -nu 1000)
fi
EOF
chmod +x /usr/bin/vbox-allowuser.sh
cat <<EOF >/usr/lib/systemd/system/vbox-allowuser.service
[Unit]
Description=Allow user to use virtualbox
#After=network.target

[Service]
Type=oneshot
ExecStart=/usr/bin/vbox-allowuser.sh
RemainAfterExit=true
ExecStop=
StandardOutput=journal

[Install]
WantedBy=multi-user.target
EOF
systemctl enable vbox-allowuser.service >>$OUTPUT 2>&1

wget -c https://download.virtualbox.org/virtualbox/$VBOX_VERSION/Oracle_VM_VirtualBox_Extension_Pack-$VBOX_VERSION.vbox-extpack

echo y | VBoxManage extpack install --replace $SCRIPT_DIR/Oracle_VM_VirtualBox_Extension_Pack-$VBOX_VERSION.vbox-extpack

rm -f $SCRIPT_DIR/Oracle_VM_VirtualBox_Extension_Pack-$VBOX_VERSION.vbox-extpack
