#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

function language_to_array() {
    local IFS
    IFS="_"
    LNG=($LOCALE)
}
language_to_array

function install_packages() {
    local PACKAGE_LIST="$1"
    apt-get $INSTALL_OPTIONS update >>$OUTPUT 2>&1
    # install packages
    #!!!the name of the main application of the module must be specified in the first line of package.list!!!
    if [ -f $SCRIPT_DIR/$PACKAGE_LIST ]; then
        DEBIAN_FRONTEND=noninteractive \
            apt-get $INSTALL_OPTIONS install \
            $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_LIST | tr "\n" " ") >>$OUTPUT 2>&1
        PACKAGE=$(head -n 1 $SCRIPT_DIR/$PACKAGE_LIST)
        echo "PACKAGE=$PACKAGE" >/.package
        echo "VERSION=$(dpkg -s $PACKAGE | grep Version | sed 's/Version: //g' | sed 's/:/-/g')" >>/.package
    fi
}

install_packages package.list