#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

apt-get update >>$OUTPUT 2>&1

wget http://mirror.yandex.ru/mirrors/MX-Linux/MX-Packages/antix/sid/pool/main/a/adwaita-icon-theme-antix/adwaita-icon-theme-antix_3.30.2~antix1_all.deb
wget http://mirror.yandex.ru/mirrors/MX-Linux/MX-Packages/antix/sid/pool/main/g/gtkdialog/gtkdialog_0.8.3-2mx150%2B1_amd64.deb

# install packages
if [ -f $SCRIPT_DIR/$PACKAGE_VARIANT.list ]; then
    DEBIAN_FRONTEND=noninteractive \
        apt-get install -y \
        $(grep -vE "^\s*#" $SCRIPT_DIR/$PACKAGE_VARIANT.list | tr "\n" " ") ./adwaita-icon-theme-antix_3.30.2~antix1_all.deb ./gtkdialog_0.8.3-2mx150+1_amd64.deb >>$OUTPUT 2>&1
fi

rm /*.deb
